### ISSUE TITLE
Allow for spaces in OpenApiComponentsRules.cs 

### ISSUE THREAD

**Issue by JosephNewman26** [microsoft/OpenAPI.NET#1028]
This rule https://github.com/microsoft/OpenAPI.NET/blob/vnext/src/Microsoft.OpenApi/Validations/Rules/OpenApiComponentsRules.cs 
does not seem to allow spaces in component names, which causes an error when we are using our custom linter. 

` public static Regex KeyRegex = new Regex(@"^[a-zA-Z0-9\.\-_]+$")`

Is there a reason for this? We cannot seem to find any guidelines or supporting material for this rule, if there are please let us know.

Best and Thank you.

**Comment by darrelmiller** [comment]
As per the specification for OpenAPI 3.0.3

> All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.

https://spec.openapis.org/oas/v3.0.3#fixed-fields-5

Spaces are not allowed in component names because most programming languages do not allow spaces in type names.
