### ISSUE TITLE
Unexpected 'collectionFormat' writing Swagger 2

### ISSUE THREAD

**Issue by richardkaspar** [microsoft/OpenAPI.NET#1053]
**Describe the bug**
Writing a Swagger 2 file with parameter differ between Microsoft.OpenApi.Readers 1.3.2  and Microsoft.OpenApi.Readers 1.4.1.

**To Reproduce**

Use the following code with Microsoft.OpenApi.Readers 1.3.2 and Microsoft.OpenApi.Readers 1.4.1.

    var doc = new OpenApiDocument
    {
        Paths = new OpenApiPaths
        {
            ["/foo"] = new()
            {
                Operations = new ConcurrentDictionary<OperationType, OpenApiOperation>
                {
                    [OperationType.Get] = new()
                    {
                        Parameters = new List<OpenApiParameter>
                        {
                            new()
                            {
                                In = ParameterLocation.Query,
                                Schema = new OpenApiSchema{Type = "string"}
                            }
                        }
                    }
                }
            }
        }
    };
    var sb     = new StringBuilder();
    var writer = new OpenApiYamlWriter(new StringWriter(sb, new CultureInfo("en_us")));
    
    doc.SerializeAsV2(writer);
    
    File.WriteAllText(writeFile, sb.ToString());

Microsoft.OpenApi.Readers 1.3.2:
    
    swagger: '2.0'
    info: { }
    paths:
      /foo:
        get:
          parameters:
            - in: query
              type: string
          responses: { }

Microsoft.OpenApi.Readers 1.4.1:
    
    swagger: '2.0'
    info: { }
    paths:
      /foo:
        get:
          parameters:
            - in: query
              type: string
              collectionFormat: multi
          responses: { }

**Expected behavior**
'collectionFormat' should not be written.

**Screenshots/Code Snippets**
![grafik](https://user-images.githubusercontent.com/98944439/197994234-2845f95a-090e-4c69-b670-37c0616856c7.png)

**Additional context**
https://swagger.io/docs/specification/2-0/describing-parameters/
![grafik](https://user-images.githubusercontent.com/98944439/197993230-4363f0c7-3edb-48d4-bb1a-7ea5aac9231c.png)

**Comment by MaggieKimani1** [comment]
Thanks for reporting this @richardkaspar. This is definitely a bug we need to investigate as per the documentation, we should only be writing out the `collectionFormat`  property for multi-value parameters with `type: array`
This might have arisen as a result of setting a default style parameter in v1.4.1.
