### ISSUE TITLE
Add support for OpenAPI schema generation for POCOs

### ISSUE THREAD

**Issue by captainsafia** [microsoft/OpenAPI.NET#1087]
This is related to https://github.com/microsoft/OpenAPI.NET/issues/836.

For certain native .NET types, it would be great if OpenAPI.NET could provide the authorative OpenApiSchema definitions for these types. Current prototypes maintain a dictionary like this:

```csharp
private static readonly Dictionary<Type, Func<OpenApiSchema>> _primitiveTypeToOpenApiSchema =
        new()
        {
            [typeof(bool)] = () => new OpenApiSchema { Type = "boolean" },
            [typeof(byte)] = () => new OpenApiSchema { Type = "string", Format = "byte" },
            [typeof(int)] = () => new OpenApiSchema { Type = "integer", Format = "int32" },
            ...
            [typeof(DateTime)] = () => new OpenApiSchema { Type = "string", Format = "date-time" },
            [typeof(DateTimeOffset)] = () => new OpenApiSchema { Type = "string", Format = "date-time" },
            [typeof(Guid)] = () => new OpenApiSchema { Type = "string", Format = "uuid" },
            [typeof(char)] = () => new OpenApiSchema { Type = "string" }
        };
```

And there a variety of open source packages/projects that maintain their own associations (see [this](https://github.com/ipjohnson/EasyRpc/blob/012cb2731b5c2ef36a909c1c2e73220a14c5fec5/src/EasyRpc.AspNetCore/Documentation/KnownOpenApiTypeMapper.cs), [this](https://github.com/vitalybibikov/AzureExtensions.Swashbuckle/blob/d4d33d526c9ce19cff2a522ad95f7d49d2eab8c9/src/AzureFunctions.Extensions.Swashbuckle/AzureFunctions.Extensions.Swashbuckle/SwashBuckle/Filters/Mapper/TypeMapper.cs), and [this](https://github.com/JamesRandall/FunctionMonkey/blob/45f4b7efc843f13a59899cdaaf470753d99bb212/Source/FunctionMonkey.Compiler.Core/Extensions/TypeExtensions.cs)).

Since this is a finite set of mappings, it would be great if they would be centralized in the OpenAPI.NET package to avoid duplication and ambiguity about the right schemas to generate for different native types in .NET.

cc: @darrelmiller  @baywet

**Comment by baywet** [comment]
Additionally, Kiota is doing something similar to get from OpenAPI type/format to dotnet (or other languages) types. Having the opposite dictionary would be helpful as well.

CC @CarolKigoonya to queue this in the pipeline
