### ISSUE TITLE
`OpenApiDate` values are serialized as `DateTime` with timestamps

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET#1101]
This issue has been transferred from the `OpenAPI.NET.OData` repo. Details can be found here: https://github.com/microsoft/OpenAPI.NET.OData/issues/90

**Comment by darrelmiller** [comment]
@irvinesunday This change needs to be reverted.  It is a breaking change as ToShortDateString is culture sensitive.

**Comment by MaggieKimani1** [comment]
> @irvinesunday This change needs to be reverted. It is a breaking change as ToShortDateString is culture sensitive. I recommend using `.ToString("o").Substring(0,10)` This will create a ISO 8601 formatted datetime but only take the date portion.

This is now fixed by [this PR](https://github.com/microsoft/OpenAPI.NET/pull/1118)
