### ISSUE TITLE
When "Components" exist only of references it cannot be parsed by the Reader.

### ISSUE THREAD

**Issue by elize-vdr** [microsoft/OpenAPI.NET#1126]
**Describe the bug**
When parsing an OpenAPI specification using the Reader and the "components" node fixed fields consist of references then the parsing throws an exception. The code fails when the nodes in the "component" node is read, because the code expects the nodes to be MapNodes but they are not. 

Execution specifically fails in file MapNode.cs at method:
```
public override Dictionary<string, T> CreateMapWithReference<T>(
            ReferenceType referenceType,
            Func<MapNode, T> map)
```
			
at line where nodes are mapped this:
```
var nodes = yamlMap.Select(....)
```

and specifically on this code:
```
entry = (
			key: key,
			value: map(new MapNode(Context, (YamlMappingNode)n.Value))
		);
```
		
The `response` node's value in the `contents` is not a YamlMappingNode but a YamlScalarNode (that is `n.Value` in the code above), for example the `response` node, it is a key-value pair "$ref" and value "./schemas/_index.yaml", so this throws an exception of:
"Unable to cast object of type 'SharpYaml.Serialization.YamlScalarNode' to type 'SharpYaml.Serialization.YamlMappingNode'."
because it is trying to cast a ScalarNode to a MapNode. 

So if the "contents" nodes are not necessarily also MapNodes, then how will such a scenario be resolved?
How is this example with the multiple references read?

**To Reproduce**
I use the yaml file from [this example](https://github.com/dgarcia360/openapi-boilerplate/blob/master/src/openapi.yaml), I only parse the primary spec document for now, I am experimenting with how to parse multiple document specifictions such as this example, but I start with the primary document only to see if it can be parsed, this example does not seem to be entirely according to the OpenApi standard, since in the standard according to the [Components object's fixed fields](https://spec.openapis.org/oas/latest.html#fixed-fields-5) the `schemas` cannot be a reference object, so I removed the `schemas` field for testing purposes, but the `parameters` and `responses` can indeed be reference objetcs.
I used this `openapi.yaml` file and then hard-coded it as a string in a test program and read it with the reader. The code snippet is in the Code snippet section below.

**Expected behavior**
If a node in the "components" node is not a MapNode but a simple reference node then this should work and the components should be read correctly with each node indicating it is an external reference.

**Screenshots/Code Snippets**
The code used to produce the error:
```
using System;
using System.IO;
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Readers;

namespace OpenApiParserLibrary
{
    public class ParseOpenApiDocument
    {
        public static OpenApiDocument Parse(out OpenApiDiagnostic diagnostic)
        {
            var documentContent = @"openapi: ""3.0.0""
info:
  version: 1.0.0
  title: Swagger Petstore
  description: Multi-file boilerplate for OpenAPI Specification.
  license:
    name: MIT
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
servers:
  - url: http://petstore.swagger.io/v1
tags:
  - name: pets
paths:
  /pets:
    $ref: ""./resources/pets.yaml""
  /pets/{petId}:
    $ref: ""./resources/pet.yaml""
components:
  parameters:
    $ref: ""./parameters/_index.yaml""
  responses:
    $ref: ""./responses/_index.yaml""";
            
            var stream = new MemoryStream();
            var writer = new StreamWriter(stream);
            writer.Write(documentContent);
            writer.Flush();
            stream.Position = 0;
            
            try
            {
                var openApiDocument = new OpenApiStreamReader().Read(stream, out diagnostic);
                return openApiDocument;
            }
            catch (Exception ex)
            {
                diagnostic = new OpenApiDiagnostic();
                diagnostic.Errors.Add(new OpenApiError("Exception", ex.Message));
                return new OpenApiDocument();
            }
        }
    }
}
```

**Comment by darrelmiller** [comment]
The example referenced is not valid OpenAPI. 

e.g.  $ref is not valid in this example
```
components:
  parameters:
    $ref: ""./parameters/_index.yaml""
```
The `parameters` property of `components` is defined as map where the key is an identifier for the reusable parameter object. https://spec.openapis.org/oas/v3.1.0.html#fixed-fields-5

Listing those keys in the referenced file is not supported.

The OpenAPI would need to be re-written as the following to be valid.

```yaml
components:
  parameters:
    petId: 
      $ref: "./parameters/path/petId.yaml"
    limit: 
      $ref: "./parameters/query/limit.yaml"
```

The bad news is that the current version of OpenAPI.NET still wouldn't handle that properly as it currently doesn't support references to fragments.  For OpenAPI.NET to resolve these as external references the external files would need to be complete OpenAPI documents themselves.  Then the OpenAPI could be as follows:

```yaml
components:
  parameters:
    petId: 
      $ref: "./parameters/path.yaml#/components/parameters/petId"
    limit: 
      $ref: "./parameters/query.yaml#/components/parameters/limit"
```

With the work we are doing to support OpenAPI 3.1 we expect to be able to address this limitation.  These new capabilities will be in our v2 of the library.

**Comment by elize-vdr** [comment]
Thank you Darrel for taking the time to look at this, my bad, you are absolutely right, I overlooked the fact that it is a reference within a map, yes that example is then invalid, will rather post something on that GitHub repository ;)
