### ISSUE TITLE
Property getter that changes model data is not the best way (imho)

### ISSUE THREAD

**Issue by richardkaspar** [microsoft/OpenAPI.NET#1132]
Version 1.4.5:

Reading the value of OpenApiParameter.Style can change the value (Line 80 - SetDefaultStyleValue):
![grafik](https://user-images.githubusercontent.com/98944439/212936539-58ac0fc4-791a-461d-844f-e2b7ab5968ca.png)

A member starting with "_" is public (Line 20):
![grafik](https://user-images.githubusercontent.com/98944439/212940714-5eaa0dd8-b672-4003-a5b5-b97d0c0a3089.png)

It was not easy to find out, why my code does not work as expected and what I have to do.

**Comment by richardkaspar** [comment]
In OpenApiParameter.cs exists code that calls 'Style', example:

![grafik](https://user-images.githubusercontent.com/98944439/213127360-e661608b-6d1c-477e-8afc-97906f66d896.png)

When '_explode' is null and  '_style' is null before reading 'Explode', after reading the value of '_style' will not be null.

Nearly every call of 'Style' in OpenApiParameter.cs has a similar problem.

Please change the getter of 'Style' so that it never changes model data.
Maybe a property 'StyleOrDefault' can be added returning the value, that Style does return now, but without changing model data.

**Comment by MaggieKimani1** [comment]
This fix will be released with the 2.0 version of this library as it has a breaking change.
