### ISSUE TITLE
Error when reading OpanApi 3.1.0 document

### ISSUE THREAD

**Issue by elize-vdr** [microsoft/OpenAPI.NET#1133]
**Is your feature request related to a problem? Please describe.**
I parsed an OpenApi 3.1.0 document with the Readers and got this error:
```
[Exception] One or more errors occurred. (OpenAPI specification version '3.1.0' is not supported.)
```

**Describe the solution you'd like**
When will it support 3.1.0?

**Comment by MaggieKimani1** [comment]
@elize-vdr this work is currently ongoing and will go live when we release v2.0.

**Comment by elize-vdr** [comment]
Any indication when release v2.0 will be released please? Will it still be in 2023 or 2024?

**Comment by MaggieKimani1** [comment]
Hi @elize-vdr , this work has been planned for CY23H1

**Comment by elize-vdr** [comment]
Thank you so much!
