### ISSUE TITLE
Referenced files used to define shared `components` are forced to contain `paths`

### ISSUE THREAD

**Issue by elize-vdr** [microsoft/OpenAPI.NET#1134]
**Is your feature request related to a problem? Please describe.**
We have 2 APIs on the same domain that use a lot of similar structures and therefore we have a shared referenced file with the common `components` defined. When I load the "primary" API document which then references this "common" document I get an error that the "paths" must is REQUIRED. ("[#/paths] Paths must be a map/object"
```
            "[#/paths] [File: common-definitions_v4.yaml] Paths must be a map/object",
            "[#/paths] [File: common-definitions_v4.yaml] The field 'paths' in 'document' object is REQUIRED."
```
We analyze APIs for our clients when we find errors we tell them their OpenAPI contract has errors, which is not so nice because this is not really supposed to be an error, perhaps a warning. Is it not true that only the primary document the `paths` should be required?

**Describe the solution you'd like**
When a referenced document does not have the `paths` element it should not generate an error.

**Comment by elize-vdr** [comment]
Any thoughts on this? I am wondering if my explanation was any good, may be I explained it so badle, which is possible, that it makes no sense. Should I build an example to explain better? This parser library will not work for use if it requires referenced documents to also have all the OpenApi schema elements that the main document has. Will there be any change to this in future?

**Comment by MaggieKimani1** [comment]
@elize-vdr can you please provide an example for us to reproduce this issue?

**Comment by darrelmiller** [comment]
In the current implementation of OpenAPI.NET we expect all externally referenced files to be valid OpenAPI descriptions.
OpenAPI 3.0 makes paths required, but it can be empty.
In OpenAPI 3.1 paths is no longer required.  We are working on OpenAPI 3.1 support.
Hopefully eventually we will support referencing external fragments that are not compliant OpenAPI descriptions, however, it is challenging to implement in a way that will perform well.

Having said that, I would not recommend using external fragments that are not OpenAPI documents unless the external documents are valid JSON Schema files.  I expect the next major version of OpenAPI to drop support for random external fragments.

**Comment by elize-vdr** [comment]
Hi Darrel, thank you very much for the feedback, leaving paths empty will already be workable for us. Then we wait for OpenAPI 3.1.0 release.
