### ISSUE TITLE
hidi doesn't return a failed exit code on validation error

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET#1141]
**Describe the bug**
hidi validate -d /some/invalid/path will result in a critical error in the console, however the exit code will be 0

**To Reproduce**
hidi validate -d /some/invalid/path will result in a critical error in the console, however the exit code will be 0

**Expected behavior**
exit code to be -1

**Comment by MaggieKimani1** [comment]
Related #900
