### ISSUE TITLE
hidi validate can't load unix path but transform can?

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET#1142]
**Describe the bug**
hidi validate -d /a/valid/unix/path.yaml will return 
`Could not validate the document, reason: Invalid URI: The Authority/Host could not be parsed.`

yet hidi transform --cs /another/valid/path.csdl -o /some/other/path.yaml will work.

We should align how source files are loaded to get a consistent behaviour.

**Comment by MaggieKimani1** [comment]
@baywet please provide the absolute path you're trying to parse in the metadata repo for me to reproduce this.

**Comment by baywet** [comment]
run is here https://github.com/microsoftgraph/msgraph-metadata/actions/runs/4019312471/jobs/6905992113
path being passed was something like this `/home/runner/work/msgraph-metadata/msgraph-metadata/openapi/v1.0/openapi.yaml`
