### ISSUE TITLE
[Reader] Error parsting property reference

### ISSUE THREAD

**Issue by Anakael** [microsoft/OpenAPI.NET#1165]
`Microsoft.OpenApi.Readers` version: 1.6.1

OpenApi spec:
```yaml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://petstore.swagger.io/v1
paths:
  /pets/{petId}:
    parameters:
      - name: petId
        in: path
        required: true
        description: The id of the pet to retrieve
        schema:
          $ref: "#/components/schemas/Pet/properties/id"
    put:
      summary: Info for a specific pet
      operationId: showPetById
      tags:
        - pets
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
```

parsing it with
```cs
OpenApiReaderSettings settings = new()
{
     ReferenceResolution = ReferenceResolutionSetting.ResolveAllReferences,
};
using FileStream stream = File.OpenRead(path);
OpenApiDocument? document = new OpenApiStreamReader().Read(stream, out OpenApiDiagnostic? diagnostic);
```

gives error: The reference string '/components/schemas/Pet/properties/id' has invalid format.
Expected behavior: Specification should be parsed successfully.

**Comment by MaggieKimani1** [comment]
The `ResolveAllReferences` ReferenceResolution setting is used to resolve external references. Try using `ResolveLocalReferences`

**Comment by MaggieKimani1** [comment]
The `ResolveAllReferences` reader setting is for resolving external references but your document only has local references. `ResolveLocalReferences` would be more suitable. 
In addition to that, `Properties` is not a referenceable component/element. During parsing, we only resolve references for components that are referenceable e.g. schemas, responses, parameters, headers etc.

**Comment by Anakael** [comment]
-> Properties is not a referenceable element/type
It is. There is an issue about that: https://github.com/OAI/OpenAPI-Specification/issues/2824
https://editor.swagger.io/ can read such reference.

**Comment by MaggieKimani1** [comment]
Thanks for the correction. Unfortunately our lib doesn't support this.

**Comment by Anakael** [comment]
Is there any plans to support this?

**Comment by MaggieKimani1** [comment]
Unfortunately, No.
