### ISSUE TITLE
OpenApiOperation copy constructor - RequestBody null not preserved

### ISSUE THREAD

**Issue by dldl-cmd** [microsoft/OpenAPI.NET#1192]
**Describe the bug**
OpenApiOperation copy constructor: `public OpenApiOperation(OpenApiOperation operation)` changes a `null` in the `RequestBody` into an object instance.

**To Reproduce**
```C#
var operation = new OpenApiOperation();
//operation.RequestBody = null is the default
var copiedOperation = new OpenApiOperation(operation);
```
`copiedOperation.RequestBody` is an `new OpenApiRequestBody`.

**Expected behavior**
`copiedOperation.RequestBody` should also be null, as on the source object. 

https://github.com/microsoft/OpenAPI.NET/blob/db02b957533b0fe9e0d880d580ad4c99f2bb0671/src/Microsoft.OpenApi/Models/OpenApiOperation.cs#L117-L132

I could provide a PR to fix this.

**Comment by MaggieKimani1** [comment]
@dldl-cmd please feel free to send a PR our way 🙂
