### ISSUE TITLE
OpenApiAny vs primitive type inconsistency

### ISSUE THREAD

**Issue by PerthCharern** [Microsoft/OpenAPI.NET#123]
@darrelmiller @xuzhg 

We have been using an OpenApiAny type (e.g. OpenApiString, OpenApiDouble) to represent strings, numbers, arrays, etc. in the property that can be of type OpenApiAny.

However, in other properties of a normal object, we simply use the C# primitive types like string, int.

This is semantically inconsistent in my opinion. An "Any" type in the spec simply means it can be anything. If we use OpenApiString to mean a string inside that "Any" type, we should exclusively use OpenApiString everywhere. If we use the C# primitive, then we should use the C# primitive everywhere.

Using OpenApiAny allows us to control the type to match what JSON schema allows and add some types recognized by the spec like Password, but will be a pain for our customers if they need to assign values with OpenApiAny everywhere since it's less intuitive to do so compared to just C# primitives.

**Comment by darrelmiller** [comment]
Based on the work done around extensions, I think OpenApiAny should remain as a simple way to allow folks who want strongly typed extensions to deserialize JSON/YAML via an OpenApiAny dom.  I think we can close this issue.

**Comment by PerthCharern** [comment]
I agree. I don't see a way out of using OpenApiAny. We'll keep it.
