### ISSUE TITLE
The examples in the readme dont compile

### ISSUE THREAD

**Issue by StingyJack** [microsoft/OpenAPI.NET#1353]
**Describe the bug**

This section specifically
``` csharp
var httpClient = new HttpClient
{
    BaseAddress = new Uri("https://raw.githubusercontent.com/OAI/OpenAPI-Specification/")
};

var stream = await httpClient.GetStreamAsync("master/examples/v3.0/petstore.yaml");

// Read V3 as YAML
var openApiDocument = new OpenApiStreamReader().Read(stream, out var diagnostic);

// Write V2 as JSON
var outputString = openApiDocument.Serialize(OpenApiSpecVersion.OpenApi2_0, OpenApiFormat.Json);
```
The last statement isnt valid.   There are functions for SerializeAsV3 and SerializeAsV2, but not Serialize.  They also take IOpenApiWriter parameters, of which the implementations are not easily locatable given GH's ever present search limitations.

**To Reproduce**
Paste the example in a console program and see if it works. 

**Expected behavior**
It would compile 

**Screenshots/Code Snippets**

That simple example of reading and writing an OAS requires much more typing than the README says. This was taken mostly from one of the OpenApiJsonWriter unit tests, though not verbatim as that seemed to have extra Write calls.

``` csharp
//read the file
var oasFilePath = @"c:\temp\MyOasFile.json";
using var fs = new FileStream(oasFilePath, new FileStreamOptions());
var oasDoc = new OpenApiStreamReader().Read(fs, var out diagnostic);  

//in here I am trimming out some paths that are unneeded then writing out the trimmed file

var sw = new StringWriter(CultureInfo.InvariantCulture);
var oasWriter = new OpenApiJsonWriter(sw);
oasDoc.SerializeAsV3(oasWriter);
oasWriter.Flush();
var oasContent = sw.GetStringBuilder().ToString();
var newFilePath = Path.ChangeExtension(oasFilePath, ".trimmed.json");
File.WriteAllText(newFilePath, oasContent);
```

**Comment by MaggieKimani1** [comment]
Thank you for pointing this out. We shall update the readme to reflect the updated snippet for serialization.

**Comment by StingyJack** [comment]
@MaggieKimani1 -  Also the readme mentions the [C# Comment / Annotation Processor](https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations)  but that repo has been archived and no explanation of the current state is given.  If the repo code is/was unusable it may be a good idea to remove the reference from this readme

**Comment by MaggieKimani1** [comment]
@StingyJack actually, we do have a `Serialize` method which acts as the entry point for the `SerializeAsV2()` or `SerializeAsV3()` in our `OpenApiSerializable` extensions here:https://github.com/microsoft/OpenAPI.NET/blob/ac2a8d1aa7a700e02424084d62d067b940f1b702/src/Microsoft.OpenApi/Extensions/OpenApiSerializableExtensions.cs#L171  so the example in the Readme is correct.

**Comment by MaggieKimani1** [comment]
> @MaggieKimani1 - Also the readme mentions the [C# Comment / Annotation Processor](https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations) but that repo has been archived and no explanation of the current state is given. If the repo code is/was unusable it may be a good idea to remove the reference from this readme

Though the project has been archived, we still have internal teams using the [CSharpAnnotations.DocumentGeneration](https://www.nuget.org/packages/Microsoft.OpenApi.CSharpAnnotations.DocumentGeneration) package which takes a dependency on this library to generate their OpenAPI hence the mention in our Readme.

**Comment by StingyJack** [comment]
@MaggieKimani1  this is what i see when copying the code into a console project.

![image](https://github.com/microsoft/OpenAPI.NET/assets/15381181/7795ab30-f0b6-46c9-b171-58e864ce75ec)

**Comment by StingyJack** [comment]
OK  I got it.    Serialize is an extension method that VS wasn't suggesting the namespace for . 

Why make it an extension method and not put it with the SerializeV2 and v3?

**Comment by darrelmiller** [comment]
It is an extension method because it can be applied to any type that implements IOpenApiSerializable.  There are a bunch of extensions for serializing different flavours and as the models have no base class, we would have needed to reimplement all of the overloads in all of the modeles.  In theory we could implement an abstract base class and put them there.  I think maybe a different option would be to just make sure that the extensions are not in a separate namespace.
