### ISSUE TITLE
How to stylize Open API

### ISSUE THREAD

**Issue by PerthCharern** [Microsoft/OpenAPI.NET#142]
@darrelmiller 

I'm seeing from the spec repo that

Open API Initiative is written with a space between Open and API, but OpenAPI Specification doesn't have that space.

https://github.com/OAI/OpenAPI-Specification

Is this intentional? If so, I can update our README to follow the same styling.

**Comment by darrelmiller** [comment]
It has been fixed. The Governing board approved removing the space in OpenAPI Initiative. :-)
