### ISSUE TITLE
`additionalProperties` schema is not parsed correctly

### ISSUE THREAD

**Issue by fpoppinga** [microsoft/OpenAPI.NET#1427]
**Describe the bug**
When parsing an OpenAPI spec which contains a schema for the `additionalProperties` field, the schema does not end up in the parsed `OpenApiDocument`. 

**To Reproduce**
Steps to reproduce the current behavior:

consider the following minimal spec (`example.yml`): 
```yaml
openapi: 3.0.0
info:
  title: Sample API
  version: 0.1.9
paths:
  /users:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  schema:
                    type: object
                    properties:
                      data:
                        type: string
```
And the code: 
```cs
using Microsoft.OpenApi.Models;
using Microsoft.OpenApi.Readers;

var document = new OpenApiStreamReader().Read(File.OpenRead("example.yml"), out var diagnostics);

var additionalProperties = document.Paths["/users"].Operations[OperationType.Get].Responses[
    "200"
].Content["application/json"]
    .Schema
    .AdditionalProperties;

Console.WriteLine(value: additionalProperties.Properties.Count); // prints "0"
```

This makes it impossible, to generate code based on the type of the additional properties (cf. [#microsoft/kiota/62](https://github.com/microsoft/kiota/issues/62) )

**Expected behavior**

I would expect the `additionalProperties` schema to be parsed and contain the schema of type `"object"` with the properties dictionary containing a field `data` of type `string`. 
 
**Additional context**

I think the parsing is in principle implemented in [OpenApiSchemaDeserializer.cs#L161](https://github.com/microsoft/OpenAPI.NET/blob/976c9f59adb53b846a935bb2c318d2364be1c333/src/Microsoft.OpenApi.Readers/V3/OpenApiSchemaDeserializer.cs#L161). However, somewhere there must be a bug.

**Comment by baywet** [comment]
Thanks for reporting this!
Is this something you'd be willing to look into further and submit a pull request for?

**Comment by fpoppinga** [comment]
I will see if I can have a look this weekend ;-)

**Comment by MaggieKimani1** [comment]
@fpoppinga the `additionalProperties` field is already defined as an `OpenApiSchema` object so it shouldn't have a `schema` field nested within it. Instead the schema should be defined directly within the `additionalProperties` field. Try using this instead and you'll see the object being populated:
```yaml
openapi: 3.0.0
info:
  title: Sample API
  version: 0.1.9
paths:
  /users:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                    type: object
                    properties:
                      data:
                        type: string
```

**Comment by MaggieKimani1** [comment]
Closing this issue as its been addressed. Feel free to reopen if the response isn't satisfactory.
