### ISSUE TITLE
Remove the VSTS build

### ISSUE THREAD

**Issue by PerthCharern** [Microsoft/OpenAPI.NET#145]
@xuzhg @robward-ms  

Do we need both AppVeyor and VSTS builds for this repo? AppVeyor build is already Windows-based, so we are not getting additional coverage from VSTS.

**Comment by tomkerkhove** [comment]
Having something like AppVeyor will be great instead of VSTS since it does not allow externals to see the build failures.

If I would create a PR and it fails, I cannot fix it while with AppVeyor it will.
This is something I can pick up if you want help with it.

**Comment by PerthCharern** [comment]
Tom,

Thanks for the offer but we already have both AppVeyor and VSTS set up. :)

Only AppVeyor status is blocking check-in, and VSTS is just for informational purpose only.

Perth

On Dec 14, 2017, at 07:26, Tom Kerkhove <notifications@github.com<mailto:notifications@github.com>> wrote:


Having something like AppVeyor will be great instead of VSTS since it does not allow externals to see the build failures.

If I would create a PR and it fails, I cannot fix it while with AppVeyor it will.
This is something I can pick up if you want help with it.

**Comment by PerthCharern** [comment]
@xuzhg @robward-ms I don't think you guys need build with every PR update though. How about we change VSTS to only get triggered with push?

**Comment by xuzhg** [comment]
Ok. I turned off the PR trigger build

**Comment by xuzhg** [comment]
@PerthCharern Can I close this issue?

**Comment by PerthCharern** [comment]
Sure
