### ISSUE TITLE
[Hidi] Unable to slice an OpenApi document using `--filter-by-tags` or `--filter-by-operationIds`

### ISSUE THREAD

**Issue by peombwa** [microsoft/OpenAPI.NET#1451]
**Describe the bug**
Unable to slice and OpenApi document using `--filter-by-tags` or `--filter-by-operationIds`.

**To Reproduce**
Steps to reproduce the current behavior:
##### Slicing by `--filter-by-tags`
``` powershell
➜ hidi transform --openapi "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/default.yaml" --filter-by-tags "users.User" --output "slicedOpenAPI.yml" --clean-output
```

##### Slicing by `--filter-by-operationids`
``` powershell
➜ hidi transform --openapi "https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/openapi/v1.0/default.yaml" --filter-by-operationids "users.User.GetUser" --output "slicedOpenAPI.yml" --clean-output
```
Fail with:
``` powershell
crit: Microsoft.OpenApi.Hidi.Handlers.TransformCommandHandler[0]
      Could not transform the document, reason: No paths found for the supplied parameters.
```

**Expected behavior**
A sliced OpenAPI document should be generated based on the provided tags or operationIdsand save it in the designated `--output` location.

**Screenshots/Code Snippets**
N/A

**Additional context**
- `--filter-by-collection` works as expected.
##### Tested using
``` powershell
➜ hidi --version
1.3.2+1bec22207572dc611ea270089cdbd967ecb064c8
```

**Comment by MaggieKimani1** [comment]
Try lowercasing the `--filter-by-tags` value to `users.user` as it appears in the file:

![image](https://github.com/microsoft/OpenAPI.NET/assets/36787645/e5a4c1db-d530-41a5-b2aa-43d080bb0166)

Same for `--filter-by-operationIds` ----> `users.user.GetUser`

![image](https://github.com/microsoft/OpenAPI.NET/assets/36787645/300e9e3f-f63a-4089-84c5-02e65e6f54fe)
