### ISSUE TITLE
Create a OpenApiDocument.Serialize method 

### ISSUE THREAD

**Issue by darrelmiller** [Microsoft/OpenAPI.NET#150]
We have a OpenApiWriterSettings class that allows you to define the desired format of the output description.  However, we don't actually use that currently.

Having to call SerializeV2 vs SerializeV3 is not very clean.

**Comment by PerthCharern** [comment]
The methods below already exist in [OpenApiSerializableExtensions.cs](https://github.com/Microsoft/OpenAPI.NET/blob/4393e09cc1a93cd3a19d36bfce788c5c42575a0c/src/Microsoft.OpenApi/Extensions/OpenApiSerializableExtensions.cs). Would these work?

string version:         
```
public static string Serialize<T>(
            this T element,
            OpenApiSpecVersion specVersion,
            OpenApiFormat format)
            where T : IOpenApiSerializable
```
        
stream version:         
```
public static void Serialize<T>(
            this T element,
            Stream stream,
            OpenApiSpecVersion specVersion,
            OpenApiFormat format)
            where T : IOpenApiSerializable
```

**Comment by darrelmiller** [comment]
Ahh, missed those.  I did think we had addressed this.  That the one challenge of extension methods.  I should fix the example to use that.

**Comment by PerthCharern** [comment]
Oops sorry. I fat-fingered the close button. Didn't mean to close. :|

**Comment by darrelmiller** [comment]
Updated readme.
