### ISSUE TITLE
OpenAPI 3.1 to Swagger 2.0 conversion

### ISSUE THREAD

**Issue by Swimburger** [microsoft/OpenAPI.NET#1610]
I could deduce that in the upcoming version, we will be able to convert OpenAPI 3 specs to 2, but didn't specifically see 3.1.
Will 3.1 to 2.0 be possible? Obviously, some things can't be converted from 3 to 2, but that's acceptable for my use case.

Context: We have a very detailed 3.1 spec and want to use it to develop a custom connector for Logic Apps/Power Automate.
Unfortunately, the custom connector editor only accepts Swagger 2.0.

**Comment by MaggieKimani1** [comment]
Hi @Swimburger,
We're working on release a V2 that will support 3.1 -> 2.0 downcasting.

**Comment by JedWe** [comment]
@MaggieKimani1 any timeline when this will be available?

**Comment by MaggieKimani1** [comment]
Hi @JedWe,
Please refer to the ongoing conversation here: https://github.com/microsoft/OpenAPI.NET/issues/795

**Comment by baywet** [comment]
closing as duplicate
