### ISSUE TITLE
Typo in `IsFragrament`

### ISSUE THREAD

**Issue by glen-84** [microsoft/OpenAPI.NET#1652]
**Describe the bug**

`IsFragrament` should be `IsFragment`.

**OpenApi File To Reproduce**

n/a

**Expected behavior**

n/a

**Screenshots/Code Snippets**

n/a

**Additional context**

n/a

**Comment by MaggieKimani1** [comment]
Thanks for bringing this up. Fixing.

**Comment by MaggieKimani1** [comment]
This is a breaking issue hence the fix will go out with v2.0 of the lib
