### ISSUE TITLE
Update `MapOpenApiPrimitiveTypeToSimpleType` to handle integers and numbers without a format

### ISSUE THREAD

**Issue by glen-84** [microsoft/OpenAPI.NET#1657]
**Is your feature request related to a problem? Please describe.**

`OpenApiTypeMapper.MapOpenApiPrimitiveTypeToSimpleType` doesn't handle integers or numbers without a format.

**Describe the solution you'd like**

Add:

`("integer", null, false)`
`("integer", null, true)`
`("number", null, false)`
`("number", null, true)`

I'm not sure what types these should default to. Perhaps int + double.

**Describe alternatives you've considered**

copy/paste/update

**Additional context**

n/a

**Comment by MaggieKimani1** [comment]
@glen-84, just to be clear is this request for nullable types only or all data types?

**Comment by glen-84** [comment]
The 3rd element of the tuple is the nullability, so it would be for both nullable and non-nullable integers and numbers.
