### ISSUE TITLE
Attributes are moved to allOf instead of in the root of an object after updating Swashbuckle.AspNetCore from 6.5.0 to 6.6.2

### ISSUE THREAD

**Issue by DerGary** [microsoft/OpenAPI.NET#1711]
**Describe the bug**
We are using swagger cli to create a openapi json file. After Updating to the newest version the generated json file changed:
![image](https://github.com/microsoft/OpenAPI.NET/assets/4302467/9156c053-aaae-4e1d-a978-640dfacc4a88)
This seems to be wrong, as the hey-api client generator generates a wrong type out of it:
![image](https://github.com/microsoft/OpenAPI.NET/assets/4302467/ca6bd984-f11b-416f-a29a-b58a53db17ab)

**OpenApi File To Reproduce**
We are generating it from source so there is not open api file.

**Expected behavior**
I expect the previous behaviour, which is the left side of the comparison image.

**Additional context**
I also opened a bug in the Swashbuckle repository first, and was redirected from there.
[Swashbuckle Issue](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2964)

**Comment by MaggieKimani1** [comment]
@DerGary I don't think this is an issue with OpenAPI.NET. 
I've followed the issue trail and it seems this was an intended fix on the Swashbuckle side where the resulting schema is placed inside the `allOf` object https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2815
Feel free to reopen this issue if need be.
