### ISSUE TITLE
AsParameters not lifting Container type of properties

### ISSUE THREAD

**Issue by jgarciadelanoceda** [microsoft/OpenAPI.NET#1712]
**Describe the bug**

This bug comes from an issue we face using Swashbuckle. Analyzing the issue domaindrivendev/Swashbuckle.AspNetCore#2658, Swashbuckle is not capable of documenting the properties of a class that is used with AsParameters, because when checking the documentation Swashbuckle looks for the Container type and is not present in the documentation of the MetadataType

**Expected behavior**
To have documentation about the ContainerType to be able to set this documentation with Swashbuckle

**Comment by captainsafia** [comment]
@jgarciadelanoceda I don't believe this is a problem with the `Microsoft.OpenApi` package. The problem that you described seems to be related to how Swashbuckle handles the minimal API-specific parameter binding rules for `[AsParameters]`.

**Comment by jgarciadelanoceda** [comment]
Hello @captainsafia, thank you for helping me

The issue I found, that I think that could be the issue why SwashBuckle is not generating the XML comments for classes with AsParameters attribute is this one:

![image](https://github.com/microsoft/OpenAPI.NET/assets/6615999/2d3aa64e-61b0-4fc0-82ce-3ff0e48ddbf2)

The first point is from a Controller and the second one is from a MinimalApi with AsParameters attribute

**Comment by jgarciadelanoceda** [comment]
@captainsafia is this the right repo to this issue or is it aspnetCore?

**Comment by captainsafia** [comment]
@jgarciadelanoceda  `ApiDescriptionProvider` is from ASP.NET Core. Can you file the issue there and cc me?
