### ISSUE TITLE
OpenApiFilterService.CreateFilteredDocument fails if the document is missing the "components" field

### ISSUE THREAD

**Issue by kanales** [microsoft/OpenAPI.NET#1732]
**Describe the bug**
Calling `OpenApiFilterService.CreateFilteredDocument` on a document that does not contain the optional field `OpenApiDocument.Components` produces a `NullReferenceException`.

**OpenApi File To Reproduce**
Not an OpenApi File, but the following is enough to trigger it.

```csharp
var openApiDoc = new OpenApiDocument
{
    Info = new()
    {
        Title = "Test",
        Version = "1.0.0"
    },
    Paths = new()
    {
        ["/test"] = new OpenApiPathItem()
        {
            Operations = new Dictionary<OperationType, OpenApiOperation>
            {
                [OperationType.Get] = new OpenApiOperation()
            }
        }
    }
};

var requestUrls = new Dictionary<string, List<string>>()
{
    { "/test", ["GET"] }
};
var filterPredicate = OpenApiFilterService.CreatePredicate(null, null, requestUrls, openApiDoc);
var filteredDocument = OpenApiFilterService.CreateFilteredDocument(openApiDoc, filterPredicate); // Error!
```

**Expected behavior**
It should not fail, because the `Components` field is not mandatory. If it's necessary it should throw a more descriptive exception.

**Additional context**

**Comment by kanales** [comment]
I have a solution for this, but I don't seem to be able to push my branch.

**Comment by andrueastman** [comment]
Are you able to fork the repository and create a PR from there?

**Comment by kanales** [comment]
Yes that worked, thank you!
