### ISSUE TITLE
OpenAPI v3.1.0 compliance

### ISSUE THREAD

**Issue by brice-prunier-dev** [microsoft/OpenAPI.NET#1749]
**Is your feature request related to a problem? Please describe.**
I can't parse a v3.1.0 swagger.json what is a valid spec for more than 1 year.

"

**Describe the solution you'd like**
Implement OpenApi 3.1.0 version in OpenApi.net

**Describe alternatives you've considered**
None

**Additional context**
I get the following error message when i try to load a v3.1.0 swagger.json: "OpenAPI specification version '3.1.0' is not supported.

**Comment by baywet** [comment]
Hi @brice-prunier-dev 
Thanks for your interest and for reaching out.
This will be supported in the upcoming v2 of the library.
You can find more details in this issue #795
Closing as duplicate for now.
