### ISSUE TITLE
Produces/consumes in V2

### ISSUE THREAD

**Issue by talamram** [Microsoft/OpenAPI.NET#178]
Currently consumes label is not affecting the body content in the reader.
for example:

/uploadImage": {
			"post": {
				"tags": ["image"],
				"summary": "uploads an image",
				"description": "",
				"operationId": "uploadFile",
				"consumes": ["multipart/form-data"],
				"produces": ["application/json"],
				"parameters": [{
					"name": "Id",
					"in": "path",
					"description": "ID to update",
					"required": true,
					"type": "integer",
					"format": "int64"
				}],
				"responses": {
					"200": {
						"description": "successful operation",
						"schema": {
							"$ref": "#/definitions/ApiResponse"
						}
					}
				}
			}
		}

gives a "application/json" as body content and not "multipart/form-data" as should be.
I tried to change the consumes value to "application/xml" but still doesn't work.

**Comment by darrelmiller** [comment]
Thanks for the feedback.  We will investigate.

**Comment by PerthCharern** [comment]
There is a typo in the code. I'll fix this.
