### ISSUE TITLE
formData parameter in V2 is not supported

### ISSUE THREAD

**Issue by talamram** [Microsoft/OpenAPI.NET#179]
Parameters in formData are ignored by the reader.

fot example:
```json
"/uploadImage": {
			"post": {
				"tags": ["upload"],
				"summary": "uploads an image",
				"description": "",
				"operationId": "uploadFile",
				"consumes": ["application/xml"],
				"produces": ["application/json"],
				"parameters": [
				{
					"name": "additionalMetadata",
					"in": "formData",
					"description": "Additional data to pass to server",
					"required": true,
					"type": "string"
				}],
				"responses": {
					"200": {
						"description": "successful operation",
						"schema": {
							"$ref": "#/definitions/ApiResponse"
						}
					}
				}
			}
		}
```

is ignores the parameter

**Comment by darrelmiller** [comment]
Can you tell us a bit more about what you would expect to happen here?  The `consumes` property says 'application/xml' which is not compatible with supporting formData parameters.  Would you expect a multi-part form with one part formData and the other part xml?  Are you currently using tooling that does this?  As far as I know, the specification doesn't explicitly allow this.

**Comment by talamram** [comment]
Yes you right, "application/xml" in the consumes property should not be supported with formData parameters, but even when I tried to change the consumes property to be "application/x-www-form-urlencoded", the reader still ignored the formData parameters

**Comment by PerthCharern** [comment]
From a quick look at the code, it seems like we recognized the wrong keyword ("form" instead of "formData"). I will take a look a bit more and fix this.
