### ISSUE TITLE
Microsoft.OpenApi Assembly No Longer Signed as of 1.6.18

### ISSUE THREAD

**Issue by wsugarman** [microsoft/OpenAPI.NET#1796]
**Describe the bug**
As of [version 1.6.18 in Nuget.org](https://www.nuget.org/packages/Microsoft.OpenApi/1.6.18), the included `Microsoft.OpenApi.dll` assembly is no longer signed.

**Expected behavior**
The assemblies should be signed like in the previous package version.

**Comment by andrueastman** [comment]
Thanks for raising this @wsugarman 

Any chance you can take a look at this one @MaggieKimani1, @irvinesunday ? 
I believe the culprit is this PR https://github.com/microsoft/OpenAPI.NET/pull/1775 and it should probably look similar to https://github.com/microsoft/OpenAPI.NET.OData/pull/558

**Comment by wsugarman** [comment]
Thank you for the quick fix! I just want to confirm @andrueastman and @MaggieKimani1 that version `1.6.18` is ok to use?

**Comment by andrueastman** [comment]
@wsugarman There should be a new update pretty soon with signed binaries. This should be out once https://github.com/microsoft/OpenAPI.NET/pull/1802 is merged.

**Comment by wsugarman** [comment]
Great! Thank you so much!
