### ISSUE TITLE
Duplicate parameters on operation filter 

### ISSUE THREAD

**Issue by erwinkramer** [microsoft/OpenAPI.NET#1833]
**Describe the bug**
Getting duplicate parameter definitions when filtering on 2 or more operations that have the same parameters. That's an invalid OpenAPI definition.

**OpenApi File To Reproduce**
```bash
hidi transform -d https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/refs/heads/master/openapi/v1.0/openapi.yaml -f yaml -o ".\test.yaml" -v OpenApi3_0 --op certificateBasedAuthConfiguration.certificateBasedAuthConfiguration.UpdateCertificateBasedAuthConfiguration,certificateBasedAuthConfiguration.certificateBasedAuthConfiguration.DeleteCertificateBasedAuthConfiguration --co
```

Check the `certificateBasedAuthConfiguration-id` parameter in this case.

**Expected behavior**
Should just have a single parameter if it's exactly the same.

**Additional context**
Also tested directly with method `OpenApiFilterService.CreateFilteredDocument` with the same behavior.

**Comment by MaggieKimani1** [comment]
Fixed by #1841
