### ISSUE TITLE
Walker service should walk schemas recursively

### ISSUE THREAD

**Issue by danyx23** [Microsoft/OpenAPI.NET#187]
I may misunderstand what the walker is going to be used for or how it works, but it seems to me that currently the nested contents of a schema node is not visited (e.g. if it is an object (Properties field) or array (Items field)). I would like to implement some logic that would need to visit all nested schema nodes. Do you agree that this is desirable? If so I could submit a pull request to add this functionality.

**Comment by PerthCharern** [comment]
Good catch! It looks like an oversight to me. Please feel free to submit a PR.

**Comment by PerthCharern** [comment]
Also, just FYI, PR #176 contains a lot of changes to the Walker. (Given that the Schema part you mentioned is not edited in that PR, you probably won't get into any conflicts anyway.)

**Comment by danyx23** [comment]
Cool, I'll prepare a PR, will take a few days though because I am travelling. There are no unit tests yet, correct?

**Comment by PerthCharern** [comment]
There are some validator unit tests as part of #176 but they are far from complete. You can add a few more or modify the tests in #176 to also verify your changes.

cc @darrelmiller

**Comment by darrelmiller** [comment]
@danyx23 Thanks for the report.  This is fixed in PR #176

**Comment by PerthCharern** [comment]
Closing. Please feel free to send a follow-up PR or re-open if you still see any issues with the current Walker.
