### ISSUE TITLE
V2 - Why is OpenAPISchema.Type of type "object"?

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET#1874]
This provides a really poor development experience, forcing the consumer to implement complex type assertions when it shouldn't be required.

And then we do things like those: https://github.com/microsoft/OpenAPI.NET/blob/3c644511afba381b0c580f31d7282ac1e98c8d41/src/Microsoft.OpenApi/Models/OpenApiSchema.cs#L839

Which is not only going to be slow, but also problematic for people using AOT/trimming.

We [already know](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-4.2.1) that OAS 3.1 and Json Schema only support the following types:
- null
- boolean
- object
- array
- number
- string

(maybe we could add compatibility with the integer mess).

Why not instead:
- Define an enum for those types
- Make the type property, an array/list/enumerable of that enum
- When serializing as v2/v3, ensuring that we emit the right compatible information.

**Comment by darrelmiller** [comment]
I hadn't noticed this.  I agree that making the type property of type object is not going to be a great experience.  However, I'm not sure making it an array is the right choice considering how commonly devs will only want to set a single value.

Could we make a `HttpMethod` style class that does some operator overloading to handle assigning both simple values and arrays?

**Comment by baywet** [comment]
@darrelmiller with modern CSharp (12) people can simply write [collection expressions](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/collection-expressions)

```cs
schema.Type = [SchemaType.Object];
```

(assuming we go with an enum)


@calebkiage I think this is simply an abstract of the JSON schema spec at the end, the possible values here being constrained to a set we know in advance, we might as well use an enum.
