### ISSUE TITLE
v2 - loading the document requires knowing the format in advance

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET#1918]
```chsarp
new OpenApiStreamReader().Read(stream, out var diagnostic);
```

(or its async variant)

Did not require knowing the format of the document (JSON/YAML) in advance. This was handy as when building general purpose tools, it's not something that I know in advance. Parsing the file extension/url extension/response content type header _might_ help discovering it, but it's not reliable.

The equivalent method

```csharp
OpenApiDocument.LoadAsync(input, "unknown", settings)
```

Requires passing the format, which I believe is a regression in functionality. We should work to restore the same level of functionality.

Also, there are a number of places in the documentation and doc comments that still refer to the old initialization and require to be updated before GA.

https://github.com/search?q=repo%3Amicrosoft%2FOpenAPI.NET%20OpenApiStreamReader&type=code

**Comment by darrelmiller** [comment]
We could create an overload that looks like this:

> OpenApiDocument.LoadAsync(input, settings);

We first try and parse as JSON.  If the JSON fails, we can say "either you have bad JSON, or you gave me YAML, and you have not registered the YAML reader, in which case you need to take a dependency on the OpenAPI.Readers package, and register the YAML reader."

1. Try and parse as JSON
2. If it fails, check to see if YAML parser is registered
3. If it is try parsing with the YAML parser

**Comment by baywet** [comment]
Thank you for the additional information.

I don't understand why we to direct the parsing between two different parsing logics: 

> The YAML 1.2[3](https://yaml.org/spec/1.2.2/#fn:1-2-spec) specification was published in 2009. Its primary focus was making YAML a strict superset of JSON

[source](https://yaml.org/spec/1.2.2/#12-yaml-history)

We could simply feed everything to the YAML parser, couldn't we? It it happens to "only be JSON" there's extra parsing logic that would be used. It might have a performance impact since [yaml parsing ultimately converts back to JSON nodes](https://github.com/microsoft/OpenAPI.NET/blob/1338905859eaa083f89a8819227073feef8836a3/src/Microsoft.OpenApi.Readers/OpenApiYamlReader.cs#L81).

It's also worth noting [this is what the library used to do before the recent changes](https://github.com/microsoft/OpenAPI.NET/blob/9ff9789fff842e9e567dbe70a8a7966014ce8e3d/src/Microsoft.OpenApi.Readers/OpenApiTextReaderReader.cs#L39).

Then for people who really care about the performance impact, we could still leave in place the overloads that accept a format argument, bypassing this overhead. Also for any method that accepts a URI, we could look at the response content type and call the right format parser.

Thoughts?

**Comment by darrelmiller** [comment]
@baywet Parsing Graph beta as JSON takes ~450ms. Using YamlSharp it take around 5secs. I think that is a difference we should try harder to take advantage of. Especially because many consumers of the library will not tell us what format they are sending.

@maggie. Maybe we should revisit sniffing the content. We might be able to "peek" at the first few bytes without consuming the content. Also, after reviewing the full set of APIs yesterday I have a few suggested changes. One of them includes making the TextReader go away. I don't think it is useful for JSON. Scenarios. We may be able to support it just in the OpenAPIYamlReader.

**Comment by MaggieKimani1** [comment]
> [@baywet](https://github.com/baywet) Parsing Graph beta as JSON takes ~450ms. Using YamlSharp it take around 5secs. I think that is a difference we should try harder to take advantage of. Especially because many consumers of the library will not tell us what format they are sending.
> 
> [@Maggie](https://github.com/Maggie). Maybe we should revisit sniffing the content. We might be able to "peek" at the first few bytes without consuming the content. Also, after reviewing the full set of APIs yesterday I have a few suggested changes. One of them includes making the TextReader go away. I don't think it is useful for JSON. Scenarios. We may be able to support it just in the OpenAPIYamlReader.

Then I think we can continue reviewing the work I did in this PR which includes sniffing the content to detect the format https://github.com/microsoft/OpenAPI.NET/pull/1929
