### ISSUE TITLE
v2 - Remove Integer from JsonSchemaType OR rename to OpenAPISchemaType

### ISSUE THREAD

**Issue by baywet** [microsoft/OpenAPI.NET#1923]
Long story short: integer is a shorthand to type number format int64. Using a format with type integer DOES NOT have meaning.
However a lot of people (including yoko, but we've recently fixed that) used the type integer, or even the type integer with a format value.

We should either remove Integer from the possible values, since JSON schema does not have an integer value for the type keyword. Or we could rename the enum to OpenAPISchemaType, and update the reference links, to make it clear which spec this is based off.

If we decide to remove the value, we'll need to consider "gracefully" handling integer types we encounter in documents we parse.
 
A couple of scenarios we should have in our unit tests:
- what happens with the format integer and the new enum? does it get auto-converted to a number type instead? or unknown?
- what happens if a format is specified with the integer type? are we graceful and we "allow it" by keeping the information? or do we yell at the developer?

**Comment by darrelmiller** [comment]
JSON Schema does allow the value "integer" for the type field https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-validation-01#section-6.1.1 it just doesn't mean anything different than number from the perspective of validation.

**Comment by baywet** [comment]
Thanks for calling me out, I managed to confused myself with the discussions we had about this a while ago in OAS TDC. Closing
