### ISSUE TITLE
The .NET OpenAPI generator is creating duplicate models when generating from a minimal API setup in .NET 9.

### ISSUE THREAD

**Issue by jzs11** [microsoft/OpenAPI.NET#1934]
**Describe the bug**
The .NET OpenAPI generator is creating duplicate models when generating from a minimal API setup in .NET 9.

**OpenApi File To Reproduce**
Steps to reproduce:
- Create a .NET 9 minimal API project
- Generate OpenAPI specification using the built-in tools
- Observe the generated output contains duplicate entries

**Expected behavior**
The OpenAPI generator should create unique model without any duplication, properly reflecting the minimal API structure.

**Screenshots/Code Snippets**
Sample1
![Image](https://github.com/user-attachments/assets/e1826b5e-df75-4109-9223-7024ae216e5c)

Sample2
![Image](https://github.com/user-attachments/assets/7e9080b4-f514-4f0d-90d6-ae291b6c05a8)

And few others.

**Comment by captainsafia** [comment]
@jzs11 This repo is for the underlying data model used by ASP.NET Core. I'd recommend that you file this bug on the dotnet/aspnetcore repo for further investigation.

**Comment by ricardoboss** [comment]
For anyone stumbling on this issue (like I did), someone already reported this to the ASP.NET team: https://github.com/dotnet/aspnetcore/issues/58968

**Comment by akamor** [comment]
@captainsafia Given your contributions on the openapi work for dotnet9 is this something you can help raise awareness of?  As things currently stand, I dont see how the openapi work in dotnet 9 is useable at all for anything but very trivial schemas.

**Comment by captainsafia** [comment]
@akamor Yep, this is on my radar. Doing some investigation into the various reports at the moment. I'll post in the issue referenced in [this comment](https://github.com/microsoft/OpenAPI.NET/issues/1934#issuecomment-2566035633) once I have something.
