### ISSUE TITLE
Microsoft.OpenApi v2 lacks support for `const` keyword in `OpenApiSchema`

### ISSUE THREAD

**Issue by captainsafia** [microsoft/OpenAPI.NET#1940]
The new updates to `OpenApiSchema` in v2 don't provide a way for modeling the `const` keyword from JSON schema in the document.

Perhaps we should provide an optional `const` property on the `OpenApiSchema` type?

**Comment by MaggieKimani1** [comment]
You're right, thank you for pointing this out. Working on adding support for this asap
