### ISSUE TITLE
"type" in a schema can be array in V2 but must be a string in V3.

### ISSUE THREAD

**Issue by PerthCharern** [Microsoft/OpenAPI.NET#195]
We currently read type as a scalar, which means that we encounter an error when reading V2 doc with type being an array e.g. [ "string", "null" ] https://api.apis.guru/v2/specs/figshare.com/2.0.0/swagger.json

I don't see a way to maintain all the info in V2 in V3 doc. Should we arbitrarily choose the first type in the array to keep in the model?

That would mean reading a V2 doc and then serializing the DOM would not yield the original document.

**Comment by darrelmiller** [comment]
@PerthCharern That's not a valid V2 document because `null` is not a supported type in OpenAPI V2 or V3.  I didn't realize that V2 actually allowed type to be an Array.  If we want to support this scenario then we would need to construct a `anyOf` or `oneOf` to support the variance.
We could be really nice and convert the array including null to set the new 'nullable' property to true.  Then we would have to figure out how to export it to V2.

**Comment by PerthCharern** [comment]
- Could you point me to the restriction on the type string in the spec? I thought type string only follows the JSON schema spec, in which case "null" is a valid type.

- The nullable one is a good idea.

- We can use anyOf to translate a schema with multiple types to a schema with anyOf array pointing to multiple schemas. One interesting problem we will have is the reverse direction (i.e. writing to V2 document). We are not handling this correctly today - we currently just ignore the anyOf array in its entirety because it's not supported in V2. We should probably do a best-effort processing to combine the schemas in the anyOf into one with multiple types if possible.

**Comment by darrelmiller** [comment]
@PerthCharern It's not really clear in the spec.  However, I talked to Ron Ratovsky who was the editor for the 1.2 and 2.0 spec and as far as he is concerned, type as an array has never been supported. The Swagger tooling doesn't support it, so I don't think we need to.

**Comment by darrelmiller** [comment]
And regarding merging to anyOf when downcasting, I agree.  We should try and do that.

**Comment by PerthCharern** [comment]
I'll create a new issue for the merging of anyOf and close this one.
