### ISSUE TITLE
[API Review] Rename & evaluate properties in ReadResult

### ISSUE THREAD

**Issue by RachitMalik12** [microsoft/OpenAPI.NET#1963]
Requester: @captainsafia 

1. Evaluate rename of properties in ReadResult to avoid redundancy in naming:  
Change `OpenAPIDocument -> Document` and `OpenAPIDiagnostic -> Error`
2. Evaluate if the properties in ReadResult need setters. 
3. OpenAPIDocument should be nullable.

**Comment by MaggieKimani1** [comment]
I think we can rename `OpenApiDiagnostic` to `Diagnostic` since it already contains an errors object within, in addition to a `SpecificationVersion` object. It would make more sense to have `Diagnostic.Errors` and `Diagnostic.SpecificationVersion` instead of  `Error.Errors`

**Comment by RachitMalik12** [comment]
@MaggieKimani1 I am fine with that.
