### ISSUE TITLE
[API review] Evaluate format default value in Load methods

### ISSUE THREAD

**Issue by RachitMalik12** [microsoft/OpenAPI.NET#1964]
Where the loading methods are used without a format property, we will attempt to parse the document using the default JSON reader. If that fails and the Yaml reader is registered, then we will attempt to read as YAML. 

Evaluate if the following methods should have default format value of "json" or the best way to manage the default format value: 
``` 
public class OpenApiDocument {
    public static async Task<ReadResult> LoadAsync(string url, OpenApiReaderSettings settings = null) {}
    public static async Task<ReadResult> LoadAsync(Stream stream, string? format = null, OpenApiReaderSettings? settings = null) {}
    public static ReadResult Load(MemoryStream stream, string? format = null, OpenApiReaderSettings? settings = null) {}
    public static ReadResult Parse(string input,string? format = null,OpenApiReaderSettings? settings = null) {}
}
```

**Comment by MaggieKimani1** [comment]
Linking [this issue](https://github.com/microsoft/OpenAPI.NET/issues/1918) as a reference particularly the ongoing discussion on whether to use JSON as a default format or opt to "sniff" the first bytes of a stream to detect its format.
