### ISSUE TITLE
Different rules for V2 and V3

### ISSUE THREAD

**Issue by PerthCharern** [Microsoft/OpenAPI.NET#198]
@darrelmiller 

There are places where the V2 and V3 specs may be slightly different. For example, V2 doesn't enforce XML.namespace to be absolute URI.

It seems to me that we may need different rulesets per version. Most default rules will be shared, but certain rules only belong to certain versions of the spec.

**Comment by darrelmiller** [comment]
@PerthCharern This comes back to parsing errors verses validation.  Once we are loaded into the DOM we are no longer V2, we are V.Current.  If the we can't make it V3 compliant then I think we have to reject when parsing, or flag it with our validation errors.  Anyway, I'm pretty sure a namespace URI can't be relative anyway.  At least I can't say I've ever seen a relative namespace.

**Comment by PerthCharern** [comment]
Same effect can be achieved by adding or removing rules from the default set when validating, so we'll close this for now.

**Comment by PerthCharern** [comment]
We are seeing this issue in #254. Even though the DOM is universal, there are certain restrictions on some strings in V3 that were not the case in V2. 

Customers can remove the rule themselves, but then that seems very inconvenient. Should we provide rulesets based on Versions?

**Comment by PerthCharern** [comment]
We decided not to do this. Whatever is in the DOM must be "V3-valid".
