### ISSUE TITLE
Wrong proprties when parsing formData parameters

### ISSUE THREAD

**Issue by talamram** [Microsoft/OpenAPI.NET#204]
I get wrong proprties in the schema object when I try to parse actions with "formData" parameters (V2)

"post": {
				"summary": "Updates",
				"description": "",
				"operationId": "update",
				"consumes": ["application/x-www-form-urlencoded"],
				"produces": ["application/xml",
				"application/json"],
				"parameters": [{
					"name": "Id",
					"in": "path",
					"description": "ID",
					"required": true,
					"type": "integer",
					"format": "int64"
				},
				{
					"name": "name",
					"in": "formData",
					"description": "Updated name",
					"required": false,
					"type": "string"
				},
				{
					"name": "status",
					"in": "formData",
					"description": "Updated status",
					"required": false,
					"type": "string"
				}],
				"responses": {
					"405": {
						"description": "Invalid input"
					}
				}
			}

I should get 2 parameters (name and status) but instead I get properties of other action.

**Comment by darrelmiller** [comment]
Thanks for the report. We will investigate.

**Comment by darrelmiller** [comment]
Fixed.
