### ISSUE TITLE
RequestBody.Content is not updated properly

### ISSUE THREAD

**Issue by talamram** [Microsoft/OpenAPI.NET#212]
in V2

When I don't have a consumes property, I get the content of the previous action.
for example:

/pet/{petId}/upload: {
	post: {
		summary: "uploads an image",
		description: "",
		operationId: "uploadFile",
		consumes: ["multipart/form-data"],
		produces: ["application/json"],
		parameters: [{
		{
			name: "file",
			in: "formData",
			description: "file to upload",
			required: false,
			type: "file"
		}]
	}
},
/store/inventory: {
	get: {
		tags: ["store"],
		summary: "Returns by status",
		description: "Returns a map of status codes to quantities",
		operationId: "getInventory",
		produces: ["application/json"],
		parameters: []
	}
}

The RequestBody.Content that I get for the second action is "multipart/form-data"

**Comment by darrelmiller** [comment]
Ah.  Thanks.  I was able to repro this.  I will fix it.

**Comment by PerthCharern** [comment]
@darrelmiller @talamram PR #197 should solve this issue. I ran the example above and `consumes` from the first operation is not used in the second operation now.

There's a different issue I see from the example above: Without `responses`, there's no place to save the `produces` array, so the example above as is will yield a missing `produces` array. However, `responses` property is required by the spec, so in usual cases, this should not be a problem. We will need to write a rule for OpenApiOperation to make sure Responses is present.

**Comment by darrelmiller** [comment]
We have a rule for ensuring there is at least one response.
