### ISSUE TITLE
Rule in OpenApiResponsesRules is too restrictive.

### ISSUE THREAD

**Issue by PerthCharern** [Microsoft/OpenAPI.NET#214]
Spec (both V2 and V3):

The Responses Object MUST contain at least one response code, and it SHOULD be the response for a successful operation call.

Our rule:

Responses must contain success response

What I think we should do:

Just check that there is one response. We don't have the capability for the SHOULD type of rule right now.

**Comment by darrelmiller** [comment]
And there we have justification for creating the notion of a Warning when doing validation :-)
