### ISSUE TITLE
Path paramters reference

### ISSUE THREAD

**Issue by talamram** [Microsoft/OpenAPI.NET#216]
When path paramter value is referenced to to parameter component, the values inside the OpeanApiParamter (name, in, description, etc) are all null.

fot example:

{
  "openapi": "3.0.0",
  "servers": [
    {
      "url": "https://www....com/v3"
    }
  ],
  "info": {
    "title": "title",
    "description": "description",
    "version": "v3"
  },
  "paths": {
	"/activities": { 
		"get" : {...},
		"post: {...},
		"parameters": [
        {
          "$ref": "#/components/parameters/alt"
        }
      ]
	}
   }
  "components": {
	"parameters": {
      "alt": {
        "name": "alt",
        "in": "query",
        "description": "desc",
        "schema": {
          "type": "string",
          "enum": [
            "json"
          ],
          "default": "json"
        }
      }
	}
	}
}

alt paramter values are all null.

**Comment by darrelmiller** [comment]
Looks like parameters at the path level are not being resolved by the ReferenceResolver.  It is probably missing in the walker.  I will fix that.  Thanks!
