### ISSUE TITLE
String reader diagnostic error when description is empty for a response

### ISSUE THREAD

**Issue by Shwetap05** [Microsoft/OpenAPI.NET#223]
OpenApiStringReader.Read throw below diagnostic error when description is empty for a response:
"The field 'description' in 'response' object is REQUIRED."

Per Specification description is required, does it mean it should not be empty too? b/c the document loads fine in swagger editor without any schema failures.

Sample Json:

{
  "openapi": "3.0.1",
  "info": {
    "title": "test",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://test.net"
    }
  ],
  "paths": {
    "/v1/applicationSettings": {
      "get": {
        "tags": [
          "ApplicationSettings"
        ],
        "summary": "Gets the settings of this application.",
        "operationId": "getV1ApplicationSettings",
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
  }
}

**Comment by darrelmiller** [comment]
If empty was allowed the requirement for it to be required would be pointless.

**Comment by darrelmiller** [comment]
Currently the spec is interpreted as empty satisfies the requirement.  This is a topic for next week's meeting to decide if this needs to change for properties like `name`.  https://github.com/OAI/OpenAPI-Specification/issues/1516

**Comment by scott-lin** [comment]
@darrelmiller, curious what the reasoning was to allow empty string for these fields when they say "Required" in the spec. As your original comment suggested, it's seemingly "pointless".

If this stands, the documentation is arguably ambiguous ([Response description for example](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#responseObject)) in my opinion.

**Comment by darrelmiller** [comment]
@scott-lin  I have had a few conversations about this with the OpenAPI working group.   The spec isn't clear about what is considered necessary to satisfy the required condition.  However, considering JSON Schema considers the mere presence of a property as satisfying the required constraint, it can be safely assumed that some folks are relying on the fact that an empty description meets the condition.

This makes it impossible to add wording that prevents it, at least not in a patch version.  We are considering introducing a distinction between strings that can be allowed empty and those that cannot.  Things like descriptions can be empty without causing any real harm.  Forcing a non-empty value will just encourage people to put in dummy values to avoid the validation.  However, for things like parameter names, and other keys, we may introduce a non-empty requirement in the 3.1 release.  We can add more rules into our library at that point.  

In the meanwhile if users of this library want to keep the non-empty description constraint, they can always add a custom rule.
