### ISSUE TITLE
OpenApiTags in OpenApiOperation can't write the extensions

### ISSUE THREAD

**Issue by xuzhg** [Microsoft/OpenAPI.NET#240]
We know Operation has a list of <Tag>:

https://github.com/Microsoft/OpenAPI.NET/blob/master/src/Microsoft.OpenApi/Models/OpenApiOperation.cs#L27

However,  If I create a <OpenApiTag> with extensions, the extensions can’t write out. Does it make sense?

For example:

```C#
OpenApiOperation operation = new OpenApiOperation
{
    Tags = new List<OpenApiTag>
    {
       new OpenApiTag
      {
          Name = "tagName1",
           Description = "tagDescription1",
           Extensions = new Dictionary<string, IOpenApiExtension>
           {
              {"x-internal-id", new OpenApiInteger(42)}
           }
  ….                
```
The above two elements (Description & Extensions) can’t write out into the open api document.
Is it by design?

Thanks!

**Comment by darrelmiller** [comment]
The extensions will write out at the root "tags" property, but not at the operation level.

**Comment by xuzhg** [comment]
thanks
