### ISSUE TITLE
Type dateTime not supported

### ISSUE THREAD

**Issue by TheEres** [Microsoft/OpenAPI.NET#243]
Hi,

I found a problem with dateTime type.

Steps:

* Try to validate/serialize an OpenApi definition containing `dateTime` schema (e.g. [Docker Engine API](https://docs.docker.com/engine/api/v1.37/swagger.yaml)).

Result:
* `OpenApiWriterException: The type 'System.DateTimeOffset' is not supported in Open API document.
`

Proposed solution:
* Add support to DateTimeOffset, ISO 8601 style : `Writer.Write(value.ToString(@"O"))`.

**Comment by darrelmiller** [comment]
Thanks for the feedback.  I will investigate.

**Comment by darrelmiller** [comment]
I was able to reproduce and resolve.  I need to add some tests around this, but I think we should be able to include this our 1.0 release.
