### ISSUE TITLE
Deafault values

### ISSUE THREAD

**Issue by talamram** [Microsoft/OpenAPI.NET#255]
Hi,
Not sure what suppsoe to be the correct behavior but when getting a default value that is not a string, the object I get for schema.Default is OpenApiString.

For example 
"grade" : {
          "type" : "integer",
          "format" : "int64",
          "minimum" : 0,
          "maximum" : 100,
          "default" : 88
        }

when getting the schema for this property, the schema.Default is OpenApiString object ("88").
I believe is should be OpenApiInteger

**Comment by darrelmiller** [comment]
Could you verify this against the latest release of the package?  I'm not able to repro the issue in my test.  Thanks.

**Comment by talamram** [comment]
Yes I verified it on 1.0.0

example:
"/getStudentGrades/{studentId}" : {
      "get" : {
        "tags" : [ "grade" ],
        "summary" : "get student grades",
        "operationId" : "getStudentGrades",
        "produces" : [ "application/json" ],
        "parameters" : [ {
          "name" : "studentId",
          "in" : "path",
          "description" : "Student id",
          "required" : true,
          "type" : "integer",
          "default" : 1010,
          "format" : "int64"
        } ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "type" : "array",
              "items" : {
                "$ref" : "#/definitions/Grade"
              }
            }
          },
          "400" : {
            "description" : "Unsuccessful operation"
          },
          "401" : {
            "description" : "Login required"
          }
        }
      }
    }

when I try to cast to integer I get:
Cannot cast 'schema.Default' (which has an actual type of 'Microsoft.OpenApi.Any.OpenApiString') to 'Microsoft.OpenApi.Any.OpenApiInteger'

**Comment by darrelmiller** [comment]
I took your example and ran it through the Workbench tool and it is parsing as an OpenApiInteger for me.

![image](https://user-images.githubusercontent.com/447694/40442391-5c8ee6ae-5e78-11e8-8dc2-bf34f709b6b8.png)

**Comment by talamram** [comment]
Yes you are right, The swagger editor export these elements as strings so the problem was at this level.

Thanks
