### ISSUE TITLE
Process for managing patch releases vs minor releases

### ISSUE THREAD

**Issue by darrelmiller** [Microsoft/OpenAPI.NET#260]
Up to this point we have used master as the primary branch that all releases are derived from.  Now that we have a 1.0.0 release we have the potential for two distinct release branches.

We have bug fixes that should go into a 1.0.1 release and we have 1.1 work that should be released as a 1.1.0-preview nuget.

My proposal is that we continue using master for doing gated check-in's of the latest preview.  When there are bug fixes to do on an existing release, we should create a branch based on the release tag and merge patches into that branch.  We should then do a patch release from that branch.

Does that make sense?  /cc @PerthCharern @xuzhg @Shwetap05 

Should we do gated check-ins to the release-v1.0.x branch? I don't know how to set that up.

**Comment by Shwetap05** [comment]
Darrel,



I see one problem with above suggested approach, If we create branches for
Patches e.g. 1.0.1, 1.0.2 etc then for each of those branches we will need
to setup CI in our internal VSO account to sign assemblies and publish
nuget packages, and if anyone outside of Microsoft wants to contribute then
we will have to spend cycles to do it for them right?



So I propose, we leave Master for patches work on 1.0.0 and create a new
child branch from master for preview release, and as patches are released
to master, we will merge master into this preview branch And when preview
branch is ready for release it can be merged to Master. That way we will
only need to maintain CI for Master and this new Preview branch thoughts?



Thanks,

~Shweta

**Comment by darrelmiller** [comment]
That works for me.
