### ISSUE TITLE
Cannot resolve relative URLs when reading documents if server URL is relative or absent

### ISSUE THREAD

**Issue by darrelmiller** [Microsoft/OpenAPI.NET#262]
Proposed solution: Add baseUrl property to reader settings.

**Comment by PerthCharern** [comment]
Do we have an example document for this?

**Comment by darrelmiller** [comment]
Simplest example would be something like:

```
openapi: 3.0.0
servers:
  url: /api
paths:
  '/': 
    get:
      responses:
        '200': 
          description: ok
          content:
            application/json:
              schema:
                $ref: "schemas/rootresponse.json"
```

**Comment by PerthCharern** [comment]
- I understand the related problem you mentioned. Wouldn't that baseURL need to be input separately (as an argument to Read)?

- I am still unclear what the original problem means. I see that we read in the Server as a simple string, but I forgot where we resolve such URL. I guess if I run the doc above in the Workbench, I should see the error.

**Comment by darrelmiller** [comment]
BaseUrl in reader settings now resolves this.
