### ISSUE TITLE
Specifying a Security object on an Operation serializes as an empty object

### ISSUE THREAD

**Issue by ChristineBoersen** [Microsoft/OpenAPI.NET#283]
When attempting to Consume a SecuritySchema within an Operation object, upon serialization, the output shows security: [{}] . 

Shouldn't it show security: [ "myToken": [] ] instead so that the operation requires the SecuritySchema requested?

The documentation doesn't provide any examples using SecuritySchema or Security or I would reference them.

e.g.
```

OpenApiDocument doc = new OpenApiDocument
            {
                Info = new OpenApiInfo
                {
                    Version = "1.0.0",
                    Title = "MyTitle"
                },
                Servers = new List<OpenApiServer> {
                    new OpenApiServer {
                        Url = "https://mySite.com/api/v1"
                    }
                },
                Paths = new OpenApiPaths { },
                Components = new OpenApiComponents
                {
                    Schemas = new Dictionary<string, OpenApiSchema>(),
                    SecuritySchemes = new Dictionary<string, OpenApiSecurityScheme> {
                        {
                            "myToken",
                            new OpenApiSecurityScheme {
                                In = ParameterLocation.Header,
                                Type = SecuritySchemeType.ApiKey,
                                Name = "myToken"
                            }
                        }
                    }
                }
            };


            OpenApiOperation operation = new OpenApiOperation
            {
                OperationId = "MyUniqueMethodName",
                Parameters = new List<OpenApiParameter>(),
                Responses = new OpenApiResponses(),
                Security = new List<OpenApiSecurityRequirement> {
                      new OpenApiSecurityRequirement{
                          {  doc.Components.SecuritySchemes["myToken"], new List<string>() }
                      }
                    }
            };

            OpenApiPathItem pathItem = new OpenApiPathItem
            {
                Operations = new Dictionary<Microsoft.OpenApi.Models.OperationType, OpenApiOperation>()
            };
            pathItem.AddOperation(Microsoft.OpenApi.Models.OperationType.Get, operation);
            doc.Paths.Add("/MyUniquePath", pathItem);

            string jsonOutput = doc.Serialize(OpenApiSpecVersion.OpenApi3_0, OpenApiFormat.Json);

```

And the output from this is 

```
{
  "openapi": "3.0.1",
  "info": {
    "title": "MyTitle",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "https://mySite.com/api/v1"
    }
  ],
  "paths": {
    "/MyUniquePath": {
      "get": {
        "operationId": "MyUniqueMethodName",
        "responses": { },
        "security": [
          { }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "myToken": {
        "type": "apiKey",
        "name": "myToken",
        "in": "header"
      }
    }
  }
}
```

**Comment by darrelmiller** [comment]
Hey @ChristineBoersen.  First off, thank for bringing this up.   It is further evidence that I really need to get some docs written for this project.  Secondly you have hit upon what was a fairly unusual design choice that I made when implementing SecurityRequirements.  I decided that for both SecurityRequirements and Tags that we were going to internally use the same reference handling code that we use for $refs.  Although the OpenAPI spec doesn't consider them $refs they behave in a very similar way.

The quick answer to your question is to be able to use the same SecurityScheme object in both the Components section and as a key in the SecurityRequirements dictionary, you need to explicitly tell us that it is a referenced object.  Therefore, when setting up the SecurityScheme, you need to do this:

```C#
 SecuritySchemes = new Dictionary<string, OpenApiSecurityScheme> {
                        {
                            "myToken",
                            new OpenApiSecurityScheme {
                                In = ParameterLocation.Header,
                                Type = SecuritySchemeType.ApiKey,
                                Name = "myToken",
                                Reference = new OpenApiReference()
                                {
                                    Id = "myToken",
                                    Type = ReferenceType.SecurityScheme
                                },
                                UnresolvedReference = false
                            }
                        }
                    }
```

This probably seems pretty strange, but I'm going to try and justify why this is.  When parsing a text based specification, the SecurityRequirements Key is simply a string value.  In theory we could have parsed it as just a string and then used an explicit lookup into SecuritySchemas to resolve it.  However, we decided it to treat it the same way we do references, so when parsing, it is created like this:

```c#
new OpenApiSecurityRequirement{
                          {  new SecurityScheme { 
                                 Reference = new OpenApiReference()
                                {
                                    Id = "myToken",
                                    Type = ReferenceType.SecurityScheme
                                },
                                UnresolvedReference = true   }, new List<string>() }
                      }
```
i.e. It is a currently unresolved reference to a security scheme.  Once the parsing is complete and if the OpenApiReaderSettings has been configured to resolve references, we then traverse the OpenAPI Document looking for unresolved references.  At that point we replace the "stub" SecurityScheme object that just has the Reference with the real one that is held in the Components.SecuritySchemes dictionary.  

Now, comes the question, of why do we need the Reference property to be populated in the complete SecurityScheme object?  When it comes time to serializing out the OpenAPI document, we would prefer $refs (or in this case SecurityRequirement keys) just be serialized out in their reference form, and not the entire object.  The only way we know to do that is by knowing that an object is actually a reference to a component.  That's what the Reference object instance tells us.

We could have special cased Tags and SecurityRequirements, and perhaps that might have been a simpler solution.  I'm not sure.  I do realize we need a better way of creating references to components via the object model.  Having to remember to set the properties that you were missing is going to trip lots of people up.  

Hopefully this addresses how to fix your immediate issue, and perhaps clarifies why it was done this way.  If you have feedback, I'd love to hear it.

**Comment by ChristineBoersen** [comment]
Actually it makes perfect sense knowing how JsonSchema works, thanks for the example! :)

One minor typo in your example above, "SecurityScheme" should be "OpenApiSecurityScheme" 

```C#

Security = new List<OpenApiSecurityRequirement> {
  new OpenApiSecurityRequirement{
      {
          new OpenApiSecurityScheme {
            Reference = new OpenApiReference {
                Id = "myToken",
                Type = ReferenceType.SecurityScheme
            },
            UnresolvedReference  = true
          }, new List<string>() }
  }
}

```
