### ISSUE TITLE
How to convert a c# object into OpenApiAny

### ISSUE THREAD

**Issue by Shwetap05** [Microsoft/OpenAPI.NET#286]
OpenAPI.NET.CSharpAnnotations builds the OpenApiDocument incrementally and to enable adding support for examples for the library, need a way to convert a C# object into OpenApiAny to populate OpenApiExample.

Or a way to convert a serialized json string to OpenApiExample object.

**Comment by darrelmiller** [comment]
1.1.0-preview supports reader.ReadFragment<IOpenApiAny>()

**Comment by PerthCharern** [comment]
Does it support reading a custom JSON into OpenApiAny though? I will double check again today.

The C# Reader does not have the whole OpenApiExample object to read from. It only gets the custom JSON object from the user and needs to populate the example field with that object. Currently the field can’t be populated with a C# `object` - only OpenApiAny is allowed.

Sent from my mobile device

On Jun 21, 2018, at 07:05, Darrel <notifications@github.com<mailto:notifications@github.com>> wrote:


1.1.0-preview supports reader.ReadFragment()

**Comment by Shwetap05** [comment]
@PerthCharern i have tried reading a JSON string into OpenApiAny and it works then its easy to create an OpenApiExample like below

var example = new OpenApiStringReader().ReadFragment<IOpenApiAny>( "{\"samplePropertyBool\":true,\"samplePropertyEnum\":\"SampleEnumValue2\"}", OpenApiSpecVersion.OpenApi3_0, out diagnosticV3 );

openApiDocV3.Components.Examples.Add( "test", new OpenApiExample() { Value = example } );

**Comment by PerthCharern** [comment]
Sounds good then. I tried tracking through the code in the preview, and I think the ReadFragment is doing what we expect it to do. (Calling ParseFragment, which then calls LoadAny for IOpenApiAny type, which then parses the JSON string into the correct type of IOpenApiAny).
