### ISSUE TITLE
$ref is not a valid property path item

### ISSUE THREAD

**Issue by talamram** [microsoft/OpenAPI.NET#288]
Hi,
I tried 1.1.0-preview.3 reader version with this sample:

```yaml
components:
  securitySchemes:
    Token:
      description: This API uses OAuth 2 
      flows:
        implicit:
          authorizationUrl: https://.......
          scopes: []
          tokenUrl: https://.......
      type: oauth2
info:
  title: API
  version: 0.9.0
openapi: 3.0.0
paths:
  /float:
    $ref: paths/float.yaml#/collection
  /float/{id}:
    $ref: paths/float.yaml#/individual
  /float/{id}/tags:
    $ref: paths/tags.yaml#/network_collection
security:
- Token: []
servers:
- url: /v1
```

And I get errors like **$ref is not a valid property at #/paths//float**
I checked the specification and it should be permitted.

Thanks

**Comment by talamram** [comment]
Hi,
First, Thanks :)
Second, do you have any timeline for supporting referencing external files?

Thanks

**Comment by darrelmiller** [comment]
@talamram I wish I did.  I would love to get it out within the next few weeks, but it just depends on how much free time I get.  And I want to get the Swashbuckle support for V3 finished first.

**Comment by fabianmeyer** [comment]
Hi, any update on this issue?

**Comment by darrelmiller** [comment]
@fabianmeyer Sadly I have no good news.  The inlining of references took priority over finishing OpenAPIWorkspace and getting support for external references.  Hopefully, that can be next up.
