### ISSUE TITLE
Add a reader for YamlDocument object

### ISSUE THREAD

**Issue by talamram** [microsoft/OpenAPI.NET#298]
Hi,

I would like to add a new reader (except OpenApiStreamReader and OpenApiStringReader) that called OpenApiDocumentReader, and gives the ability to parse YamlDocument SharpYaml object directly.
The class signature will be:

public class OpenApiDocumentReader : IOpenApiReader<YamlDocument, OpenApiDiagnostic>

The OpenApiStreamReader will use it after it generates YamlDocument.
This class is useful for developers who want to generate the YamlDocument object independently (with SharpYaml package) and want to be able to parse it with OpenApi parsers.

Tanks, Tal.

**Comment by darrelmiller** [comment]
@talamram That sounds great.  If you could create a PR against the vnext branch we should be able to get that into our 1.1 release.

**Comment by darrelmiller** [comment]
Unfortunately, we don't want to expose our dependency on YamlDocument.
