### ISSUE TITLE
V3 multipart `encoding` property type  for content-type isn't supported

### ISSUE THREAD

**Issue by daniel-white** [Microsoft/OpenAPI.NET#308]
Given this spec:

```
openapi: "3.0.0"
info:
  title: Test
  version: "1.0"
paths:
  /convert:
    post:
      operationId: doWork
      description: Work work work.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              properties:
                options:
                  description: The configuration data.
                  type: object
                  properties:
                    foo:
                      type: string
                      description: A foo.
                  required:
                    - foo
                message:
                  description: Big text file
                  type: string
                  format: binary
              required:
                - options
                - message
            encoding:
              message:
                contentType: text/plain
      responses:
        201:
          description: Request worked.
   ```
and given the documentation: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#special-considerations-for-multipart-content

I would not expect any errors or lack of the `contentType` for `message` when reading the YAML. I do get a diagnostic error: `"encoding is not a valid property at #/paths//convert/post/requestBody/content"`

**Comment by daniel-white** [comment]
Diving into the code a bit, `Microsoft.OpenApi.Readers\V3\OpenApiMediaTypeDeserializer.cs` / `_mediaTypeFixedFields` has a comment like a todo for encodings, but its left unimplemented.

**Comment by daniel-white** [comment]
Well it looks like the rest of the plumbing is there; this is what is missing in the `_mediaTypeFixedFields`

```
{
    "encoding", (o, n) =>
    {
        o.Encoding = n.CreateMap(LoadEncoding);
    }
},
```

**Comment by PerthCharern** [comment]
Based on the PR and the conversation above, I believe this is resolved. Please reopen if that's not the case.
