### ISSUE TITLE
Nested properties inside a JSON API description malfunctioning 

### ISSUE THREAD

**Issue by fhinojoza09** [Microsoft/OpenAPI.NET#315]
Hi, I'm an intern working on a deserialization/translation tool for API descriptions and I've been using the OpenAPI Stream Reader, but I ran into an issue when the reader came across a nested property, the reader skips the nested properties entirely while registering the contents as null. I've attached a section of the file it contains the part where the reader malfunctions. The specific properties are under components/schemas/estimated_diameter/properties. Thank you ! 
![estimated_diameter](https://user-images.githubusercontent.com/20980393/44059505-7ad83466-9f06-11e8-8475-394a279f55dd.PNG)

**Comment by PerthCharern** [comment]
Thanks for reporting @fhinojoza09 and sorry for the delay in our response. I'll investigate this tomorrow and get back to you.

**Comment by PerthCharern** [comment]
@fhinojoza09 The document is not compliant with the OpenAPI 3.0 spec. The values in the `properties` map must also be a Schema object.

For example, here's the way to document a nested property in OpenAPI 3.0.



```
{
  "openapi": "3.0.1",
  "info": {
    "title": "Simple Document",
    "version": "0.9.1"
  },
  "paths": { },
  "components": {
    "schemas": {
      "estimated_diameter": {
        "type": "object",
        "properties": {
          "kilometers": {
            "type": "object",
            "properties": {
              "estimated_diameter_min": {
                "type": "number",
                "format": "float"
              },
              "estimated_diameter_max": {
                "type": "number",
                "format": "float"
              }
            }
          }
        }
      }
    }
  }
}
```

The above represents

```
- estimated_diameter
  - kilometers
    - estimated_diameter_min
    - estimated_diameter_max
```

**Comment by PerthCharern** [comment]
I'll close this issue. If you have more questions/concerns, feel free to reopen.
