### ISSUE TITLE
Exception thrown when security requirement key doesn't match a security scheme definition

### ISSUE THREAD

**Issue by PerthCharern** [Microsoft/OpenAPI.NET#330]
Exception thrown when security requirement key doesn't match a security scheme definition.

We should parse the document normally, but yield a validation error instead of throwing.

**Comment by senthilkumarmohan** [comment]
Hi, I have checked in fix for this issue pr#339.

**Comment by PerthCharern** [comment]
@senthilkumarmohan Thanks for the PR. I'll take a look.
