### ISSUE TITLE
Report an error when the discriminator property is not defined in 'oneOf' the schema types?

### ISSUE THREAD

**Issue by senthilkumarmohan** [Microsoft/OpenAPI.NET#344]
Should we report an error when the discriminator property is not defined in 'oneOf' the schema types? in the below example, pet2 doesn't have the expected discriminator property.

responses:
        '200':
          description: pet response
          content:
            application/json:
                schema:
                  oneOf:
                    - "$ref": '#/components/schemas/pet1'
                    - "$ref": '#/components/schemas/pet2'
                  discriminator:
                    propertyName: petType
components:
    schemas:
        pet1:
            type: object
            required:
            - id
            properties:
              id:
                type: integer
                format: int64
              petType:
                type: string
        pet2:
            type: object
            required:
            - id
            properties:
              id:
                type: integer
                format: int64

**Comment by PerthCharern** [comment]
From the spec, we might be able to be even stricter:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#composition-and-inheritance-polymorphism

"... As such, the discriminator field MUST be a required field. There are are two ways to define the value of a discriminator for an inheriting instance."

Would you like to send out a PR? :)

**Comment by senthilkumarmohan** [comment]
Thanks for your response. I am working on it - will submit a PR soon.

**Comment by senthilkumarmohan** [comment]
@PerthCharern, i have submitted a PR for this. Please can you review?
