### ISSUE TITLE
OpenApiStringReader().ReadFragment throwing exception when converting a string to IOpenApiAny

### ISSUE THREAD

**Issue by Shwetap05** [Microsoft/OpenAPI.NET#345]
One of the consumer of https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations is specifying below string for example value of a multipart/form-data

@"---------------------------acebdf13572468
ParamaterOne: 'Some App-Specific Data'
ParameterTwo: { ItemOne: 'one', ItemTwo: 'two' }
ParameterThree: ['1','2','3']
Content-Disposition: 'form-data'; name='fieldNameHere'; filename='AnnualReport.docx'
Content-Type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
<@includeC:\Users\Anderssen\Desktop\AnnualReport.docx@>
---------------------------acebdf13572468"

And the library uses below code to Parse the example value
```c#

new OpenApiStringReader().ReadFragment<IOpenApiAny>(
                        exampleString,
                        OpenApiSpecVersion.OpenApi3_0,
                        out OpenApiDiagnostic openApiDiagnostic);
```
which is throwing diagnostic error {(Lin: 1, Col: 12, Chr: 55) - (Lin: 1, Col: 12, Chr: 55): Mapping values are not allowed in this context. [#line=1]}

so i am not sure if the example value is the correct one for a form data request type?

**Comment by Shwetap05** [comment]
If i just use below value then it works, but again i am not familiar with form data so not sure if that is the correct way to provide an example

@"
ParamaterOne: 'Some App-Specific Data'
ParameterTwo: { ItemOne: 'one', ItemTwo: 'two' }
ParameterThree: ['1','2','3']"

**Comment by PerthCharern** [comment]
The string given to OpenApi.NET reader must be JSON/YAML compliant. To preserve the newlines in the original string, we'll need to first escape them.

Basically, we will need the below input in `exampleString`. Note that the quotes ARE a part of the string. It is needed for ReadFragment to understand that this is a string.

"---------------------------acebdf13572468\r\nParamaterOne: 'Some App-Specific Data'\r\nParameterTwo: { ItemOne: 'one', ItemTwo: 'two' }\r\nParameterThree: ['1','2','3']\r\nContent-Disposition: 'form-data'; name='fieldNameHere'; filename='AnnualReport.docx'\r\nContent-Type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'\r\n<@INcludeC:\\Users\\Anderssen\\Desktop\\AnnualReport.docx@>\r\n---------------------------acebdf13572468"

**Comment by PerthCharern** [comment]
Synced with @Shwetap05. The changes will have to be made on the https://github.com/Microsoft/OpenAPI.NET.CSharpAnnotations side. I'll close this.
