### ISSUE TITLE
Parameters are not parsed, only yielding empty seqs

### ISSUE THREAD

**Issue by kMutagene** [Microsoft/OpenAPI.NET#347]
I am trying to parse the [petshop example yaml](https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore.yaml) using the OpenApiStringReader in F#. There are no exceptions thrown, but aside from the actual path string, the resulting object is completely empty:

![image](https://user-images.githubusercontent.com/21338071/48545545-69bd9180-e8c6-11e8-96f5-018de308f120.png)

Am I missing something obvious or is this a bug? I used the provided functions like this:
![image](https://user-images.githubusercontent.com/21338071/48545727-e3557f80-e8c6-11e8-94bd-a298e6bdc3f1.png)

**Comment by darrelmiller** [comment]
I think what you are seeing is as intended.  For the first path item, the  operations dictionary has two Operation objects in it.  The description string will be in those, as will the list of parameters and responses..

**Comment by kMutagene** [comment]
I knew i was missing something, thank you for the quick answer!
