### ISSUE TITLE
Reading and writing a document with sample date-time fields produces invalid document

### ISSUE THREAD

**Issue by korygin** [Microsoft/OpenAPI.NET#348]
OpenAPI.NET 
Version 1.1.0.0

**Repro:**

1. Create an OpenAPI document with a sample response message that has date-time fields, i.e.:
"responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "object"
            },
            "examples": {
              "application/json": [
                {
                  "lastCalculated": **"2018-11-16T17:52:05.7194097-06:00"**,
                  "lastGenerated": **"2018-11-16T17:52:05.7194097-06:00"**,
                  "lastGeneratedFile": "20170331091550_1.RTS",
                  "employeeCount": 100,
                  "calculationStatus": null,
                  "companyInfoId": 0,
                  "rtsImportStatus": "Open",
                  "id": 1,
                  "year": 2016,
                  "quarter": 4,
                  "companyId": "123456",
                  "companyName": "Northwind LLC"
                }
              ]
            }
          }
        }

2. Run the document through OpenAPI.NET (read/write)
3. Notice that write will produce an invalid JSON document (double-quotes are missing around date-time fields)
"responses": {
          "200": {
            "description": "",
            "examples": {
              "application/json": [
                {
                  "lastCalculated": **2018-11-16T17:52:05.7194097-06:00**,
                  "lastGenerated": **2018-11-16T17:52:05.7194097-06:00**,
                  "lastGeneratedFile": "20170331091550_1.RTS",
                  "employeeCount": 100,
                  "calculationStatus": null,
                  "companyInfoId": 0,
                  "rtsImportStatus": "Open",
                  "id": 1,
                  "year": 2016,
                  "quarter": 4,
                  "companyId": "123456",
                  "companyName": "Northwind LLC"
                }
              ]
            }
          }
        }

**Comment by PerthCharern** [comment]
Could you try v1.1.1? It should be fixed there.

https://www.nuget.org/packages/Microsoft.OpenApi/1.1.1

**Comment by korygin** [comment]
Thanks, Perth. I can confirm this is fixed  in 1.1.1
