### ISSUE TITLE
Is there a way when defining responses to give it T and let the lib create the schema?

### ISSUE THREAD

**Issue by jchannon** [Microsoft/OpenAPI.NET#352]
Is there a way to use the library for example to do `new OpenApiResponse{Content = new Foo()}` and it then creates the schema for you?

**Comment by PerthCharern** [comment]
Did you mean something like below?
- You provide an example in the Media Type object as `new Foo()`
- Call some function in the library
- The Media Type object will have schema populated

Unfortunately we don't have this capability implemented yet. I am not sure if it fits in the main scope of this library, but I can see how it can add convenience.

We DO have the validation in place for the type mismatch though. Say, if you add schema in the Media Type that conflicts with your example type Foo(), you will get a validation error in the Diagnostic.

**Comment by darrelmiller** [comment]
No @jchannon we don't try and infer schemas from C# types.  I think it would be an interesting add on, but I'm not convinced it should be part of the core.  The solution would start to get way to opinionated once the type has base classes and interfaces.
