### ISSUE TITLE
Create converter from C# object to IOpenApiAny

### ISSUE THREAD

**Issue by mattfrear** [Microsoft/OpenAPI.NET#377]
Hi,

I wish to set `OpenApiSchema.Example`. It is an IOpenApiAny. Is there a serializer/converter for creating an `IOpenApiAny` from a C# `object`? Or do I need to write my own using reflection?

**Background:** I am the author of a Swashbuckle filter which adds examples to request and response parameters and schemas. I see that the upcoming Swashbuckle 5.0 (in beta) is using OpenAPI.NET, so I am trying to convert my filter to use that.

**Comment by PerthCharern** [comment]
@mattfrear Unfortunately, we do not have such converter. If you need this functionality now, you will have to write this yourself.

@darrelmiller This seems like a nice thing (and an important thing) to have, and I recall we were asked for this before. I can't seem to recall the reason why we went against it though. Do you still remember?

This way, when someone wants to create an Example in the DOM, they can simply do something like myCSharpObject.ConvertToIOpenApiAny(). It might not be a perfect conversion since the types do not exactly match, but we can add some configuration for that as well.

**Comment by darrelmiller** [comment]
@PerthCharern I tend to avoid all conversations that relate to automatic serialization of C# types because it leads to pain :-).  However, I understand the desire for this feature.  It should be fairly simple to create a converter that handles 90% of scenarios.

**Comment by PerthCharern** [comment]
I'll rename this issue

**Comment by mattfrear** [comment]
FWIW someone told me that 
> You can set OpenApiSchema.Example to a new Microsoft.OpenApi.Any.OpenApiString(formattedJsonString).

So that has solved the problem for me for now. I'm happy if this issue gets closed.

**Comment by mattfrear** [comment]
Hi so this doesn't actually fix my issue after all. My example gets rendered as a JSON encoded string. So instead of:
```
"example": {
  "error": {
    "code": "EX0100",
    "reference": "https://reference.url",
    "message": "Authentication must be provided"
  }
}
```
I get
```
"example": "{\r\n \"error\": {\r\n \"code\": \"EX0100\",\r\n \"reference\": "https://reference.url\",\r\n \"message\": \"Authentication must be provided\"\r\n }\r\n}"
```
Could you reopen this issue please?

Related issue:
https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/99

**Comment by nate141** [comment]
> @mattfrear Unfortunately, we do not have such converter. If you need this functionality now, you will have to write this yourself.

can anyone give an example how to write one myself?

**Comment by mattfrear** [comment]
@nate141 I am doing that on my project, you can find the code here. See this PR (I didn't write it so don't ask me about it). 

https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/pull/100/files

**Comment by wilkovanderveen** [comment]
> Thanks mattfrear.
> 
> I have fixed it by applying the below code to convert the string to IOpenApiAny object
> 
> property.Value.Example = new Microsoft.OpenApi.Any.OpenApiString(defaultAttribute.Value.ToString());

This does not work for me: 

```csharp
public class CustomExampleSchemaFilter : ISchemaFilter
    {
        public void Apply(OpenApiSchema schema, SchemaFilterContext context)
        {
            if (schema.Properties == null)
            {
                return;
            }

            TrySetDefaulValueBasedOnAttributeOnType(schema, context);
            TrySetDefaultValueBasedOnAttributeOnProperty(context.Type, schema);
        }

        private static void TrySetDefaulValueBasedOnAttributeOnType(OpenApiSchema schema, SchemaFilterContext context)
        {
            var defaultPropertyValueAttribute = context.Type.GetCustomAttribute<DefaultPropertyValueAttribute>();

            if (defaultPropertyValueAttribute != null)
            {
                var relatedProperty = context.Type.GetProperties().SingleOrDefault(property => string.Equals(property.Name, defaultPropertyValueAttribute.PropertyName, StringComparison.Ordinal));

                if (relatedProperty != null)
                {
                    TrySetExampleAndDefaultValue(schema, defaultPropertyValueAttribute, relatedProperty);
                }
            }
        }

        private static void TrySetExampleAndDefaultValue(OpenApiSchema schema, object defaultValue, PropertyInfo relatedProperty)
        {
            foreach (KeyValuePair<string, OpenApiSchema> property in schema.Properties)
            {
                if (string.Equals(relatedProperty.Name, property.Key, StringComparison.InvariantCultureIgnoreCase))
                {
                    property.Value.Example = new OpenApiString(defaultValue.ToString());
                    property.Value.Default = new OpenApiString(defaultValue.ToString());

                    break;
                }
            }
        }

        private void TrySetDefaultValueBasedOnAttributeOnProperty(Type type, OpenApiSchema schema)
        {
            foreach (PropertyInfo propertyInfo in type.GetProperties())
            {
                DefaultValueAttribute defaultAttribute = propertyInfo
                    .GetCustomAttribute<DefaultValueAttribute>();

                if (defaultAttribute != null)
                {
                    TrySetExampleAndDefaultValue(schema, defaultAttribute.Value, propertyInfo);
                }
            }
        }
    }
```

The values are being set but it does not show up in my api explorer

**Comment by prenaissance** [comment]
I got such a generic solution to work in my application, which uses minimal api:

```cs
public static class OpenApiExtensions
{
    private static readonly JsonSerializerOptions jsonSerializerOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };
    public static RouteHandlerBuilder WithExample<T>(this RouteHandlerBuilder builder, T example)
    {
        builder.WithOpenApi(
            config =>
            {
                config.RequestBody = new OpenApiRequestBody
                {
                    Content = new Dictionary<string, OpenApiMediaType>
                    {
                        ["application/json"] = new OpenApiMediaType
                        {
                            Schema = new OpenApiSchema
                            {
                                Reference = new OpenApiReference
                                {
                                    Id = typeof(T).Name,
                                    Type = ReferenceType.Schema
                                }
                            },
                            Example = new OpenApiString(JsonSerializer.Serialize(example, jsonSerializerOptions))
                        }
                    }
                };
                return config;
            }
        );
        return builder;
    }
}
```

used like this:

```cs
group.MapPost("/login", Login)
    .WithDescription("Logs in the user and returns a JWT")
    .WithExample<LoginDto>(new("admin", "Test12345!"));
```
