### ISSUE TITLE
base64 data type

### ISSUE THREAD

**Issue by PavelZav** [Microsoft/OpenAPI.NET#379]
How is implement type:string format:byte? By the specification OAS should be base64, but in internal structures it's byte. Thank's

**Comment by PerthCharern** [comment]
@PavelZav We are finalizing the details about this. There is a bit of ambiguity (or unclearness) in the spec, so we got this incorrectly in the current version. It should be fixed soon.

**Comment by PavelZav** [comment]
Thanks

**Comment by PerthCharern** [comment]
FYI: @xuzhg sent out a PR for this (#391).

**Comment by PerthCharern** [comment]
I'll close this. Please reopen if there are still any issues.
