### ISSUE TITLE
Serious performance issues when reading some Open API documents

### ISSUE THREAD

**Issue by aslivker** [Microsoft/OpenAPI.NET#388]
We see serious performance issues when reading some Open API documents. The following code freezes and never returns (we left it run overnight).

            using (Stream input = File.OpenRead(@"c:\temp\Swagger.json"))
            {
                OpenApiDocument doc = new OpenApiStreamReader()
                    .Read(input, out OpenApiDiagnostic diagnostic);
            }

Hint: the problem seems to be related to resolving local references and type inheritance. The following code actually returns the result:

            using (Stream input = File.OpenRead(@"c:\temp\Swagger.json"))
            {
                OpenApiReaderSettings settings = new OpenApiReaderSettings()
                {
                    ReferenceResolution = ReferenceResolutionSetting.DoNotResolveReferences
                };

                OpenApiDocument doc = new OpenApiStreamReader(settings)
                    .Read(input, out OpenApiDiagnostic diagnostic);
            }

The Open API swagger.txt test file is attached. This problem is critical, as it prevents us from using this library.
[
[swagger.txt](https://github.com/Microsoft/OpenAPI.NET/files/2927778/swagger.txt)

](url)

**Comment by darrelmiller** [comment]
I just pasted your sample document into the workbench tool and it parsed it in 179ms from a cold start.  30ms, the second time.  

![image](https://user-images.githubusercontent.com/447694/54250914-f8ac8480-451b-11e9-9282-b51243546ed5.png)

We have been able to successfully parse this 22MB OpenAPI document that is full of inheritance relationships in under 10 secs.  https://github.com/microsoftgraph/microsoft-graph-openapi/blob/master/beta.json  

There must be something special about your scenario, but I currently cannot reproduce the issue.

**Comment by aslivker** [comment]
Please see attached Visual Studio project that clearly shows this issue.
Regards,
Andrew
[OpoenAPI-Issue.zip](https://github.com/Microsoft/OpenAPI.NET/files/2978593/OpoenAPI-Issue.zip)

**Comment by aslivker** [comment]
Do you have an update on this issue? Please see the latest message with attachment with complete example of a proven issue. We do not have any responses in 15 days now while this remains a blocking issue that prevents many customers from using this library.

**Comment by darrelmiller** [comment]
@aslivker  I guess your doc has some scenario that the 1.1.2 version doesn't like.  I was able to reproduce your issue.  I built a 1.1.3-preview nuget and ran your test on that and it completed very quickly.
I will try and get a new release out as soon as we get issue #390 fixed.

**Comment by darrelmiller** [comment]
1.1.3 has been released
