### ISSUE TITLE
OpenApiSchema.Items can be a array

### ISSUE THREAD

**Issue by ijsgaus** [Microsoft/OpenAPI.NET#389]
For tuple representation as array, OpenApiSchema.Items can be array of schemas - https://json-schema.org/understanding-json-schema/reference/array.html

**Comment by darrelmiller** [comment]
JSON Schema Items can be an array, however OpenAPI Schema Items specifically prohibits this behavior https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schema-object  One of the reasons being that it makes it because hard to create a model in strongly typed languages.
