### ISSUE TITLE
Descriptions are omitted for schema references

### ISSUE THREAD

**Issue by martincostello** [Microsoft/OpenAPI.NET#393]
If a property of a definition references another defined type via a reference, the description for the property is not written to the schema.

This means that specificity in a document for a description for a type of a property is not serialized to the schema.

This is because if the `Reference` property is non-null, it is the _only_ property serialized.

https://github.com/Microsoft/OpenAPI.NET/blob/c08eb18391e42555c00297de5530503f3be318a7/src/Microsoft.OpenApi/Models/OpenApiSchema.cs#L254-L258

https://github.com/Microsoft/OpenAPI.NET/blob/c08eb18391e42555c00297de5530503f3be318a7/src/Microsoft.OpenApi/Models/OpenApiSchema.cs#L427-L431

When the schema is serialized, allowable metadata such as the description should still be serialized when a reference is present.

**Expected**

```json
"definitions": {
  "Foo": {
    "description": "A foo",
    "type": "object",
    "properties": {
      "bar": {
        "$ref": "#/definitions/Bar",
        "description": "A custom Bar"
      }
    }
  },
  "Bar": {
    "description": "A bar",
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      }
    }
  }
}
```

**Actual**

```json
"definitions": {
  "Foo": {
    "description": "A foo",
    "type": "object",
    "properties": {
      "bar": {
        "$ref": "#/definitions/Bar"
      }
    }
  },
  "Bar": {
    "description": "A bar",
    "type": "object",
    "properties": {
      "name": {
        "type": "string"
      }
    }
  }
}
```

**Comment by darrelmiller** [comment]
@martincostello  Unfortunately that is by design.  The JSON Reference specification does not allow any keys to be by the side of it.  The OpenAPI TSC is currently working on a new mechanism that may allow something equivalent in the future but currently it is not allowed.  I know AutoREST supports it, but it is not valid OpenAPI.

**Comment by martincostello** [comment]
That’s a shame.

I did try out a V2 schema validator before opening this issue, which appeared to have no issues with the description being present, as well as trying to look up the rules in the spec, but I couldn’t seem to find anything that stated it was forbidden.

**Comment by darrelmiller** [comment]
@martincostello   It isn't the easiest thing to find.  If you see [here](http://spec.openapis.org/oas/v3.0.2#fixed-fields-18) it says:

> This object cannot be extended with additional properties and any properties added SHALL be ignored.

**Comment by MikeBeaton** [comment]
I've come across this as well. It's frustrating (specific details follow). I do realise from the above that this is not something controlled by this project, but I am not sure where else to post a comment that might be heard.

A `string`, `int` or `bool` property can have a description of what it is for, but it seems wrong that a custom `Address` type property, say, should not also have a description to say whether it is a home or work address.

To give a real-world example, I am using [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) and it is correctly capturing the schema references where my C# API objects contain child objects, and the also capturing in the schema objects descriptions of what those reference objects are for from my XML comments.

But then OpenAPI.NET is (correctly!) not serializing the description even though it is present in the schema, and even if I hack the code from this project (it only needs a couple of lines changes) to output descriptions into the JSON where present along with references, then of course the [Swagger UI](https://swagger.io/tools/swagger-ui/) is (correctly!) ignoring them for display in the UI.

It doesn't prima facie sound hard to change the spec to allow only an optional `Description` field in addition to the `$ref` field? (So partly I was just wondering why an entire new mechanism is considered necessary for this.)

**Comment by MikeBeaton** [comment]
See also: https://github.com/OAI/OpenAPI-Specification/issues/556

**Comment by zxli** [comment]
I feel I'm facing similar issue. I create OpenApiResponse with both description and reference set. And description is not in the serialized content. The problem is AutoRest is expecting description and will fail to generate client if description is not in the input. With this issue present, it looks like I cannot make the generated Swagger definition work in AutoRest by default.

Here is the implementation in OpenApiResponse. It clearly indicates Reference and description (likely other properties) are mutually exclusive.

        /// <summary>
        /// Serialize <see cref="OpenApiResponse"/> to Open Api v2.0.
        /// </summary>
        public void SerializeAsV2(IOpenApiWriter writer)
        {
            if (writer == null)
            {
                throw Error.ArgumentNull(nameof(writer));
            }

            if (Reference != null)
            {
                Reference.SerializeAsV2(writer);
                return;
            }

            SerializeAsV2WithoutReference(writer);
        }

**Comment by darrelmiller** [comment]
@MikeBeaton Newer versions of JSON Schema have introduced a major distinction between the notion of annotations and constraints.  By doing this they have enabled merging of annotations but remove the problem of trying to figure out how to merge constraints.  Descriptions are considered annotations and not constraints.

We are currently trying to figure out if we can safely adopt JSON draft-8 in OpenAPI 3.1.  Maybe there will be good news at some point in the near future.

**Comment by fearthecowboy** [comment]
> It is unfortunate that AutoREST decided to allow this. I understand why they did and I have talked with the team about this issue. Hopefully we can move past this in the near future.

Hey man, it was like that when I got here 🗡

**Comment by darrelmiller** [comment]
Fear not @fearthecowboy , this will be allowed in 3.1 !
