### ISSUE TITLE
Nullable path param with default value 'null' causes error for valid doc 

### ISSUE THREAD

**Issue by linelson** [Microsoft/OpenAPI.NET#394]
The OpenAPI.NET library fails to parse the following valid doc:
```
openapi: 3.0.0
info:
  version: 1.0.0
  title: My New Service
paths:
  /test/{id}:
    get:
      summary: Sample endpoint for my awesome service.
      parameters: 
        - name: id
          in: path
          description: sample description
          required: true
          schema:
            type: bool
            default: null
            nullable: true
      responses:
        '200':
          description: OK
```
The error produced is  "Data and type mismatch found. [#/paths/~1test~1{id}/get/parameters/0/schema/default]". The document appears to be a valid Open API 3 document per the spec. It appears to be complaining about          
 ```
     schema:
            type: bool
            default: null
            nullable: true
 ```

Library version: 1.1.2

**Comment by darrelmiller** [comment]
Hmmm, curious.  I just ran the workbench tool from the current master branch and I was able to parse it.

![image](https://user-images.githubusercontent.com/447694/55025821-111aa580-4fd8-11e9-9814-a7243901b482.png)

It is possible this was one of the bug fixes since 1.1.2

**Comment by linelson** [comment]
Apologies, I posted the incorrect version of the document. Here is the correct one for reproducing this issue:

```
openapi: 3.0.0
info:
  version: 1.0.0
  title: My New Service
paths:
  /test/{id}:
    get:
      summary: Sample endpoint for my awesome service.
      parameters: 
        - name: id
          in: path
          description: sample description
          required: true
          schema:
            type: boolean
            default: null
            nullable: true
      responses:
        '200':
          description: OK
```

Note that 'bool' has been changed to 'boolean'. I also cannot repro with the spec I posted originally.

**Comment by darrelmiller** [comment]
Ahh, yes.  So in 1.12 we had a PR that validated the default value based on the data type.  This looks like an edge case that was missed.  However, I believe we have since pulled those changes because the spec does not require the default value to match the schema.  It says, the default SHOULD be valid, but the document is not invalid if it doesn't.  I need to investigate what the current state of that is because I can repro the error and I don't think I should be seeing it. 

You can work around this by removing that schema validation rule from the set of rules like I did here https://github.com/darrelmiller/apislice/blob/master/apislice/FilterOpenApiService.cs#L124

**Comment by PerthCharern** [comment]
@darrelmiller We haven't pulled those changes I believe. We still allow the document generation to go through, just with errors. It might be the right time to introduce Warnings (to be used for SHOULD cases). I think you suggested this a while back but I can't seem to locate that.

**Comment by PerthCharern** [comment]
That aside, I think this one is a MUST, not a SHOULD:

default - The default value represents what would be assumed by the consumer of the input as the value of the schema if one is not provided. Unlike JSON Schema, the value MUST conform to the defined type for the Schema Object defined at the same level. For example, if type is string, then default can be "foo" but cannot be 1.

**Comment by darrelmiller** [comment]
@PerthCharern My apologies...  I didn't think the spec had a MUST there.  I need to go back and look at the scenario where I was ignoring this errors.  

I agree we should look into the idea of Warnings.  

I aslo need to investigate why using "bool" as a type didn't give an error.

**Comment by PerthCharern** [comment]
No problem at all :) 

Regarding the "bool" issue, we don't have a validator that checks the validity of the type name itself. 

The current check for `default` only gets triggered when the `type` + `format` combo is something we recognize.
