### ISSUE TITLE
How to read examples after parsing the file.

### ISSUE THREAD

**Issue by divyanshmethi** [Microsoft/OpenAPI.NET#395]
Hi,
I have problem related to example object
I have tried defining example 

1. as a part of schema 

schema:
            type: string
            pattern: '^\d{3}-\d{4}$'
            example: "hello"

2. as separate object.

components:
  schemas:
     MyComponent:
        type: object
        properties:
           id:
              type: integer
        example:
           id: 1

cmd: 
OpenApiDocument doc = new OpenApiStreamReader().Read(input, out OpenApiDiagnostic diagnostic);
doc.Components.Schemas["MyComponent"].Example

But I am not able to read the values of these example as it of type IOpenAPIAny.
Is there any way I can read the example values

**Comment by nitinkathpalia09** [comment]
I'm facing the same issue.

**Comment by Shwetap05** [comment]
@divyanshmethi do you want to read those value as string? If so then you can use below code
```c#
            var outputStringWriter = new StringWriter();
            var sourceWriter = new OpenApiJsonWriter( outputStringWriter );
            sourceWriter.WriteAny( doc.Components.Schemas["MyComponent"].Example );

            string exampleString = outputStringWriter.GetStringBuilder().ToString();
```

**Comment by divyanshmethi** [comment]
Thanks @Shwetap05
