### ISSUE TITLE
When is the next release?

### ISSUE THREAD

**Issue by deniszykov** [Microsoft/OpenAPI.NET#397]
There are bugs that are blockers in 1.1.2 and fixed in current development branch. I want to know when the next version will be released.

**Comment by darrelmiller** [comment]
I believe we should get #390 fixed before we release a new version.  @VitaliyKurokhtin said that he might have time to take a look at it.

**Comment by VitaliyKurokhtin** [comment]
I will try to do that tomorrow.

**Comment by VitaliyKurokhtin** [comment]
Here you go #398

**Comment by deniszykov** [comment]
Thanks @VitaliyKurokhtin for quick fix!

Looking forward to release

**Comment by PerthCharern** [comment]
v1.1.3 is now live on NuGet.org.
