### ISSUE TITLE
Schema array type with anyOf and discriminator fails validation

### ISSUE THREAD

**Issue by rwrife** [microsoft/OpenAPI.NET#402]
I'm trying to validate an OpenAPI document that contains a schema object that is of type 'array' that can be an 'anyOf' that uses a discriminator to know which object goes into the array and it's failing validation.  The document appears to be a valid OAS3 document and the Swagger UI has no issues rendering it, so I'm guessing it's an issue with OpenAPI.NET.

I'm getting validation errors similar to:

> Composite Schema ChildTypeA must contain property specified in the discriminator type. [#/components/schemas/SampleResponse/properties/suggestedActions/items/anyOf]
Composite schema ChildTypeA must contain property specified in the discriminator type in the required field list. [#/components/schemas/SampleResponse/properties/suggestedActions/items/anyOf]

...for this document

```
openapi: 3.0.0
info:
  description: Service to test discriminator
  version: 1.0.0
  title: Test Service
servers:
  - url: 'https://localhost'
paths:
  /test:
    post:
      description: Sample post of SampleRequest
      requestBody:
        description: Returns the SampleResponse with multiple types
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SampleRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SampleResponse'
components:
  schemas:
    SampleRequest:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          description: Random ID
          example: '1513776099991'
    BaseType:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          description: Suggested object type
    ChildTypeA:
      allOf:
        - $ref: '#/components/schemas/BaseType'
          properties:
            type:
              type: string
              enum:
                - typeA
      type: object
    ChildTypeB:
      allOf:
        - $ref: '#/components/schemas/BaseType'
          properties:
            type:
              type: string
              enum:
                - typeB
      type: object
    SampleResponse:
      type: object
      properties:
        suggestedActions:
          type: array
          items:
            anyOf:
              - $ref: '#/components/schemas/ChildTypeA'
              - $ref: '#/components/schemas/ChildTypeB'
            discriminator:
              propertyName: type
```

**Comment by PerthCharern** [comment]
I think currently that rule only looks at the properties in the schema itself without delving into the properties in the anyOf/allOf. This is a bug in our validator.

**Comment by ma499** [comment]
Are there any plans to fix this bug? This validator is now being used by Azure API Management when deploying APIs, and we are no longer able to deploy updates to our existing API to production because of this problem.

**Comment by Robzilla** [comment]
Yes reported last November. Pretty big impact for me too. Apparently a fix is rolling out next week. See https://github.com/microsoft/OpenAPI.NET/issues/429
Bit scary when something this big stops deployments for a few months.

**Comment by fabich** [comment]
@PerthCharern any updates on this?

**Comment by ma499** [comment]
Is this actually a bug? I just read the relevant section of the latest Open API 3.0.3 specification which [indicates that a discriminator field is actually required to be a 'required' field](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#composition-and-inheritance-polymorphism).

> To support polymorphism, the OpenAPI Specification adds the discriminator field. When used, the discriminator will be the name of the property that decides which schema definition validates the structure of the model. As such, the discriminator field MUST be a required field. There are two ways to define the value of a discriminator for an inheriting instance.

This is not new, the same is specified for Open API 2.0.

Therefore, having read the specification, and thinking about the semantics of a discriminator field, I would argue that OpenAPI.NET's behaviour is actually correct and the official OpenAPI/Swagger parsers are the ones that actually have the bug as they are not strict enough to identify this problem.

**Comment by himanigulati** [comment]
Is this issue still Open? We are dealing with the similar problem.

**Comment by amrith92** [comment]
@himanigulati Yes, I think this is still open.

**Comment by darrelmiller** [comment]
Ok, I must be doing something wrong.  I'm trying the above sample in the OpenAPIWorkbench tool from the master branch and I am not seeing the error... 
![image](https://user-images.githubusercontent.com/447694/106364740-56f4d300-62ff-11eb-8d83-bef2f1e83e37.png)

**Comment by darrelmiller** [comment]
I verified this again and I am not seeing any errors.  Please re-open if you find this is still a problem.

**Comment by cnwta3** [comment]
I can still reproduce the error with the following reproducer specification.

```
openapi: 3.0.0
info:
  description: Service to test discriminator
  version: 1.0.0
  title: Test Service
servers:
  - url: 'https://localhost'
paths:
  /test:
    post:
      description: Sample post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Parent'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Parent'
components:
  schemas:
    Parent:
      type: object
      oneOf:
         - $ref: '#/components/schemas/ChildA'
         - $ref: '#/components/schemas/ChildB'
      discriminator:
         propertyName: type
    ChildA:
      properties:
        type:
          type: string
      type: object
    ChildB:
      properties:
        type:
         type: string
      type: object
```

I get the following error: 

> "Schema Parent must contain property specified in the discriminator type in the required field list."

The specification validates correctly in Swagger Editor.

**Comment by danehorak-callaway** [comment]
Can we get an update on the status of this fix? When can we expect a fix to be released?

**Comment by baywet** [comment]
Hi everyone,
We just hit that issue recently with our internal tooling. After a quick chat with @darrelmiller here is the course of actions.

[This code block](https://github.com/microsoft/OpenAPI.NET/blob/76681b01876184801b9043df3763f1a5ddd6e293/src/Microsoft.OpenApi/Validations/Rules/OpenApiSchemaRules.cs#L71) needs improvements:
- [The spec mandates that discriminator fields are required](https://spec.openapis.org/oas/v3.1.0#composition-and-inheritance-polymorphism). [more reading on the discriminator](https://spec.openapis.org/oas/v3.1.0#discriminator-object)
- It should look recursively into the allOf/oneOf/anyOf when present

When the validation rule doesn't find the discriminator field in the current schema's required fields, it should recursively look into the anyOf/oneOf/allOf schemas (if any) before returning an error.

Ping @CarolKigoonya to bump the priority of this one given the current impact.

**Comment by julealgon** [comment]
I see this was apparently fixed several years ago, but I'm seeing the exact same issue today while attempting to import an OpenApi spec into Azure API Management:

> Parsing error(s): Schema KpiDataResponse must contain property specified in the discriminator $type in the required field list. [#/components/schemas/KpiDataResponse/discriminator]

<img width="2272" height="1392" alt="Image" src="https://github.com/user-attachments/assets/ffe3049d-2547-4fb0-9c7c-6c50b48689b9" />

This just happened as I switched our OpenApi generation in the API from `Swashbuckle`'s library, to latest `Microsoft.AspNetCore.OpenApi`.

In our case, this is due to an inheritance chain that generates this section:

```json
      "KpiDataResponse": {
        "type": "object",
        "anyOf": [
          {
            "$ref": "#/components/schemas/KpiDataResponseGetWarrantyPayRevenueV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetVehicleMileageAgeV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetUsedDealVolumeV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetUsedDealsByCustomerSegmentV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetTriggersMarketingV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetTradeInDealsV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetTotalRepairOrderRevenueV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetTotalGrossProfitsUsedDealsV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetTotalGrossProfitsNewDealsV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetTimeToTradeInResaleV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetTimeToServiceResponseV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetTimeToReturnServiceV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetTimeToFirstServiceV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetThreeYearServiceLifetimeVisitsV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetThreeYearServiceLifetimeSpendV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetServiceTriggerAppointmentConversionV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetServicesCompletedByCategoryV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetServiceRetentionV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetServiceOpportunitiesInPositiveEquityV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetServiceEmailCollectionV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetSalesToServiceSchedulingV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetSalesResponseV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetSalesEmailCollectionV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetRevenueOfServiceV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetRepairOrderVolumeV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetRepairOrderRevenueByVehicleAgeV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetRepairOrderLaborHoursV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetRepairOrderAppointmentsBySourceV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetPurchaseToServiceLoyaltyV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetPrintBudgetV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetPrintBudgetsV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetNumberOfCarsSoldV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetNewDealVolumeV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetNewDealsByCustomerSegmentV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetMonthsToRepurchaseV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetMarketingCustomersV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetLaneCheckInsV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetFiveYearRepurchaseRateV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetDailyMilesDrivenV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetCustomerPayRevenueV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetCustomerHealthV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetCapacityUtilizationV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetCampaignStatusV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetCampaignDrilldownV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetApprovedUpsellRevenueV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetAppointmentEmailCollectionV1ProcedureCallResponse"
          },
          {
            "$ref": "#/components/schemas/KpiDataResponseGetActiveVehiclesByMakeModelYearV1ProcedureCallResponse"
          }
        ],
        "discriminator": {
          "propertyName": "$type"
        }
      },
```

Can someone clarify whether or not this is a bug on the _parsing_ side (on Azure API Management), or a bug in the _generation_ side?

This is currently making it impossible for us to update our API in APIM.

**Comment by baywet** [comment]
If the type property is defined on all the anyOf entries somehow, it's a bug on the parsing side.
If it's not defined on all the anyOf entries, it's a bug on the generation side.

**Comment by julealgon** [comment]
> If the type property is defined on all the anyOf entries somehow, it's a bug on the parsing side. If it's not defined on all the anyOf entries, it's a bug on the generation side.

@baywet that `$type` property does not exist in _any_ of the actual .NET models (not in the `abstract` base, and not in any of the concrete ones). It was automatically generated by `Microsoft.AspNetCore.OpenApi` to model the hierarchy as a set of `anyOf` entries.

I assume I should go ahead and open a Bug on the library then?

**Comment by baywet** [comment]
https://github.com/dotnet/aspnetcore yes

**Comment by julealgon** [comment]
Thanks @baywet . While creating a smaller repro to post the issue on the `aspnetcore` repo, I realized that the reason we were getting that structure was due to a custom `DefaultJsonTypeInfoResolver` implementation, and that when removing that customization, we get a valid document again.

I'll look into that customization on our side more closely before opening the issue as it may very well just be an oversight on our side and not on the library side.
