### ISSUE TITLE
Resolve remote references in v 1.1 ?

### ISSUE THREAD

**Issue by jrouaix** [microsoft/OpenAPI.NET#406]
Hello, 

I had the hope to replace our nasty json swagger v2 merge with your shiny lib but I ran into some trouble : https://github.com/Microsoft/OpenAPI.NET/blob/5742db6b5f0f8bd9990fbf43a7e03a8b0b6f674a/src/Microsoft.OpenApi.Readers/Services/OpenApiReferenceResolver.cs#L229-L236

Do you plan to reschedule this feature to a close future ?
(the code that I hope to get rid of is right here : https://github.com/BeezUP/dotnet-codegen/blob/master/Dotnet.CodeGen/Schemas/SwaggerSchemaLoader.cs)

**Comment by darrelmiller** [comment]
I have a branch dm/openapiworkspace that is designed to deal with multiple related documents.  I haven 't had chance to work on it for a while.  Hopefully I can get back to it soon.

**Comment by darrelmiller** [comment]
Referencing components in external OpenAPI documents is working.  There is still work to do to reference fragments of OpenAPI in arbitrary JSON/YAML files.
