### ISSUE TITLE
 How can I resolve remote references?

### ISSUE THREAD

**Issue by ayungan** [microsoft/OpenAPI.NET#409]
How can I resolve remote references?
Hi, I would like to resolve remote references, could someone help me please

**Comment by darrelmiller** [comment]
That capability isn't finished yet.  The current work is in the openapiworkspace branch

**Comment by V0v1kkk** [comment]
Could you increase priority of the feature, please?
Our contract-first specification contains 24k lines and it's painfull.

**Comment by darrelmiller** [comment]
Referencing external OpenAPI documents is working.  There is still work to do to reference fragments of OpenAPI in arbitrary JSON/YAML files.
