### ISSUE TITLE
<< is not a valid property - support yaml merge keys

### ISSUE THREAD

**Issue by deltafsdevelopment** [microsoft/OpenAPI.NET#410]
Hi 

Currently the reader does not support the use of yaml "<<" [merge keys](https://yaml.org/type/merge.html)

Repo:

        [Fact]
        public void TestMergeKeysOnParameters()
        {
            // Arrange
            OpenApiDocument document;
            var diagnostic = new OpenApiDiagnostic();

            String spec = @"
              openapi: 3.0.0
              info:
                description: This is a simple API
                version: 1.0.0
                title: Simple Inventory API
              paths:
                /inventory:
                  get:
                    summary: searches inventory
                    operationId: searchInventory
                    parameters:
                      - $ref: '#/components/parameters/custom-header-example1'
                    responses:
                      '200':
                        description: OK
              components:
                parameters:
                  custom-header: &custom-header
                    name: custom-header
                    in: header
                    description: The requested API version 
                    required: false
                    schema:
                      type: string
                    style: simple
                  custom-header-example1:
                    <<: *custom-header
                    example: specific example
              ";
            document = new OpenApiStringReader().Read(spec, out diagnostic);

            var parameter = document.Paths.First().Value.Operations.First().Value.Parameters.First();

            parameter.ShouldBeEquivalentTo(
                new OpenApiParameter
                {
                  Name = "custom-header",
                  In = ParameterLocation.Header,
                  Description = "The requested API version",
                  Required = false,
                  Schema = new OpenApiSchema
                  {
                    Type = "string"
                  },
                  Style = ParameterStyle.Simple,
                  Example = new OpenApiExample
                  {
                    Value = new OpenApiString("specific example") 
                  } as IOpenApiAny
                }
            );
        }

The diagnostic contains the following errors:

      [0]: {<< is not a valid property at #/components/parameters}
      [1]: {The field 'name' in 'parameter' object is REQUIRED. [#/components/parameters/custom-header-example1/name]}
      [2]: {The field 'in' in 'parameter' object is REQUIRED. [#/components/parameters/custom-header-example1/in]}

custom-header-example1 should "merge" in the properties of the referenced "custom-header" parameter, redefining "example". However once read in the document has null for all the other properties of "custom-header-example1".

Do you have any plans to support the merge syntax as it is valid yaml and useful for very large open api specs with reused components?

Thanks in advance.

**Comment by darrelmiller** [comment]
The OpenAPI spec only supports YAML that uses the [JSON Schema](https://yaml.org/spec/1.2/spec.html#id2803231).  This ensures OpenAPI descriptions can be roundtripped between JSON and YAML.

**Comment by darrelmiller** [comment]
Please feel free to reopen this issue if you feel it has not been resolved.
