### ISSUE TITLE
Extension mechanism is broken

### ISSUE THREAD

**Issue by Cloudmersive** [microsoft/OpenAPI.NET#411]
Just want to add "x-ms-summary" (which ironically is Microsoft-based) to a Parameter but the AddExtension mechanism requires me to write a whole IOpenApiExtension class and go through a writer.  I just want to add custom key/value pairs.

**Comment by Cloudmersive** [comment]
This is how it should be done for reference: https://github.com/tavis-software/Tavis.OpenApi/blob/master/src/OpenApi/Model/Parameter.cs

**Comment by khellang** [comment]
Can't you just do `.AddExtension("x-ms-summary", new OpenApiString("blah"))`?

**Comment by darrelmiller** [comment]
I'm going to assume this is the fault of me not actually writing any documentation for this library.  I really should do that.  I'm going to close this issue and @Cloudmersive  can you let me know if this is still an issue for you?
