### ISSUE TITLE
Swagger 2, no host or basepath values

### ISSUE THREAD

**Issue by Trekkan** [microsoft/OpenAPI.NET#426]
It seems these are combined into a "servers" object.  However that object concats these two values together, opening the door for mistakes.  

Basically, the concat value is great, but please preserve the original host and basepath values as different properties on the server object.

**Comment by darrelmiller** [comment]
That is not how the OpenAPI V3 specification has been defined..  However, you should be able to take the Server.Url and use standard URL parsing logic to separate the host and path.

What is the reason why you are trying to keep those values separate?

**Comment by SlavekRydval** [comment]
The reason could be that you must still maintain RestAPI 2.0.

**Comment by darrelmiller** [comment]
@SlavekRydval Sorry, I don't understand what you mean.  You can continue using the separate host and basepath if you are using OpenAPI 2.0.  It is only in OpenAPI 3.0 that it is merged together.

**Comment by SlavekRydval** [comment]
@darrelmiller Lets say the host+basepath is https://www.abcd.efg/hi/jk/lm. There are programmers who set https://www.abcd.efg/hi as a host and jk/lm as a path.

**Comment by darrelmiller** [comment]
Well, that would be wrong because https://www.abcd.efg/hi  is not a host.  https://tools.ietf.org/html/rfc3986#section-3.2.2

**Comment by SlavekRydval** [comment]
I agree with you but customer is always right.

**Comment by darrelmiller** [comment]
And the customer has the right to go and use a different free library created by developers in their free time.
