### ISSUE TITLE
OpenApiDocument.SerializeAsV2 throws UriFormatException when OpenApiServer.Url contains only a path

### ISSUE THREAD

**Issue by cgreenza** [microsoft/OpenAPI.NET#440]
`OpenApiDocument.SerializeAsV2` throws the following exception when `OpenApiServer.Url` is set to a path only e.g. `doc.Servers = new List<OpenApiServer> { new OpenApiServer { Url = "/api" } }`

```csharp
System.UriFormatException
  HResult=0x80131537
  Message=Invalid URI: The format of the URI could not be determined.
  Source=System.Private.Uri
  StackTrace:
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at Microsoft.OpenApi.Models.OpenApiDocument.WriteHostInfoV2(IOpenApiWriter writer, IList`1 servers)
   at Microsoft.OpenApi.Models.OpenApiDocument.SerializeAsV2(IOpenApiWriter writer)
   at OpenApiTest.Program.Main(String[] args)
```

`OpenApiDocument.SerializeAsV3` works fine with server URLs that contain only a path.

The OpenAPI V2 Specification allows for independent setting of [`basePath`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swaggerBasePath) and [`host`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swaggerHost), so setting only a path should be possible.

Setting the basePath is needed for cases where multiple APIs are hosted in different virtual directories on the same host. Not setting the host is useful because the server generating the swagger document does then not need to know the hostname that clients are using to access it.

Below the code to reproduce this exception:

```csharp
static void Main(string[] args)
{
    var document = CreateDocument("/api"); // http://petstore.io/api works in all cases

    var w1 = new OpenApiJsonWriter(new StringWriter());
    document.SerializeAsV2(w1); // fails with exception

    var w2 = new OpenApiJsonWriter(new StringWriter());
    document.SerializeAsV3(w2); // success
}

static OpenApiDocument CreateDocument(string serverUrl)
{
    return new OpenApiDocument {
        Info = new OpenApiInfo {
            Version = "1.0.0",
            Title = "Swagger Petstore",
        },
        Servers = new List<OpenApiServer> {
            new OpenApiServer { Url = serverUrl }
        },
        Paths = new OpenApiPaths {
            ["/pets"] = new OpenApiPathItem {
                Operations = new Dictionary<OperationType, OpenApiOperation> {
                    [OperationType.Get] = new OpenApiOperation()
                }
            }
        }
    };
}
```

**Comment by darrelmiller** [comment]
Thanks for reporting this.  I was able to reproduce the issue you described and agree it is a bug.

**Comment by cgreenza** [comment]
Thanks for looking into this Darrel. Appreciate your speedy response and resolution.

**Comment by KalleOlaviNiemitalo** [comment]
I am getting a somewhat similar exception with Microsoft.OpenApi 1.2.2. Exception.Message is however different.

```
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Microsoft.OpenApi.Models.OpenApiDocument.WriteHostInfoV2(IOpenApiWriter writer, IList`1 servers)
   at Microsoft.OpenApi.Models.OpenApiDocument.SerializeAsV2(IOpenApiWriter writer)
```

I'll try to set up a publishable test case in a few days and then decide whether to add it to this issue or open a new one.
