### ISSUE TITLE
I have a custom parameter attribute and want it to cause Swagger to display the request body input.

### ISSUE THREAD

**Issue by jpactor** [microsoft/OpenAPI.NET#451]
Scenario:
My application reads the entire request body as a byte array and saves it to a database. To do this, I created a custom model binder that reads the request body and passes it along; I associate that binder with a custom attribute, "RawBody". This behavior works as expected: The controller action's method parameter receives the body as a byte array and I pass it along to my DAL.

I would like Swagger to expose the request body input field so users in swagger can provide a value to save, and I'm running into difficulties. In its current state, with no "FromBody" attribute, the property is identified as a "query" parameter, and Swagger will try to post that body as a query parameter when I execute it. This of course means the request body is empty, and so an empty array (byte[0]) is sent along to the DAL.

I've tried investigating making a Parameter Filter with SwaggerGen, but here I hit a snag: I can't change the parameter's location to "Body", because the "ParameterLocation" enum does not have a "Body" value!

I read in another issue here that "OpenApi V3 doesn't support body parameters", but I have a clear use case for needing to force a method parameter to be a body parameter instead of the default.

What are my options for enabling this scenario? Am I missing something?

Thanks in advance,
--Josh

**Comment by darrelmiller** [comment]
The RequestBody property on an operation is the body parameter.  You can use that to describe your request body.

**Comment by darrelmiller** [comment]
Please feel free to reopen this issue if you feel it has not been resolved.
