### ISSUE TITLE
Package Microsoft.OpenApi 1.1.4 is not compatible with netcoreapp3.1 (On Azure Devops)

### ISSUE THREAD

**Issue by HuNtR-RSA** [microsoft/OpenAPI.NET#454]
We keep on getting the following error when building an API (with Swagger) project on Azure Devops:

Package Microsoft.OpenApi 1.1.4 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.OpenApi 1.1.4 supports:
      - net46 (.NETFramework,Version=v4.6)
      - netstandard2.0 (.NETStandard,Version=v2.0)

**Comment by darrelmiller** [comment]
I experienced this same issue.  I had to update Nuget on Azure devops to a later version (5.4) before it worked for me.

**Comment by darrelmiller** [comment]
Please let me know if you are still having this issue.  Thanks.

**Comment by SrilakshmiTunduri** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package Microsoft.OpenApi 1.4.3 is not compatible with net7.0 (.NETCoreApp,Version=v7.0). Package Microsoft.OpenApi 1.4.3 does not support any target frameworks.	PatientManagement	F:\GitRepo\PatientManagement\PatientManagement\PatientManagement\PatientManagement.csproj	1

**Comment by HuNtR-RSA** [comment]
> Please let me know if you are still having this issue. Thanks.

It is sorted now, thanks..

I can't remember what I did, but I ended up updating Nuget packages left right and center on the project + updating the Nuget version used in Azure DevOps..

I've luckily been allowed to also update to NET 8 now..
