### ISSUE TITLE
Components section not rendered when serializing OpenAPI doc as V2 with inline reference settings

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET#464]
The _components_ section does not get rendered when serializing an OpenAPI doc as V2 with inline reference settings - in the case of cyclic references. This section gets added as a reference yet a _definitions_ section gets rendered. 

demo:

![image](https://user-images.githubusercontent.com/40403681/76017232-52793c00-5f2f-11ea-8ae8-ecbce3efa223.png)

**Comment by darrelmiller** [comment]
OpenAPI V2 docs do not have components sections.  There were however a bunch of issues with inlining in v2.  The 1.2.0-preview.2 release has a bunch of fixes for inlining a v2 document.
