### ISSUE TITLE
Apply OpenApi.Net to Api Document project in Asp.Net (Not Core)

### ISSUE THREAD

**Issue by DTH-012** [microsoft/OpenAPI.NET#468]
Hi,
Im currently using Swagger/Swashbuckle in Asp.Net (not core) for my Document Api project.
I want to apply OpenApi.Net to my project. But it's quite difficult.
I dont know how to apply based on your document/example.
Can someone give me more detailed document/example ?

**Comment by DTH-012** [comment]
f

**Comment by darrelmiller** [comment]
What is it that you are trying to do?

**Comment by darrelmiller** [comment]
Please feel free to re-open this issue if you can provide more details on what you are trying to achieve.
