### ISSUE TITLE
Issues with OpenAPI.Net

### ISSUE THREAD

**Issue by spparida** [microsoft/OpenAPI.NET#473]
Hello Team,

We are building one API catalog and using Microsoft.OpenApi.Readers library in our application. We found couple of issues like

- We are unable to fetch RequestBody Object (I am aware there is a difference between OAS2 & OAS 3)
- Response is having lot of unwanted parameters like Title,  Type, Format, Description...etc. and it's keep repeating for each property. Is it really required?
- In Swagger UI for each requestBody & response it shows some examples. I am unable to find them in the nuget/library response. Is this feature in your plan/pipeline to release in coming days?

Waiting for your response. Thanks.

**Comment by darrelmiller** [comment]
Hi @spparida 

Could you provide an example of a OpenAPI description that fails to parse the RequestBody object?  That would help us identify the issue.

The Response object only has a Description property.  A number of the properties you describe are from the Schema that is a property of the media type object.  The media type object can be set to null in the content map if you don't want those details.

There is an `example` property and `examples` property on the OpenAPIMediaType object and there is also an example property on the OpenApiSchema object.
