### ISSUE TITLE
Error importing OpenApi on Azure

### ISSUE THREAD

**Issue by silascaimi** [microsoft/OpenAPI.NET#476]
After trying to import into Azure, several errors are launched, among which are below

1. Parsing error (s): JSON is valid against no schemas from 'oneOf'. Path ......

for 
```
{
  "data": [
    {
      "data": {},
      "description": "string",
      "id": 0
    }
  ],
  "input": "string",
  "message": "string",
  "totalData": 0,
  "totalPages": 0
}
```

2. Parsing error (s): JSON does not match any schemas from 'anyOf'. Path ......

3. Parsing error (s): Property 'originalRef' has not been defined and the schema does not allow additional properties. Path .........

Finally, the following error occurs:

4. Parsing error (s): The input OpenAPI file is not valid for the OpenAPI specificate https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md (schema https://github.com/ OAI / OpenAPI-Specification / blob / master / schemas / v2.0 / schema.json).

**Comment by darrelmiller** [comment]
> After trying to import into Azure
I'm afraid I don't understand the context here.  What are you actually trying to do?  Can you provide a bit bigger sample of the OpenAPI description you are trying to work with.  The above example doesn't provide much context.

**Comment by silascaimi** [comment]
Thanks for the feedback
The problem was solved by changing the swagger version in the settings
