### ISSUE TITLE
Serializing as Json produces invalid Json for numeric types depending on culture

### ISSUE THREAD

**Issue by korygin** [microsoft/OpenAPI.NET#478]
This is the follow up on the original issue (https://github.com/microsoft/OpenAPI.NET/issues/396) that had been fixed in 1.1.3. I believe the problem still exists with example numeric values.

**Input JSON (read)**
"properties": {
  "weightTotalMax": {
     "type": "number", 
	 "format": "float", 
	 "description": "Максимальна загальна вага відправлення, кг", 
	 "example": 29.992
  }
}

**Output JSON (write)**
"properties": {
  "weightTotalMax": {
    "format": "float",
    "description": "Максимальна загальна вага відправлення, кг",
    "type": "number",
    "example": 29,
    992
  }
}

**Comment by darrelmiller** [comment]
I just switched my machine to French and confirmed that numbers were rendering with commas.  I then tried your example using the code in the vnext branch and it behaved as expected.  

I am going to release the 1.2 version.  Could you check with that version that you are still seeing the issue?

**Comment by korygin** [comment]
Thanks, Darrel. There can I get v 1.2? Is it published to NuGet?

Regards,

Alex

On May 24, 2020, at 18:26, Darrel <notifications@github.com> wrote:

﻿

I just switched my machine to French and confirmed that numbers were rendering with commas. I then tried your example using the code in the vnext branch and it behaved as expected.

I am going to release the 1.2 version. Could you check with that version that you are still seeing the issue?

**Comment by korygin** [comment]
Hi Darrel, I can confirm that the issue is fixed in 1.2. I'm going to close the issue now. Thanks!
