### ISSUE TITLE
Support custom name for body parameter in serialization for V2

### ISSUE THREAD

**Issue by asvishnyakov** [microsoft/OpenAPI.NET#486]
Or make code extendable to allow do it on customer side.

https://github.com/microsoft/OpenAPI.NET/blob/3d620544669801bc334e875d707feccbebf90d8d/src/Microsoft.OpenApi/Models/OpenApiOperation.cs#L244-L252

**Comment by darrelmiller** [comment]
If we auto-create an x-name when importing a v2 document and round-trip that when writing as v2, would that solve the problem for you?

**Comment by asvishnyakov** [comment]
@darrelmiller It's better to set `name`, of course. If you can't/don't want to fix issue this way, then probably you may just close it. #485 can be used as workaround.

**Comment by darrelmiller** [comment]
@asvishnyakov Sorry, I phrased that badly.   We can set the `name` property when we render in V2.  In V3 and in the OpenApiDocument the value would be stored as an extension.

**Comment by darrelmiller** [comment]
This is now enabled in 1.2.3
