### ISSUE TITLE
OpenAPI.NET 1.2.0 is not backwards compatible with 1.1.x

### ISSUE THREAD

**Issue by LeroyK** [microsoft/OpenAPI.NET#487]
Version 1.2.0 is not backwards compatible with 1.1.x. For example, the constructor of OpenApiString has changed from:

```c#
public OpenApiString(string value);
```
to
```c#
public OpenApiString(string value, bool isExplicit = false);
```

If another project references the old version, it cannot find the constructor since its signature has changed. It would have been better to add a new constructor or increase the major version number of the package (if you adhere to semantic versioning). At the very least, breaking api changes should be documented in the release notes.

**Comment by CumpsD** [comment]
This just bit me

`System.MissingMethodException: Method not found: 'Void Microsoft.OpenApi.Any.OpenApiString..ctor(System.String)'.`

**Comment by CumpsD** [comment]
Added a PR: https://github.com/microsoft/OpenAPI.NET/pull/489

**Comment by CumpsD** [comment]
@darrelmiller any chance for your input on this one please?

**Comment by darrelmiller** [comment]
Ugh.  Apparently optional parameters have source backward compatibility but not [binary backward compatibility](https://codeblog.jonskeet.uk/2015/06/03/backwards-compatibility-is-still-hard/).

**Comment by CumpsD** [comment]
> Ugh. Apparently optional parameters have source backward compatibility but not [binary backward compatibility](https://codeblog.jonskeet.uk/2015/06/03/backwards-compatibility-is-still-hard/).

Yep :) Compiler magic...

**Comment by hasancemcerit** [comment]
With 1.2.1, the previous `OpenApiString` error just got transformed into 

```Method not found: 'Void Microsoft.OpenApi.Writers.OpenApiJsonWriter..ctor(System.IO.TextWriter)'.```
🤔

**Comment by CumpsD** [comment]
@hasancemcerit PR ongoing to fix it: https://github.com/microsoft/OpenAPI.NET/pull/492

**Comment by CumpsD** [comment]
It's fixed. 1.2.2 has no breaking changes, and the others got delisted.

@darrelmiller This can probably be closed now :)

**Comment by darrelmiller** [comment]
@CumpsD Thank you for your help with this.
