### ISSUE TITLE
OpenApiTextReaderReader inconsistently sets "#char=" vs. "#line=" in OpenApiError.Pointer

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/OpenAPI.NET#495]
When `OpenApiTextReaderReader` translates a `YamlException` to `OpenApiError`, it sets "#line=" followed by a line number as `OpenApiError.Pointer`:

<https://github.com/microsoft/OpenAPI.NET/blob/cb254da1f72dfb29199ff45cc38fe05489e6d468/src/Microsoft.OpenApi.Readers/OpenApiTextReaderReader.cs#L73>

Here though, it instead sets "#char=" followed by a line number as `OpenApiError.Pointer`:

<https://github.com/microsoft/OpenAPI.NET/blob/cb254da1f72dfb29199ff45cc38fe05489e6d468/src/Microsoft.OpenApi.Readers/OpenApiTextReaderReader.cs#L48>

Because there is a line number in both cases, I think "#line=" would be more appropriate than "#char=".

**Comment by darrelmiller** [comment]
Thank you for raising this issue.  I agree that this is a mistake.  I suspect that may be a result of a bad merge.
