### ISSUE TITLE
Specification Extensions not supported for externalDocumentationObject

### ISSUE THREAD

**Issue by AP-G** [microsoft/OpenAPI.NET#513]
Dear all,

it looks like Specification Extensions are not supported for an [externalDocumentationObject](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#externalDocumentationObject).  If I parse the file I get a

`x-ExternalDoc-simple is not a valid property at #/paths/externalDocs`

This is strange in two ways, as the externalDocs is part of the OpenAPI Object (root) and not as part of paths.

Here is my example:

```
...
components:
....
security:
...
tags:
...
externalDocs:
  description: My external API documentation
  url: https://external.server.tld/doc
  # extension
  x-ExternalDoc-simple: MyContent
```

**Comment by darrelmiller** [comment]
Thank you!  I just checked and the code to deserialize extensions in both v2 and v3 is missing.  That should be an easy fix to get into a patch release.  I am puzzled about that error message though.
