### ISSUE TITLE
Creating top level empty Security Requirement object with empty scope throws `OpenApiReaderException`

### ISSUE THREAD

**Issue by Achuth17** [microsoft/OpenAPI.NET#518]
- I was following the official OAS 3.0.3 [doc](http://spec.openapis.org/oas/v3.0.3#security-requirement-object) to create a simple spec file describing an API with api key validation and I ran into this issue. Since securityScheme I wish to use is of type api key, the scope in the "security" (securityRequirement) object is required to be empty.
- This exception is thrown by OpenApiV3Deserializer#41 and is reproducible on the vnext branch.
- I couldn't find any tests for the security requirement object, How do we resolve this issue?

Example - 
```
openapi: 3.0.0
info:
  title: Simple Document
  version: 0.9.1
security: 
  api_key: []
paths: { }
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
  schemas:
    Dog:  ## "Dog" will be used as the discriminator value
      description: A representation of a dog
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        properties:
          packSize:
            type: integer
            format: int32
            description: the size of the pack the dog is from
            default: 0
            minimum: 0
        required:
        - packSize
```

**Comment by Achuth17** [comment]
@darrelmiller Any suggestions?

**Comment by darrelmiller** [comment]
Hi @Achuth17 

Sorry for the delay, my GitHub notifications are somewhat bankrupt.  The [Security property](http://spec.openapis.org/oas/v3.0.3#fixed-fields) in the OpenApi is a list of security requirements, so they should be defined like this:
```yaml
openapi: 3.0.0
info:
  title: Simple Document
  version: 0.9.1
security:  
  - api_key: [] 
paths: { }
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
```
