### ISSUE TITLE
Can't confers JsonScema with enums'Error converting value "type 1" to type 'Microsoft.OpenApi.Any.IOpenApiAny'

### ISSUE THREAD

**Issue by amid0** [microsoft/OpenAPI.NET#525]
Hi,
I've my JsonSchema and want to convert it to Microsoft.OpenApi.Models.OpenApiSchema class instance.

**Schema example** 
`
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://adzu.io/schemas/Item",
  "title": "Item",
  "type": "object",
  "properties": {
    "DisplayName": {
      "title": "Display Name",
      "description": "",
      "type": "string"
    },
    "ItemType": {
      "title": "Item type",
      "description": "",
      "type": "string",
      "enum": [
        "type 1",
	"type 2"
      ]
    }
  },
  "required": [
    "DisplayName"
  ]
}
`

**Code example**
`
var jObject = JObject.Parse(<json schema string here>);
`
`
var openApiSchema = jObject.ToObject<OpenApiSchema>();
`

**Error**
`
Newtonsoft.Json.JsonSerializationException: 'Error converting value "type 1" to type 'Microsoft.OpenApi.Any.IOpenApiAny'. Path 'properties.ItemType.enum[0]', line 17, position 16.'
`
If I remove enum property from original json and add it manually after conversion - in final swagger json it look exactly the same as in initial.

Can some one advice something about it.
Really do not want to handle enums manually especially in complex json's.

![image](https://user-images.githubusercontent.com/6542910/95334729-2653de00-08b7-11eb-8257-326b45eca86a.png)

**Comment by darrelmiller** [comment]
You can't use jObject.ToObject<> to deserialize the models in this library.  ToObject relies on the automatic serializer in Newtonsoft that doesn't understand any of the semantics of OpenAPI.

You can use ReadFragment<OpenApiSchema> on the OpenApiStringReader class to do what you are trying to do.  There is an example in this issue https://github.com/microsoft/OpenAPI.NET/issues/496

However, the JSON Schema you are trying to read is not valid for OpenAPI V3.  $schema is not allowed, nor is $id.  OpenAPI v3 only supports draft-04.  

OpenAPI has always used a slight variant of JSON schema that is not quite compatible with full JSON Schema. In the upcoming OpenAPI 3.1 which is currently in RC1 stage, we have native support for JSON Schema.  We are waiting for the JSON Schema 2020 draft to be released to align with that.

**Comment by amid0** [comment]
@darrelmiller Thank you.
Seems like your advise is exactly what I need.
Somehow I didn't catch this variant while researching.
