### ISSUE TITLE
OpenApiStreamReader disposes input stream after reading and it's not configurable

### ISSUE THREAD

**Issue by jaceks2106** [microsoft/OpenAPI.NET#530]
Hi all,

I have to use `OpenApiStreamReader` as a one of the several steps, of handling the `Stream`. The problem is, that when I read the stream using `OpenApiStreamReader.Read(stream)` at first, then the Stream is disposed and cannot be used anymore. I cannot configure anyhow to Read the stream without disposing it, as I can do that in the base `StreamReader`.

[Link - bool leaveOpen](https://docs.microsoft.com/pl-pl/dotnet/api/system.io.streamreader.-ctor?view=netcore-3.1#System_IO_StreamReader__ctor_System_IO_Stream_System_Text_Encoding_System_Boolean_System_Int32_System_Boolean_)

Here is my example reproduction:
```
// openApiSpec is a Stream argument of the method
var openApiStreamReader = new OpenApiStreamReader();
var openApiDocument = openApiStreamReader.Read(openApiSpec, out var openApiDiagnostic);
```

**Comment by darrelmiller** [comment]
This is a good call out.  We use StreamReader under the covers with a using statement, hence why dispose is called.   I think we can add a property to OpenReaderSettings to allow control of this.
