### ISSUE TITLE
ReadOnly attribute not transferring on V2 serialization

### ISSUE THREAD

**Issue by forteddyt** [microsoft/OpenAPI.NET#540]
I'm using Swashbuckle to generate a Swagger 2.0 spec for the [azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs/pull/11955). According to [this comment](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1734#issuecomment-701377319), Swashbuckle uses OpenAPI.NET to serialize into Swagger 2.0.

One of my controllers returns an object with the following property definition:
```c#
/// <summary>
/// The format of exported labels, also as the discriminator.
/// </summary>
[TypeDiscriminator]
[ReadOnly(true)]
[SwaggerMutability(Mutability.Read)]
public virtual ExportFormatType Format { get; set; }
```

In OpenApi 3.0, I get the expected schema signature (notice `"readOnly": true,`):
```json
"ExportSummary": {
        "required": [
          "format"
        ],
        "type": "object",
        "properties": {
          "format": {
            "enum": [
              "Dataset",
              "Coco",
              "CSV"
            ],
            "type": "string",
            "description": "The format of exported labels, also as the discriminator.",
            "readOnly": true,
            "x-ms-enum": {
              "name": "ExportFormatType",
              "modelAsString": false
            },
            "x-ms-mutability": [
              "read"
            ]
          },
...
}
```

however, the Swagger 2.0 schema signature is not as expected:
```json
"ExportSummary": {
      "required": [
        "format"
      ],
      "type": "object",
      "properties": {
        "format": {
          "description": "The format of exported labels, also as the discriminator.",
          "enum": [
            "Dataset",
            "Coco",
            "CSV"
          ],
          "type": "string",
          "x-ms-enum": {
            "name": "ExportFormatType",
            "modelAsString": false
          },
          "x-ms-mutability": [
            "read"
          ]
        },
...
}
```

The `"readOnly": true,` is missing from the schema signature. Am I missing something?

Also as a slight aside, I'm not sure why "format" is shown as required in the signature... But that's secondary to `"readOnly": true,` being missing and may be a Swashbuckle issue.

**Comment by darrelmiller** [comment]
According to the OpenAPI 2.0 specification you cannot mark a property as readOnly and set it as required.  https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-13  
In OpenAPI 3.0 it was allowed by the spec qualifies that request only applies to the response and not the request. https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#fixed-fields-20

In OpenAPI 3.1, all commentary around these properties have been removed and the behavior is left to be defined by JSON Schema.  JSON Schema has no notion of some constraints being applicable for just a response vs a request.  If you need different behavior then it will be necessary to define two different schemas.
