### ISSUE TITLE
FormatException while import valid swagger json spec

### ISSUE THREAD

**Issue by petarvu** [microsoft/OpenAPI.NET#543]
Hi

Unable to import a valid Swagger (OAS2) specification. The JSON file is quite large and the error message not very constructive, so very hard to pinpoint the exact line or part which is failing in the **OpenApiStringReader**.

Any help / guidance is very welcome 😃 

**Api specification**: https://tripletex.no/v2/swagger.json

**Error**
> System.FormatException: Input string was not in a correct format.

**Stack trace**
> Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
>     Number.ParseDecimal(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
>     Decimal.Parse(String s, IFormatProvider provider)
>     <.cctor>b__83_139(OpenApiSchema o, ParseNode n)
>     PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields)
>     OpenApiV2Deserializer.LoadSchema(ParseNode node)
>     <>c__DisplayClass6_0`1.<CreateMap>b__0(KeyValuePair`2 n)
>     SelectEnumerableIterator`2.MoveNext()
>     Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>     Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
>     MapNode.CreateMap[T](Func`2 map)
>     <.cctor>b__83_156(OpenApiSchema o, ParseNode n)
>     PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields)
>     OpenApiV2Deserializer.LoadSchema(ParseNode node)
>     <>c__DisplayClass7_0`1.<CreateMapWithReference>b__0(KeyValuePair`2 n)
>     SelectEnumerableIterator`2.MoveNext()
>     WhereEnumerableIterator`1.MoveNext()
>     Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
>     Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
>     MapNode.CreateMapWithReference[T](ReferenceType referenceType, Func`2 map)
>     <.cctor>b__83_13(OpenApiDocument o, ParseNode n)
>     PropertyNode.ParseField[T](T parentInstance, IDictionary`2 fixedFields, IDictionary`2 patternFields)
>     OpenApiV2Deserializer.ParseMap[T](MapNode mapNode, T domainObject, FixedFieldMap`1 fixedFieldMap, PatternFieldMap`1 patternFieldMap, List`1 requiredFields)
>     OpenApiV2Deserializer.LoadOpenApi(RootNode rootNode)
>     OpenApiV2VersionService.LoadDocument(RootNode rootNode)
>     ParsingContext.Parse(YamlDocument yamlDocument)
>     OpenApiYamlDocumentReader.Read(YamlDocument input, OpenApiDiagnostic& diagnostic)
>     OpenApiTextReaderReader.Read(TextReader input, OpenApiDiagnostic& diagnostic)
>     OpenApiStringReader.Read(String input, OpenApiDiagnostic& diagnostic)

**Comment by darrelmiller** [comment]
I pasted your example in the OpenAPIWorkbench tool using a latest branch of the code and it parsed without error.  It may be a bug that has been fixed recently.  I need to try the same in the master branch.

**Comment by darrelmiller** [comment]
Hmm, I tried it in the master branch, which should match with the latest released nuget and I didn't get any errors.

**Comment by darrelmiller** [comment]
If you are able to reproduce this issue in the latest release, please feel free to re-open this issue.
