### ISSUE TITLE
OpenAPI 3.1 is out!!!

### ISSUE THREAD

**Issue by gregsdennis** [microsoft/OpenAPI.NET#552]
The [OpenAPI v3.1 spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md) has been released! 🎉 

We want all the updates!  🎉 🎉

**Comment by darrelmiller** [comment]
:-)  We need to get the 1.3 milestone out and then we can focus on supporting 3.1.

We should definitely chat about how we can integrate well with whatever replaces Manatee.   I also want to get System.Text.JSON support into this library.  The perf difference for large documents is huge.

**Comment by gregsdennis** [comment]
https://github.com/gregsdennis/json-everything

This is the new library suite that replaces Manatee.Json.  It's fully supported by System.Text.Json.  (Turns out taking my parsing/serialization logic out made things a LOT faster.)

**Comment by darrelmiller** [comment]
@gregsdennis   Have you seen the PR Jason Desroisier wrote?  https://github.com/OAI/OpenAPI-Specification/pull/2489   We reviewed it in the last TSC meeting and it is looking really close.

**Comment by gregsdennis** [comment]
Yeah, I'm part of that discussion in Slack.  He's kind of our rep for right now. It's better than having 50 JSON Schema implementors yell at OAS.

**Comment by gregsdennis** [comment]
So discussions over at the OAI group have yielded that the new keywords are to be annotations only (which would be pretty easy to implement).  I might add in optional validation for `discriminator`, but I'm not sure yet.

**Comment by ygalbel** [comment]
Hi, 
We are using this library heavily.
We are working on a project that need support for Webhooks that are a part of OpenAPI 3.1.

Do you have date that you think we will be able to use it?
Thanks again for this great library

**Comment by gregsdennis** [comment]
So I had a look at implementing the new keywords.  Turns out OAS is saying that they're officially annotation-only, which means that there's nothing to validate.  I think there's still some discussion going on regarding the meta-schema and maybe a vocabulary ID, so if anything I'd need to make an extension lib for that.

@darrelmiller I'm happy to help build in the schema support when you're ready to work on this.

**Comment by darrelmiller** [comment]
Once I get the build pipeline fixed I can get this release out and start focusing on 3.1 support.

**Comment by ygalbel** [comment]
Thanks a lot.

Do I have to help and push it?

**Comment by gregsdennis** [comment]
>Do I have to help and push it?

I think you mean, ["Would it help if I got out and pushed?"](https://www.youtube.com/watch?v=2ccbTzkl2oY)

**Comment by darrelmiller** [comment]
the 1.3.0-preview almost went out on Sunday night and then I discovered the Nuget API key had expired and I need someone else to fix that.  Hopefully today.

**Comment by qub1n** [comment]
Guys, are you going to support OpenAPI v3.1 or not? This ticket is opened for two and half year already.

**Comment by srev-saxo** [comment]
Hi,

Do you have a rough idea about when OpenAPI 3.1 is going to be supported by OpenAPI.NET? 

Thanks

**Comment by sebasptsch** [comment]
I am also eager to see when 3.1 support is going to drop.

**Comment by gregsdennis** [comment]
This looks to be tracked in #795 now.  I'm going to close this issue in favor of that one.
