### ISSUE TITLE
OpenApiSchema additionalProperties cannot be deserialized when set to false

### ISSUE THREAD

**Issue by niels013** [microsoft/OpenAPI.NET#561]
I'm having an issue deserializing my swagger JSON file to an OpenApiDocument. I'm using Swashbuckle to generate the swagger JSON file of my dotnet web API and a lot of the schemas will get `"additionalProperties": false`.

I created a unit test where I have a simple swagger JSON string to deserialize it into an OpenApiDocument object like this:
````
[TestMethod]
public void SwaggerJSON_Deserialize_OpenApiDocument_Test()
{
    var swaggerJson = "{ \"openapi\": \"3.0.1\", \"info\": { \"title\": \"Test API\" }, \"paths\": {}, \"components\": { \"schemas\": { \"test\": { \"type\": \"object\", \"properties\": { \"name\": { \"type\": \"string\" } }, \"additionalProperties\": false } } } }";

    var openApiDocument = JsonConvert.DeserializeObject<OpenApiDocument>(swaggerJson);
    Assert.IsNotNull(openApiDocument);
    Assert.AreEqual("Test API", openApiDocument.Info.Title);
}
````

There I get the error `Error converting value False to type 'Microsoft.OpenApi.Models.OpenApiSchema'`
![image](https://user-images.githubusercontent.com/40338068/111804366-4e1c8880-88d0-11eb-893f-0b4e9dc4de28.png)

According to the specifications of swagger (https://swagger.io/specification/) the `additionalProperties` key can be either a boolean or an OpenApiSchema. I found an old issue where this was fixed in a pull request, but I'm still having this issue.

For reference:
Swashbuckle.AspNetCore.SwaggerGen: version 5.6.3
Microsoft.OpenApi: version 1.2.3.0
.NET: version 5.0

Old issue: #196

**Comment by darrelmiller** [comment]
You can't use Newtonsoft's DeserializeObject to create an OpenApiDocument.  That will never work because Newtonsoft JSON doesn't understand OpenAPI semantics.

You can use the OpenApiStringReader class though.

It will read the additonalProperties properly.  However based on my tests, it does not write out additionalProperties properly in V2.  The V3 writer works fine.

Here's the test case I used.
```yaml
openapi: 3.0.1
info:
  title: foo
  version: 1.0.0
paths: {}
components:
  schemas:
    foo:
      type: object
      additionalProperties: false
```

**Comment by niels013** [comment]
Thank you for your response. I can confirm that my test works using the OpenApiStringReader class to read an OpenAPI V3 swagger JSON file. Shall I close this bug since the original issue is resolved or do you want to keep it open because of the other issue you found writing additionalProperties in V2?
