### ISSUE TITLE
OpenApiStreamReader object is missing the ReadAsync method

### ISSUE THREAD

**Issue by NishantaA** [microsoft/OpenAPI.NET#582]
The nuget downloaded Microsoft.OpenApi.Readers class does not contain the OpenApiStreamReader.ReadAsync method. The downloaded version 1.2.3 is the same as GitHub repo. Is there a way that I can get the most current dlls ? 

thanks.

![image](https://user-images.githubusercontent.com/30534912/114780055-80d56780-9d3c-11eb-8f4f-1ca2db10c720.png)

**Comment by darrelmiller** [comment]
I need to do a deployment, but we are currently blocked.  I will update as soon as I can.

**Comment by NishantaA** [comment]
thanks... no hurry, I will work around until available.

________________________________

**Comment by NishantaA** [comment]
Reinstalled using nuget, and the ReadAsync api is still not available and the latest version is still 1.2.3. The nuget package source is https://www.nuget.org/api/v2/. Should I point to some place else ?
