### ISSUE TITLE
OpenAPI "data and type mismatch found"

### ISSUE THREAD

**Issue by Thorium** [microsoft/OpenAPI.NET#587]
I'm trying to read this schema:
https://developer.experian.com/system/files/2020-12/credit-profile-product-apis-v-openapi3.2.0.45.yaml

I'm getting a lot of "Data and type mismatch found" errors.
And indeed, it seems that the types vary:
permissiblePurpose/type seems to be sometimes 08 and sometimes '08' and sometimes just ''.

Is the schema totally un-usable wtih OpenAPI.NET, or is it still possible to use it by forcing the types manually (with some parameter maybe?), so that the type is "either string or int" or "force to string"?

I don't care the solution details, I do care a workaround to get this ~10k lines of type-definitions into use easily.

**Comment by darrelmiller** [comment]
This was a rule that should never have been added as a rule that produces an error.
