### ISSUE TITLE
OpenApi data and type mismatch - example schema request being processed

### ISSUE THREAD

**Issue by wilsoncg** [microsoft/OpenAPI.NET#590]
I'm having difficulty using this library to consume public APIs. I'm getting `Data and type mismatch` errors, it seems the library is parsing the example schema and failing.

Here is the code I am executing when trying to communicate with [this wayback Open API](https://api.apis.guru/v2/specs/archive.org/wayback/1.0.0/openapi.json):
```fsharp
#r "nuget:SwaggerProvider"

open SwaggerProvider
let [<Literal>] Schema = "https://api.apis.guru/v2/specs/archive.org/wayback/1.0.0/openapi.json"
type WayBack = OpenApiClientProvider<Schema>

let client = WayBack.Client()
client.GetWaybackV1Available("http://www.google.co.uk")
```

 I've also seen parse failures with an OpenAPI using custom string format. I think the problem lies in this `RuleHelper` [class](https://github.com/microsoft/OpenAPI.NET/blob/vnext/src/Microsoft.OpenApi/Validations/Rules/RuleHelpers.cs).
From the OpenAPI spec, string format is an [open value](https://swagger.io/docs/specification/data-models/data-types/#string), so string custom format should be supported?

**Comment by darrelmiller** [comment]
This rule has been removed from the default set of rules in the 1.3.0-preview library. It should not have created validation failures as it is not a MUST in the OpenAPI specification.

**Comment by wilsoncg** [comment]
Ah, I just tried today and was able to successfully call the API. 👍
