### ISSUE TITLE
"Yes" strings are being serialized without quotes in YAML

### ISSUE THREAD

**Issue by jcin193** [microsoft/OpenAPI.NET#593]
var result = new Microsoft.OpenApi.Models.OpenApiDocument()
    {
        Components = new Microsoft.OpenApi.Models.OpenApiComponents()
        {
            Schemas =
            {
                {
                    "a", new Microsoft.OpenApi.Models.OpenApiSchema()
                    {
                        Enum = new Microsoft.OpenApi.Any.OpenApiString[]
                        {
                            new Microsoft.OpenApi.Any.OpenApiString("Yes")
                        }
                    }
                }
            }
        }
    }.Serialize(OpenApiSpecVersion.OpenApi2_0, OpenApiFormat.Yaml);

results in

    swagger: '2.0'
    info: { }
    paths: { }
    definitions:
      a:
        enum:
          - Yes

which is not serialized as specified by input `OpenApiDocument`, as `Yes` in enum is a boolean `true` as per YAML spec. It should be surrounded by single quotes.

**Comment by darrelmiller** [comment]
YAML 1.2 removed these kind of implicit typings
>  We have removed unique implicit typing rules and have updated these rules to align them with JSON's productions
https://yaml.org/spec/1.2/spec.html

OpenAPI requires the use of YAML 1.2 and limited to the JSON Schema subset. https://spec.openapis.org/oas/v3.1.0#format

**Comment by jcin193** [comment]
Please note I'm serializing to OpenAPI 2.0 - https://spec.openapis.org/oas/v2.0#format doesn't say anything about YAML version
