### ISSUE TITLE
Failure To Handle External References

### ISSUE THREAD

**Issue by Cooksauce** [microsoft/OpenAPI.NET#603]
References to local files or external files outside of the file being parsed fail to parse correctly. The failure results in the properties being parsed to just be completely ignored.

`$ref: path.to.my.yaml`

Fails with diagnostic error:
`The reference string 'path.to.my.yaml' has invalid format.`

This appears to be caused by `OpenApiV3VersionService.ConvertToOpenApiReference(..)` expecting `ReferenceType? == null` for external references. However, `OpenApiV3Deserializer` is blindly passing in `ReferenceType.Schema`.

Links:
[OpenApiV3VersionService](https://github.com/microsoft/OpenAPI.NET/blob/1374d779bcd1afe87afd81ec0bceba178638d54f/src/Microsoft.OpenApi.Readers/V3/OpenApiV3VersionService.cs#L67)
[OpenApiV3Deserializer](https://github.com/microsoft/OpenAPI.NET/blob/1374d779bcd1afe87afd81ec0bceba178638d54f/src/Microsoft.OpenApi.Readers/V3/OpenApiSchemaDeserializer.cs#L286)

Is this a known issue?

**Comment by Cooksauce** [comment]
To clarify the use case here. It doesn't matter to me whether `OpenAPI.NET` can resolve the reference or not, I'm just trying to use it to parse a set of OpenAPI documents. This issue causes me a problem because it throws away the reference which could be able to at least be parse into the OpenAPI C# objects. It seems like this issue would also block any progress on the 'Workspace' feature or resolving of external references.

For example:
```
title: My Object
type: object
properties:
  code:
    type: integer
  something:
    $ref: 'path.to.my.yaml'
```

If you parse this with: 
```
var reader = new OpenApiStreamReader(new OpenApiReaderSettings() {
      ReferenceResolution = ReferenceResolutionSetting.DoNotResolveReferences
});
var modelSchema = reader.ReadFragment<OpenApiSchema>(stream, OpenApiSpecVersion.OpenApi3_0, out var diagnostic);
```

`modelSchema.Properties` is empty.

I would expect `modelSchema.Properties["something"].Reference.Id == "path.to.my.yaml"`

**Comment by darrelmiller** [comment]
@Cooksauce I would expect the example you show above to work as you expect.  It should also work as you expect if you online resolve internal references.  I'll take a look and see if I can repro your issue.

The external references should resolve completely if you provide an absolute path.  I need to work on resolving relative paths.

**Comment by V0v1kkk** [comment]
Hello @Cooksauce , @darrelmiller.
I have been tested new **Workspaces** feature too.

I have found root of the problem.
Responsibility to resolve external resource is delegating to `IStreamLoader` interface.
In the default implementation (`DefaultStreamLoader`) used _Uri_ for resolve references.
In this case format of correct reference is: `file://path.to.my.yaml`, but it's wrong for OpenAPI.

And it's not that I expect too.
I have written replacement for `DefaultStreamLoader`:
```cs
public class ResourceLoaderFixed : IStreamLoader
{
    private readonly string _mainFilePath;
    private readonly HttpClient _httpClient = new HttpClient();

    public ResourceLoaderFixed(string mainFilePath)
    {
        _mainFilePath = mainFilePath;
    }

    public Stream Load(Uri uri)
    {
        return LoadAsync(uri).GetAwaiter().GetResult();
    }

    public async Task<Stream> LoadAsync(Uri uri)
    {
        try
        {
            var uriScheme = uri.Scheme;
        
            switch (uriScheme)
            {
                case "file":
                    return File.OpenRead(uri.AbsolutePath);
                case "http":
                case "https":
                    return await _httpClient.GetStreamAsync(uri);
                default:
                    throw new ArgumentException("Unsupported scheme");
            }
        }
        catch (InvalidOperationException) // it seems that it's path to local file without 'file://' prefix
        {
            string originalAbsolutePath = uri.OriginalString;
            string compositeAbsolutePath = Path.Combine(_mainFilePath, uri.OriginalString);
            
            string finalFilePath;
            if (File.Exists(originalAbsolutePath))
            {
                finalFilePath = originalAbsolutePath;
            }
            else if (File.Exists(compositeAbsolutePath))
            {
                finalFilePath = compositeAbsolutePath;
            }
            else
            {
                throw new Exception($"Can't to resolve reference to {originalAbsolutePath}");
            }

            return File.OpenRead(finalFilePath);
        }
        
    }
}
```

And use it as follows:
```cs
var specificationPath = @"C:\Git_Root\Robocop\Veeam.AC.Web.REST\Specification\models\rest_v3.yaml";
var specificationFolder = Path.GetDirectoryName(specificationPath);

// Create a reader that will resolve all references
var reader = new OpenApiStreamReader(new OpenApiReaderSettings()
{
    ReferenceResolution = ReferenceResolutionSetting.ResolveAllReferences,
    CustomExternalLoader = new ResourceLoaderFixed(specificationFolder)
});

ReadResult result;
using (var stream = File.OpenRead(specificationPath))
{
    result = await reader.ReadAsync(stream);
}
```

I expected that **Micosoft.OpenAPI** will resolve all JSON references and inline all files into the one document.
But now the feature works wired.
I found the [great tutorial](https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-8-splitting-specification-file/) by specification splitting and I can do nothing of that.

In the current implementation you can reference only structural elements of OpenAPI. For example: schema, response, etc.
And furthermore, you need to add a header to each of secondary files:
```yaml
openapi: 3.0.0
info:
  title: Components for the main app
  version: 1.0.0
paths: {}
components:
```

## And another bug
1. Open the primary specification with a reference to a schema in another file.
2. Save the primary specification.

The reference will be replaced to the reference to the primary file, but the schema doesn't copy to primary file.

**Comment by darrelmiller** [comment]
Thanks for the additional info, this will be very helpful.  


Supporting of referencing external fragments will be supported.  However, you can only use $ref to replace referenceable components, not just any arbitrary chunk of JSON.

Inlining is not supposed to happen automatically.  There is a setting in the writer if you want to inline on write. https://github.com/microsoft/OpenAPI.NET/blob/a008173908103740770cb0f16cac4148cdc17766/src/Microsoft.OpenApi.Tool/OpenApiService.cs#L73

**Comment by V0v1kkk** [comment]
Thank @darrelmiller !

But `ReferenceInlineSetting` there are only three values: `DoNotInlineReferences`, `InlineLocalReferences` and `InlineAllReferences`.
In my case I want to inline only remote references. 😒 

Well, to be quite honest, I just want to split a huge specification (~34k lines in yaml) to smaller parts. 
And merge the parts together on preprocessing without losing any information (names of schemes for example).

The bug that I mentioned above can be even helpful.
If I copy all parts from secondary OpenApiDocuments to primary, references will be fixes automatically. 😆

**Comment by Cooksauce** [comment]
> @Cooksauce I would expect the example you show above to work as you expect. It should also work as you expect if you online resolve internal references. I'll take a look and see if I can repro your issue.

@darrelmiller Thanks for taking a look. To be clear, I'm not concerned even whether or not it can resolve the reference, I just need it to be able to read the $ref string without throwing an error which prevents other properties from being parsed.

Additionally, it's worth noting that `$ref: path.to.my.yaml#/` does work, while `$ref: path.to.my.yaml` does not. IMO, the `#/` part should not be required in order for parsing to work (_since they mean the same thing essentially_). You can see why that happens [here](https://github.com/microsoft/OpenAPI.NET/blob/1374d779bcd1afe87afd81ec0bceba178638d54f/src/Microsoft.OpenApi.Readers/V3/OpenApiV3VersionService.cs#L63). I have have the reader settings set to `ReferenceResolutionSetting.DoNotResolveReferences`. I've tried both with the latest stable nuget release and the latest preview.

**Comment by peteraritchie** [comment]
I think this is related:
```csharp
    var text = new OpenApiV3VersionService()
        .ConvertToOpenApiReference(
            "externalSchema.json#/externalPathSegment1/externalPathSegment2/externalPathSegment3", null)
            .ReferenceV3
```
`text` ends up being `"externalSchema.json#//externalPathSegment1/externalPathSegment2/externalPathSegment3"`

Note the two slashes `//` after the fragment indicator (#).

**Comment by peteraritchie** [comment]
> ```cs
> new OpenApiV3VersionService()
>         .ConvertToOpenApiReference(
>             "externalSchema.json#/externalPathSegment1/externalPathSegment2/externalPathSegment3", null)
>             .ReferenceV3
> ```

Interestingly, if I use realistic path segments (i.e:)

`new OpenApiV3VersionService() .ConvertToOpenApiReference( "externalSchema.json#/components/schemas/Pet", null) .ReferenceV3`

...I get `"common.yaml#/Pet"`

_But_ serializing that reference ends up with `"$ref: common.yaml#/Pet"` (via `new OpenApiV3VersionService() .ConvertToOpenApiReference( "common.yaml#/components/schemas/Pet", null) .SerializeAsYaml(OpenApiSpecVersion.OpenApi3_0)`

That is, processing `"externalSchema.json#/components/schemas/Pet"` when serialized back to a file becomes `"$ref: common.yaml#/Pet"`

---
this is with vNext
---
