### ISSUE TITLE
Weak Documentation

### ISSUE THREAD

**Issue by RichardKav** [microsoft/OpenAPI.NET#610]
Hi,

I've been looking at the documentation at: 

https://github.com/microsoft/OpenAPI.NET/wiki/GettingStarted and https://github.com/microsoft/OpenAPI.NET

The line: 

`// Write V2 as JSON`
`var outputString = openApiDocument.Serialize(OpenApiSpecVersion.OpenApi2_0, OpenApiFormat.Json);`

Doesn't seem to work, with inteli-sense showing: 'SerializeAsV3' or 'SerializeAsV2' as the only possibilities and no description on how to use them. What is the correct way?

My overall intent it to read in an api and dynamically call endpoints based upon what I discover from the API. I would also like to filter parts of the document out and return segments of the overall API description.

**Comment by darrelmiller** [comment]
@RichardKav This method is an extension method which unfortunately got placed in a separate namespace.  You will need to pull in Microsoft.OpenApi.Extensions to be able to use it.  https://github.com/microsoft/OpenAPI.NET/blob/vnext/src/Microsoft.OpenApi/Extensions/OpenApiSerializableExtensions.cs#L177

Until recently this has been an unfunded effort for the last couple of years, hence the sorry state of the docs and the slow progress.  It has largely been my weekend project.  Hopefully that will change now it has found a new home in the company.

**Comment by RichardKav** [comment]
Thank you for this, I don't think I'd have found the method otherwise.

**Comment by darrelmiller** [comment]
Thank you for taking the time to report the issue.  I added a a note to the Getting Started docs.  I think in a future version we can just remove that namespace.  It really isn't necessary.
