### ISSUE TITLE
Using Multiple Authentication Types With Logical And - Not Following Specification

### ISSUE THREAD

**Issue by MarianSWA** [microsoft/OpenAPI.NET#633]
Hey, I noticed a place in the library that does not follow the open API specification.

**Reference zone:** In the OpenApiOperation object there's an IList<OpenApiSecurityRequirement> called Security whic, according to the documentation above it's declaration allows: "Only one of the security requirement objects need to be satisfied to authorize a request." 
**Expected behaviour:** According to the specification this list should allow not only logical OR but AND too, as mentiones [here](https://swagger.io/docs/specification/authentication/)
"That is, security is an array of hashmaps, where each hashmap contains one or more named security schemes. Items in a hashmap are combined using logical AND, and array items are combined using logical OR. Security schemes combined via OR are alternatives – any one can be used in the given context. Security schemes combined via AND must be used simultaneously in the same request."

Is there something that can be done to match the specification? 
Or I am missing something, in which case I apologise and this can be closed, and maybe clarified in the code documentation.

Thanks!

**Comment by darrelmiller** [comment]
The Security property is an IList of SecurityRequirement objects.  Each SecurityRequirement object is a Map of SecuritySchemes.  

If there are multiple SecurityRequirements, then only one of the SecurityRequirements need to be met. That's the OR.

Within a SecurityRequirement object, all of the SecuritySchemes must be met. That's the AND.

Yes, it is complicated to understand.  That is the unfortunate price of the flexibility that is offered.  Hopefully, that clears this up a bit.
