### ISSUE TITLE
Support nullable properties with references

### ISSUE THREAD

**Issue by aelij** [microsoft/OpenAPI.NET#634]
Currently if we set `nullable: true` a property with a reference, the nullable attribute is not emitted. For example:

```yaml
schema:
  $ref: '#/definitions/Foo'
  nullable: true # not emitted
```

This can be useful when the nullability is per-property and not per-definition. So the reference schema can only be emitted once, and used both in nullable and non-nullable properties.

**Comment by darrelmiller** [comment]
This is not supported in OpenAPI v3.  It will be possible in V3.1

**Comment by darrelmiller** [comment]
However, you can do this with an oneOf construct.

**Comment by aelij** [comment]
Thanks!
