### ISSUE TITLE
Align input parameter names of hidi with kiota commandline tool

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/OpenAPI.NET#662]
As this tool will regularly be used with the kiota tool, it would make sense to align the command line names like input, output, etc.  

@danielmbaluka could you chat with @baywet to align.

**Comment by baywet** [comment]
for reference, here is kiota's parameters documentation at the moment, could you provide a reference for hidi's please?
https://microsoft.github.io/kiota/using.html

**Comment by MaggieKimani1** [comment]
@baywet, here is a link to hidi's documentation along with the parameters it accepts for both `transform` and `validate` commands.

**Comment by baywet** [comment]
@MaggieKimani1 Thanks for sharing the information, here is the diff:

| Name | Alias | Kiota | Hidi |
| ------ | ------ | ----- | ---- |
| backing-store | b | ✔️ | N/A |
| output | o | ✔️ | ✔️ |
| openapi | d | ✔️ | ✔️ |
| version | v | N/A | ✔️ |
| format | f | N/A | ✔️ |
| inline | i | N/A | ✔️ |
| resolveExternal | ex | N/A | ✔️ |
| filterByOperationIds | op | N/A | ✔️ |
| filterByTags | t | N/A | ✔️ |
| filterByCollection | c | N/A | ✔️ |
| language | l | ✔️ | N/A |
| loglevel | ll | ✔️ | ❌ |
| class-name | c | ✔️ | N/A |
| deserializer | ds | ✔️ | N/A |
| namespace-name | n | ✔️ | N/A | 
| serializer | s | ✔️ | N/A |

Some differences: 

- For multi-word parameters, should the convention be kebab case, or lower camel case?
- Hidi should allow to set the logging level for by users.
- Some parameters aliases conflict between the two tools. Those are for parameters that only apply to one tool. I don't think it's a big issue but I wanted to outline it just in case.

**Comment by MaggieKimani1** [comment]
> @MaggieKimani1 Thanks for sharing the information, here is the diff:
> 
> Name	Alias	Kiota	Hidi
> backing-store	b	✔️	N/A
> output	o	✔️	✔️
> openapi	d	✔️	✔️
> version	v	N/A	✔️
> format	f	N/A	✔️
> inline	i	N/A	✔️
> resolveExternal	ex	N/A	✔️
> filterByOperationIds	op	N/A	✔️
> filterByTags	t	N/A	✔️
> filterByCollection	c	N/A	✔️
> language	l	✔️	N/A
> loglevel	ll	✔️	❌
> class-name	c	✔️	N/A
> deserializer	ds	✔️	N/A
> namespace-name	n	✔️	N/A
> serializer	s	✔️	N/A
> Some differences:
> 
> * For multi-word parameters, should the convention be kebab case, or lower camel case?
> * Hidi should allow to set the logging level for by users.
> * Some parameters aliases conflict between the two tools. Those are for parameters that only apply to one tool. I don't think it's a big issue but I wanted to outline it just in case.

@baywet Thank you for outlining this in a visually presentable format!
- I believe @darrelmiller can offer some insight on whether we should retain our camel-case naming convention or adopt the kebab case for consistency across both tools.
- Does this mean we should add a logging level param to hidi? @darrelmiller 
- As for the conflicting params, I only identified `--input` and `--output` as the common aliases across both tools hence updated them. Will the other aliases be problematic and if so, how?

**Comment by baywet** [comment]
IMHO having colliding aliases for different parameters on the two tools is not a big issue, but I wanted to get the teams consensus on that aspect.
The bigger experience problems being the kebab/lower camel case for multiple word parameters and the logging aspect.

**Comment by darrelmiller** [comment]
Vincent and I chatted.  
- Create the input parameters as -csdl and -openapi.  
- We checked the Graph CLI and Az CLI and they use lower kebab-case so we should too.

**Comment by baywet** [comment]
and lastly, add the loglevel parameter for observability, especially when people use the tool as part of a CI workflow.

**Comment by MaggieKimani1** [comment]
Noted.
