### ISSUE TITLE
External references

### ISSUE THREAD

**Issue by leolplex** [microsoft/OpenAPI.NET#669]
Hi,

My current scenario is, I have 3 files one of them is the main file, this one has references to the other 2 files (schemas, parameters). Is there some way to configure OpenAPI.Net to load those external files and get only one final file with all external references in this one?

Thank you so much.

**Comment by darrelmiller** [comment]
It is almost working.  It should be resolved before we release 1.3.0

**Comment by darrelmiller** [comment]
External references of complete OpenAPI Documents now works in 1.3.  External references to fragments does not.
