### ISSUE TITLE
fsharp example to build a document

### ISSUE THREAD

**Issue by jkone27** [microsoft/OpenAPI.NET#672]
do you have an F# example to build a document, or could you add a more functional builder for F# users? 

e.g. a CE like , just an example but for sure would become easier to build this object from F#

https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/computation-expressions

```fsharp

let document = 
    openapi {
           version "1"
           get "/test" 
           post "/testthis"
    
    //..
    }

```

**Comment by jkone27** [comment]
i have found this : 
https://github.com/akhansari/FSharp.OpenApi

**Comment by xperiandri** [comment]
@jkone27 thanks for posting!
