### ISSUE TITLE
Add support for DateOnly and/or DateTime.

### ISSUE THREAD

**Issue by TeunKooijman** [microsoft/OpenAPI.NET#680]
With the introduction of `DateOnly` and `TimeOnly` in .NET 6.0, it would be beneficial to support these value types in OpenAPI.NET as well. The biggest downside here is of course that you wouldn't be able to publish it under netstandard2.0 (as far as I know).

Just looking to start a conversation as to whether this would be possible.

**Comment by darrelmiller** [comment]
We might need to pull all rich typing out of this library in v2 because OpenAPI 3.1 uses native JSON Schema and it is limited to JSON types.
We may be able add support for setting a corresponding `format` property that corresponds to DateOnly and TimeOnly, but you could do that now also.

What is the scenario you are using OpenAPI.NET for?

**Comment by zijianhuang** [comment]
IMHO, DateOnly had already been supported well in Swagger 2.0 and OpenApi 3.0 already, as described on https://swagger.io/docs/specification/data-models/data-types/#string
and
https://swagger.io/docs/specification/data-models/data-types/

```
date – full-date notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), for example, 2017-07-21
date-time – the date-time notation as defined by [RFC 3339, section 5.6](https://tools.ietf.org/html/rfc3339#section-5.6), for example, 2017-07-21T17:32:28Z
```

[OpenApiClientGen](https://github.com/zijianhuang/openapiclientgen) has supported string/date with DateOnly in C# codes generated.

For example, [C# codes generated] contains a lot DateOnly properties for [Medicare Online definition file](https://github.com/zijianhuang/openapiclientgen/blob/master/Tests/SwagTests/SwagMock/mcp.yaml)

 Therefore, nothing needs to be done in OpenApi.NET regarding the OP.

**Comment by MaggieKimani1** [comment]
Closing this issue in favour of JSON schema support in 3.1.
