### ISSUE TITLE
Add support for packaging and publishing hidi as an executable file to Github

### ISSUE THREAD

**Issue by MaggieKimani1** [microsoft/OpenAPI.NET#731]
We need to add capability to publish hidi as an .exe to NuGet for users operating outside of the Windows environment e.g Linux users

**Comment by darrelmiller** [comment]
The EXE will only be published to the GitHub releases page.  We can't publish an EXE in Nuget.

**Comment by MaggieKimani1** [comment]
Thank you for the correction. Editing the issue title 🙂
