### ISSUE TITLE
Removal of .NET Framework support?

### ISSUE THREAD

**Issue by ShaunLoganOracle** [microsoft/OpenAPI.NET#751]
I saw [this commit](https://github.com/microsoft/OpenAPI.NET/commit/b98a4cb2e2a7f293d3ef53eee1af54c5763d0b0b).

I may not be following the intent or effect of this change, but if the intent is to drop .NET Framework support, please do not! Please restore support for .NET framework version 4.x. Our solutions cannot be migrated to .NET Core.

What is the thinking/policy about supporting .NET Framework 4.x? Microsoft's [support policy](https://docs.microsoft.com/en-us/lifecycle/products/microsoft-net-framework) shows no end dates for 4.6.2-4.8.

**Comment by ShaunLoganOracle** [comment]
One additional detail: our solution is targeting .NET Framework 4.7, so we're requesting that support for that version be restored.

**Comment by darrelmiller** [comment]
@ShaunLoganOracle Support for .NET Standard 2.0 should be sufficient for .NET Framework 4.7  https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0  

You shouldn't need us to support .NET 46 framework support to be able use the library in your application.  Would it be possible for you to try the 1.3.0 preview and confirm that it works for you?

**Comment by ShaunLoganOracle** [comment]
Thank you. We'll give that a try.

**Comment by ShaunLoganOracle** [comment]
Thanks, that seems to work with our development boxes; we still have some pending work to certify on end-user set ups.

**Comment by darrelmiller** [comment]
Please re-open this issue if you find problems.
