### ISSUE TITLE
Enable Hidi users to configure the way CSDL is translated to OpenAPI

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/OpenAPI.NET#830]
The conversion library has many settings.  To control these settings we should provide a command line parameter that points to a settings file that configures the behavior of the conversion library.

If the user points to a file that does not exist, we should create the file, filled with the default settings.

**Comment by irvinesunday** [comment]
> The conversion library has many settings. To control these settings we should provide a command line parameter that points to a settings file that configures the behavior of the conversion library.
> 
> If the user points to a file that does not exist, we should create the file, filled with the default settings.

Probably an XML file?

**Comment by irvinesunday** [comment]
How can an application like DevX API make use of this when using Hidi for conversion? Could it be possible to pass the settings programmatically?

**Comment by MaggieKimani1** [comment]
> > The conversion library has many settings. To control these settings we should provide a command line parameter that points to a settings file that configures the behavior of the conversion library.
> > If the user points to a file that does not exist, we should create the file, filled with the default settings.
> 
> Probably an XML file?

We're thinking of a JSON file

**Comment by darrelmiller** [comment]
@irvinesunday DevX API should never be calling hidi.  Hidi is a commandline tool.

**Comment by darrelmiller** [comment]
@MaggieKimani1 I have a PR started for this, so I can take this on if you have other tasks to complete.
