### ISSUE TITLE
Convert / Deserialize OpenApiSchema to Json schema

### ISSUE THREAD

**Issue by leolplex** [microsoft/OpenAPI.NET#833]
Hello all,

Somebody knows how can I convert a OpenApiSchema to Json Schema.?

Any help will be appreciated 👍

**Comment by JoeTomkinson** [comment]
I would also quite like to see this. Is there a proper MSDoc page for this, the Wiki here seems a little light. I'd love to see more detailed documentation. Perhaps I'm overlooking the location.

**Comment by darrelmiller** [comment]
We're starting to work on complete docs.  Sorry it took so long to get around to it.

If you are just looking to emit the OpenAPI 3.0 flavour of JSON Schema then this will do it for you.

```csharp
using Microsoft.OpenApi.Readers;
using Microsoft.OpenApi.Writers;

var reader = new OpenApiStreamReader();

var result = await reader.ReadAsync(new FileStream("openapi.yaml", FileMode.Open));

foreach (var schemaEntry in result.OpenApiDocument.Components.Schemas)
{
    var schemaFileName = schemaEntry.Key + ".json";
    Console.WriteLine("Creating " + schemaFileName);
    using FileStream? fileStream = new FileStream(schemaFileName, FileMode.CreateNew);
    using var writer = new StreamWriter(fileStream);
    schemaEntry.Value.SerializeAsV3WithoutReference(new OpenApiJsonWriter(writer));
}

```

**Comment by JoeTomkinson** [comment]
Not a problem, it's understandable, documentation ends up taking up alot more time than anyone intends for it to take up. So it does usually get pushed out towards the back end. 

Thank you for the response and the code snippet. I ended up doing something similar, didn't realise that we could actually serialize it using that method. I can still see that there are some internal "$ref" properties that don't seem to get resolved, is that intended, or is it likely down to issues with the Open API spec itself in your experience?

**Comment by darrelmiller** [comment]
Ahh, if you want to inline all the references you can pass a OpenApiWriterSettings to the constructor of the Writer and set  InlineLocalReferences to true.

**Comment by JoeTomkinson** [comment]
That worked an absolute treat.
