### ISSUE TITLE
OpenAPI v2 is not read properly when Produces/Consumes is not provided

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/OpenAPI.NET#842]
Related: #706 

The OpenAPI v2 specification is not clear that Produces/Consumes are required to be able to completely describe an API request/response.

This means that when OpenAPI v2 documents are read in, if they don't have a produces/consumes then there is no media type object created and there is nowhere to put any schema that has been specified.

By adding a `defaultContentType` property to the OpenApiReaderSettings object we can use that to create a content object if there is no produces/consumes and we will not lose the schema information.  This will not change the default behavior of library.

**Comment by darrelmiller** [comment]
It turns out we already have code that assumes application/json for a body or application/x-url-encoded-form for form data.  The only thing that was missing was a check for an empty consumes/produces array.  Considering this feature only causes issues for V2 I am reluctant to add another reader setting unless we have customers asking for it.

**Comment by MaggieKimani1** [comment]
I concur on not adding a new reader setting if we can retain the schema info by adding the missing check.
