### ISSUE TITLE
Error on `SerializeAsV2` when `InlineLocalReferences = true`

### ISSUE THREAD

**Issue by irvinesunday** [microsoft/OpenAPI.NET#850]
Serializing an OpenAPI document as V2 throws an error `"Value cannot be null. (Parameter 'source')"` when `InlineLocalReferences = true` e.g., 
```
OpenApiWriterBase writer = new OpenApiYamlWriter(sr,
                        new OpenApiWriterSettings { InlineLocalReferences = true});
```
The error gets thrown when serializing the OpenAPI document as V2, i.e., `OpenApiDocument.SerializeAsV2(writer)`

This affects both `OpenApiJsonWriter` and `OpenApiYamlWriter` classes.
This affects the latest version of `Microsoft.OpenAPI.Readers` `v1.3.1`

**Comment by darrelmiller** [comment]
Closing this.  Please re-open if anyone is able to repro.

**Comment by millicentachieng** [comment]
We have the same error occurring in the Open API OData conversion library. I've tracked down the error and created the PR #978 to fix it.
