### ISSUE TITLE
hidi transform creates an extensionless `output` file

### ISSUE THREAD

**Issue by MaximRouiller** [microsoft/OpenAPI.NET#877]
## Steps to reproduce

`hidi transform --inlineLocal -d https://raw.githubusercontent.com/Azure/azure-rest-api-specs/main/specification/resources/resource-manager/Microsoft.Resources/stable/2021-04-01/resources.json`

## Expected result

Have a default file with the extension associated with the format it contains (`output.json` or `output.yaml`)

## Actual result

File called `output` without any extension.

<img width="862" alt="image" src="https://user-images.githubusercontent.com/209384/169549393-1e87e776-cdc6-4ef3-80f0-71d9946d68da.png">

**Comment by CarolKigoonya** [comment]
We will set the extension based on the output format (this is determined by the input)

**Comment by MaggieKimani1** [comment]
As @CarolKigoonya has mentioned, we can infer the file format from the input file extension and use it as a default for when an output path is not provided.
Currently, we default to `./output`
