### ISSUE TITLE
DisplayAttribute is not public

### ISSUE THREAD

**Issue by fernandolamp** [microsoft/OpenAPI.NET#889]
Hi! 

I'm writing an `OpenApiOperation` extension using enum and I've noticed that it has a method named `GetDisplayName` to use a display name instead of a enum name.

https://github.com/microsoft/OpenAPI.NET/blob/1280e48768f60f03fc62d6bc54fc8478ca60b242/src/Microsoft.OpenApi/Extensions/EnumExtensions.cs#L40

```
        /// <summary>
        /// Gets the enum display name.
        /// </summary>
        /// <param name="enumValue">The enum value.</param>
        /// <returns>
        /// Use <see cref="DisplayAttribute"/> if exists.
        /// Otherwise, use the standard string representation.
        /// </returns>

```
But, `DisplayAttribute` is a private attribute and it's not possible to use them.

https://github.com/microsoft/OpenAPI.NET/blob/1280e48768f60f03fc62d6bc54fc8478ca60b242/src/Microsoft.OpenApi/Attributes/DisplayAttribute.cs#L12

Is it possible to change this attribute to be  public instead internal class?

Example of use:

```csharp

   //my enum, used on docOptions
    public enum ApiLevel
    {
        [DisplayAttribute(Name = "private")]
        Privada = 1,
        [Display(Name = "public")]
        Publica = 2,
        [Display(Name = "corporate")]        
        Corporativa = 3
    }

//my filter where i use the enum
    internal class OpenApiExampleFilter : IOperationFilter
    {
        private readonly DocOptions _docOptions;

        public OpenApiExampleFilter (DocOptions docOptions)
        {
            _docOptions = docOptions;
        }

        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {           
            operation.AddExtension("x-test", new OpenApiObject
            {
                ["apiLevel"] = new OpenApiString(_docOptions.ApiLevel.GetDisplayName()), //here i cant use GetDisplayName() :(
                ["apiDomain"] = new OpenApiString(_docOptions.ApiDomain)
            });
        }
    }
```

Tks!

**Comment by darrelmiller** [comment]
That seems like a reasonable request to me.

**Comment by CodeCasterNL** [comment]
@darrelmiller any reason not to use System.ComponentModel.DataAnnotations.DisplayAttribufe?

**Comment by fernandolamp** [comment]
> @darrelmiller any reason not to use System.ComponentModel.DataAnnotations.DisplayAttribufe?

This make sense. I can change if @darrelmiller  agrees.

**Comment by CodeCasterNL** [comment]
On the other hand, one might want to differ between `DataAnnotations.Display` for MVC purposes, and `OpenApi.Attributes.Display` for OpenAPI descriptions.

**Comment by fernandolamp** [comment]
> On the other hand, one might want to differ between `DataAnnotations.Display` for MVC purposes, and `OpenApi.Attributes.Display` for OpenAPI descriptions, I think? Not sure what the intended usage for the attribute is, other than to annotate your classes exposed from your API?

I was analyzing the code. Display attribute is used to standardize the display name of the enum.

![image](https://user-images.githubusercontent.com/18193204/183803561-77470c04-d3cb-418a-bea7-3f2e5ffa0b16.png)

And get enum  from display name on `StringExtensions`

https://github.com/microsoft/OpenAPI.NET/blob/a17303c382e33baee31bb4fe2cb2093c6cbb822b/src/Microsoft.OpenApi/Extensions/StringExtensions.cs#L19

In my code i'm using to solve the same problem, i need to expose this enums using lower case and translated.

Both attribute is used to the same thing, but to use from  `System.ComponentModel.DataAnnotations` is necessary install the package `System.ComponentModel.Annotations`.  

I don't know if reference this package in this project is a problem. If not, this change make sense and is simple.

I made this change in my local branch and all test have passed, i can push if there is no problem.

**Comment by CodeCasterNL** [comment]
@MaggieKimani1 or @darrelmiller can you chime in on the discussion? Does the attribute need to exist in the first place? Less code being more and all.

**Comment by darrelmiller** [comment]
@CodeCasterNL I agree less code is more, and the problem with System.ComponentModel.DataAnnotations is that it pulls in all kinds other code that we don't use and don't support.  The DisplayAttribute class is only a few lines of code.  I'd rather not take another dependency for just this small feature.

**Comment by CodeCasterNL** [comment]
@darrelmiller sorry, I meant [`System.ComponentModel.DisplayNameAttribute`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.displaynameattribute?view=netstandard-2.0), which is covered in netstandard2.0.
