### ISSUE TITLE
Hidi returns exit code 0 even when failing on mac

### ISSUE THREAD

**Issue by fellnerse** [microsoft/OpenAPI.NET#900]
Hello here is the log form my terminal:
```bash
bash-3.2$ hidi validate -d core/openapi.yml -ll trace
trce: Microsoft.OpenApi.Hidi.OpenApiService[0]
      => Reading input stream
      5ms: Read file core/openapi.yml
crit: Microsoft.OpenApi.Hidi.OpenApiService[0]
      OpenAPI specification version '' is not supported.
bash-3.2$ echo $?
0
bash-3.2$ hidi --version
1.0.0-preview4+b04aecd4a4955f71bc8f1a21ac74b8ac0976cb2a
```

The file I'm validating is just wrong for the purpose of demonstration, it starts like this:

```yaml
openapiWRONG: 3.0.3
...
```
Do you have an idea how I can get the correct exit code? It seems like it does not even print to the stderr but everything is printed to stdout.

**Comment by zengin** [comment]
might be related: https://github.com/microsoft/kiota/issues/1605

**Comment by fellnerse** [comment]
I'm not sure thats a different repo; but if the same fix works I'd be happy! its really annoying to have to parse the output of the tool

**Comment by fellnerse** [comment]
No this is not fixed:

```bash
bash-3.2$ hidi validate -d public/openapi.yml2 --ll Trace
crit: Microsoft.OpenApi.Hidi.OpenApiService[0]
      Could not validate the document, reason: Could not open the file at public/openapi.yml2
bash-3.2$ echo $?
0
bash-3.2$ hidi --version
1.1.0+40d67ac929299fd007cc6bf9e5cf44e83187f948
```

Might make sense to validate such things before closing an issue.
