### ISSUE TITLE
Flow of context and reference setting in the reader strange and potentially circular

### ISSUE THREAD

**Issue by PerthCharern** [Microsoft/OpenAPI.NET#91]
@andystumpp 

"In order to set the reference service in the context, you need the rootnode, for that though you need the context to have (partially?) initialized... Is there some potential circular reference?"

This is a valid concern. Even if we do not have any circular reference, the flow seems a little strange and difficult to understand and debug if there are any issues later on.

**Comment by darrelmiller** [comment]
This cycle has now gone.  The ParsingContext determines the version using the RootNode and then loads the appropriate VersionService (replacement for ReferenceService).
