### ISSUE TITLE
Missing release definition for 1.4.0-preview1

### ISSUE THREAD

**Issue by DamianEdwards** [microsoft/OpenAPI.NET#964]
Seems version [1.4.0-preview1 is on NuGet](https://www.nuget.org/packages/Microsoft.OpenApi/1.4.0-preview1) but there's no release defined for it here on the [repo releases page](https://github.com/microsoft/OpenAPI.NET/releases).

@MaggieKimani1 @darrelmiller

**Comment by MaggieKimani1** [comment]
Hi @DamianEdwards, thank you for pointing this out. We have an automated Github release notes task in our pipeline that does the changelog for Hidi. I'll make sure to add the same for the OpenAPI libs as well.

**Comment by MaggieKimani1** [comment]
@DamianEdwards [here](https://github.com/microsoft/OpenAPI.NET/releases/tag/1.4.0-preview1) is a link to the current release definition as I investigate why our automated task in our pipeline didn't work.
